package typingsJapgolly.typescript.mod.server

import typingsJapgolly.typescript.typescriptStrings.actionColonColoninvalidate
import typingsJapgolly.typescript.typescriptStrings.actionColonColonpackageInstalled
import typingsJapgolly.typescript.typescriptStrings.actionColonColonset
import typingsJapgolly.typescript.typescriptStrings.eventColonColonbeginInstallTypes
import typingsJapgolly.typescript.typescriptStrings.eventColonColonendInstallTypes
import typingsJapgolly.typescript.typescriptStrings.eventColonColoninitializationFailed
import typingsJapgolly.typescript.typescriptStrings.eventColonColontypesRegistry
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


type ActionInvalidate = actionColonColoninvalidate

type ActionPackageInstalled = actionColonColonpackageInstalled

type ActionSet = actionColonColonset

type EventBeginInstallTypes = eventColonColonbeginInstallTypes

type EventEndInstallTypes = eventColonColonendInstallTypes

type EventInitializationFailed = eventColonColoninitializationFailed

type EventTypesRegistry = eventColonColontypesRegistry
