package typingsJapgolly.reactNativeWindows.rntypesMod

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALENDAR
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALENDAR
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCAMERA
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CONTACTS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CONTACTS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotGET_ACCOUNTS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_FINE_LOCATION
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_COARSE_LOCATION
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_BACKGROUND_LOCATION
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECORD_AUDIO
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_PHONE_STATE
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCALL_PHONE
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALL_LOG
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALL_LOG
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.comDotandroidDotvoicemailDotpermissionDotADD_VOICEMAIL
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotUSE_SIP
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotPROCESS_OUTGOING_CALLS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotBODY_SENSORS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotSEND_SMS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_SMS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_SMS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_WAP_PUSH
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_MMS
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_EXTERNAL_STORAGE
  - typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_EXTERNAL_STORAGE
*/
trait Permission extends StObject
object Permission {
  
  inline def androidDotpermissionDotACCESS_BACKGROUND_LOCATION: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_BACKGROUND_LOCATION = "android.permission.ACCESS_BACKGROUND_LOCATION".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_BACKGROUND_LOCATION]
  
  inline def androidDotpermissionDotACCESS_COARSE_LOCATION: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_COARSE_LOCATION = "android.permission.ACCESS_COARSE_LOCATION".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_COARSE_LOCATION]
  
  inline def androidDotpermissionDotACCESS_FINE_LOCATION: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_FINE_LOCATION = "android.permission.ACCESS_FINE_LOCATION".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotACCESS_FINE_LOCATION]
  
  inline def androidDotpermissionDotBODY_SENSORS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotBODY_SENSORS = "android.permission.BODY_SENSORS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotBODY_SENSORS]
  
  inline def androidDotpermissionDotCALL_PHONE: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCALL_PHONE = "android.permission.CALL_PHONE".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCALL_PHONE]
  
  inline def androidDotpermissionDotCAMERA: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCAMERA = "android.permission.CAMERA".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotCAMERA]
  
  inline def androidDotpermissionDotGET_ACCOUNTS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotGET_ACCOUNTS = "android.permission.GET_ACCOUNTS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotGET_ACCOUNTS]
  
  inline def androidDotpermissionDotPROCESS_OUTGOING_CALLS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotPROCESS_OUTGOING_CALLS = "android.permission.PROCESS_OUTGOING_CALLS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotPROCESS_OUTGOING_CALLS]
  
  inline def androidDotpermissionDotREAD_CALENDAR: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALENDAR = "android.permission.READ_CALENDAR".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALENDAR]
  
  inline def androidDotpermissionDotREAD_CALL_LOG: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALL_LOG = "android.permission.READ_CALL_LOG".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CALL_LOG]
  
  inline def androidDotpermissionDotREAD_CONTACTS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CONTACTS = "android.permission.READ_CONTACTS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_CONTACTS]
  
  inline def androidDotpermissionDotREAD_EXTERNAL_STORAGE: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_EXTERNAL_STORAGE = "android.permission.READ_EXTERNAL_STORAGE".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_EXTERNAL_STORAGE]
  
  inline def androidDotpermissionDotREAD_PHONE_STATE: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_PHONE_STATE = "android.permission.READ_PHONE_STATE".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_PHONE_STATE]
  
  inline def androidDotpermissionDotREAD_SMS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_SMS = "android.permission.READ_SMS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotREAD_SMS]
  
  inline def androidDotpermissionDotRECEIVE_MMS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_MMS = "android.permission.RECEIVE_MMS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_MMS]
  
  inline def androidDotpermissionDotRECEIVE_SMS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_SMS = "android.permission.RECEIVE_SMS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_SMS]
  
  inline def androidDotpermissionDotRECEIVE_WAP_PUSH: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_WAP_PUSH = "android.permission.RECEIVE_WAP_PUSH".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECEIVE_WAP_PUSH]
  
  inline def androidDotpermissionDotRECORD_AUDIO: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECORD_AUDIO = "android.permission.RECORD_AUDIO".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotRECORD_AUDIO]
  
  inline def androidDotpermissionDotSEND_SMS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotSEND_SMS = "android.permission.SEND_SMS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotSEND_SMS]
  
  inline def androidDotpermissionDotUSE_SIP: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotUSE_SIP = "android.permission.USE_SIP".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotUSE_SIP]
  
  inline def androidDotpermissionDotWRITE_CALENDAR: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALENDAR = "android.permission.WRITE_CALENDAR".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALENDAR]
  
  inline def androidDotpermissionDotWRITE_CALL_LOG: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALL_LOG = "android.permission.WRITE_CALL_LOG".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CALL_LOG]
  
  inline def androidDotpermissionDotWRITE_CONTACTS: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CONTACTS = "android.permission.WRITE_CONTACTS".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_CONTACTS]
  
  inline def androidDotpermissionDotWRITE_EXTERNAL_STORAGE: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_EXTERNAL_STORAGE = "android.permission.WRITE_EXTERNAL_STORAGE".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.androidDotpermissionDotWRITE_EXTERNAL_STORAGE]
  
  inline def comDotandroidDotvoicemailDotpermissionDotADD_VOICEMAIL: typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.comDotandroidDotvoicemailDotpermissionDotADD_VOICEMAIL = "com.android.voicemail.permission.ADD_VOICEMAIL".asInstanceOf[typingsJapgolly.reactNativeWindows.reactNativeWindowsStrings.comDotandroidDotvoicemailDotpermissionDotADD_VOICEMAIL]
}
