package typingsJapgolly.officeUiFabricReact.libComponentsDetailsListDetailsListDottypesMod

import typingsJapgolly.officeUiFabricReact.libComponentsDetailsListDetailsRowCheckDottypesMod.IDetailsCheckboxProps
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


type IDetailsListCheckboxProps = IDetailsCheckboxProps
