package typingsJapgolly.ionicAngular.directivesProxiesMod

import org.scalajs.dom.HTMLElement
import typingsJapgolly.angularCore.mod.ChangeDetectorRef
import typingsJapgolly.angularCore.mod.ElementRef
import typingsJapgolly.angularCore.mod.NgZone
import typingsJapgolly.angularCore.mod.ɵɵComponentDeclaration
import typingsJapgolly.angularCore.mod.ɵɵFactoryDeclaration
import typingsJapgolly.ionicAngular.anon.Disabled
import typingsJapgolly.ionicAngular.ionicAngularBooleans.`false`
import typingsJapgolly.ionicAngular.ionicAngularStrings.Asterisk
import typingsJapgolly.ionicAngular.ionicAngularStrings.`ion-accordion`
import typingsJapgolly.ionicCore.ionicCoreStrings.end
import typingsJapgolly.ionicCore.ionicCoreStrings.start
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@ionic/angular/directives/proxies", "IonAccordion")
@js.native
open class IonAccordion protected ()
  extends StObject
     with typingsJapgolly.ionicCore.distTypesComponentsMod.Components.IonAccordion {
  def this(c: ChangeDetectorRef, r: ElementRef[Any], z: NgZone) = this()
  
  /**
    * If `true`, the accordion cannot be interacted with.
    */
  /* CompleteClass */
  var disabled: Boolean = js.native
  
  /* protected */ var el: HTMLElement = js.native
  
  /**
    * If `true`, the accordion cannot be interacted with, but does not alter the opacity.
    */
  /* CompleteClass */
  var readonly: Boolean = js.native
  
  /**
    * The toggle icon to use. This icon will be rotated when the accordion is expanded or collapsed.
    */
  /* CompleteClass */
  var toggleIcon: String = js.native
  
  /**
    * The slot inside of `ion-item` to place the toggle icon. Defaults to `'end'`.
    */
  /* CompleteClass */
  var toggleIconSlot: start | end = js.native
  
  /**
    * The value of the accordion. Defaults to an autogenerated value.
    */
  /* CompleteClass */
  var value: String = js.native
  
  /* protected */ var z: NgZone = js.native
}
/* static members */
object IonAccordion {
  
  @JSImport("@ionic/angular/directives/proxies", "IonAccordion")
  @js.native
  val ^ : js.Any = js.native
  
  @JSImport("@ionic/angular/directives/proxies", "IonAccordion.\u0275cmp")
  @js.native
  def ɵcmp: ɵɵComponentDeclaration[
    IonAccordion, 
    `ion-accordion`, 
    scala.Nothing, 
    Disabled, 
    js.Object, 
    scala.Nothing, 
    js.Array[Asterisk], 
    `false`
  ] = js.native
  inline def ɵcmp_=(
    x: ɵɵComponentDeclaration[
      IonAccordion, 
      `ion-accordion`, 
      scala.Nothing, 
      Disabled, 
      js.Object, 
      scala.Nothing, 
      js.Array[Asterisk], 
      `false`
    ]
  ): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("\u0275cmp")(x.asInstanceOf[js.Any])
  
  @JSImport("@ionic/angular/directives/proxies", "IonAccordion.\u0275fac")
  @js.native
  def ɵfac: ɵɵFactoryDeclaration[IonAccordion, scala.Nothing] = js.native
  inline def ɵfac_=(x: ɵɵFactoryDeclaration[IonAccordion, scala.Nothing]): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("\u0275fac")(x.asInstanceOf[js.Any])
}
