package typingsJapgolly.materialDashUi.components

import typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash3DashBarMod.default
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object SignalDashCellularDashConnectedDashNoDashInternetDash3DashBar extends SharedApply_SvgIconProps1538262166[default] {
  override val __component: js.Any = js.constructorOf[typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash3DashBarMod.default]
}

