package typingsJapgolly.materialDashUi.components

import typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash2DashBarMod.default
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object SignalDashCellularDashConnectedDashNoDashInternetDash2DashBar extends SharedApply_SvgIconProps1538262166[default] {
  override val __component: js.Any = js.constructorOf[typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash2DashBarMod.default]
}

