package typingsJapgolly.materialDashUi.components

import typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash0DashBarMod.default
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object SignalDashCellularDashConnectedDashNoDashInternetDash0DashBar extends SharedApply_typingsJapgollymaterialDashUiMaterialUISvgIconProps1538262166[default] {
  override val __component: js.Any = js.constructorOf[typingsJapgolly.materialDashUi.svgDashIconsDeviceSignalDashCellularDashConnectedDashNoDashInternetDash0DashBarMod.default]
}

