package typingsJapgolly.chromeApps.chrome.webViewRequest

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRequest
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeSendHeaders
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonSendHeaders
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonHeadersReceived
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonAuthRequired
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonResponseStarted
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRedirect
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonCompleted
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonErrorOccured
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonRequest
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonMessage
*/
trait DeclarativeWebRequestEventList extends StObject
object DeclarativeWebRequestEventList {
  
  inline def declarativeContentDotonAuthRequired: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonAuthRequired = "declarativeContent.onAuthRequired".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonAuthRequired]
  
  inline def declarativeContentDotonBeforeRedirect: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRedirect = "declarativeContent.onBeforeRedirect".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRedirect]
  
  inline def declarativeContentDotonBeforeRequest: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRequest = "declarativeContent.onBeforeRequest".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeRequest]
  
  inline def declarativeContentDotonBeforeSendHeaders: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeSendHeaders = "declarativeContent.onBeforeSendHeaders".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonBeforeSendHeaders]
  
  inline def declarativeContentDotonCompleted: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonCompleted = "declarativeContent.onCompleted".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonCompleted]
  
  inline def declarativeContentDotonErrorOccured: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonErrorOccured = "declarativeContent.onErrorOccured".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonErrorOccured]
  
  inline def declarativeContentDotonHeadersReceived: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonHeadersReceived = "declarativeContent.onHeadersReceived".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonHeadersReceived]
  
  inline def declarativeContentDotonMessage: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonMessage = "declarativeContent.onMessage".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonMessage]
  
  inline def declarativeContentDotonRequest: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonRequest = "declarativeContent.onRequest".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonRequest]
  
  inline def declarativeContentDotonResponseStarted: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonResponseStarted = "declarativeContent.onResponseStarted".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonResponseStarted]
  
  inline def declarativeContentDotonSendHeaders: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonSendHeaders = "declarativeContent.onSendHeaders".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeContentDotonSendHeaders]
}
