package typingsJapgolly.chromeApps.chrome.webViewRequest

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension
  - typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules
*/
trait DeclarativeWebRequestActionsList extends StObject
object DeclarativeWebRequestActionsList {
  
  inline def declarativeWebRequestDotAddRequestCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie = "declarativeWebRequest.AddRequestCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie]
  
  inline def declarativeWebRequestDotAddResponseCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie = "declarativeWebRequest.AddResponseCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie]
  
  inline def declarativeWebRequestDotAddResponseHeader: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader = "declarativeWebRequest.AddResponseHeader".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader]
  
  inline def declarativeWebRequestDotCancelRequest: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest = "declarativeWebRequest.CancelRequest".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest]
  
  inline def declarativeWebRequestDotEditRequestCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie = "declarativeWebRequest.EditRequestCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie]
  
  inline def declarativeWebRequestDotEditResponseCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie = "declarativeWebRequest.EditResponseCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie]
  
  inline def declarativeWebRequestDotIgnoreRules: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules = "declarativeWebRequest.IgnoreRules".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules]
  
  inline def declarativeWebRequestDotRedirectByRegEx: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx = "declarativeWebRequest.RedirectByRegEx".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx]
  
  inline def declarativeWebRequestDotRedirectRequest: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest = "declarativeWebRequest.RedirectRequest".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest]
  
  inline def declarativeWebRequestDotRedirectToEmptyDocument: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument = "declarativeWebRequest.RedirectToEmptyDocument".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument]
  
  inline def declarativeWebRequestDotRedirectToTransparentImage: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage = "declarativeWebRequest.RedirectToTransparentImage".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage]
  
  inline def declarativeWebRequestDotRemoveRequestCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie = "declarativeWebRequest.RemoveRequestCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie]
  
  inline def declarativeWebRequestDotRemoveRequestHeader: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader = "declarativeWebRequest.RemoveRequestHeader".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader]
  
  inline def declarativeWebRequestDotRemoveResponseCookie: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie = "declarativeWebRequest.RemoveResponseCookie".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie]
  
  inline def declarativeWebRequestDotRemoveResponseHeader: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader = "declarativeWebRequest.RemoveResponseHeader".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader]
  
  inline def declarativeWebRequestDotSendMessageToExtension: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension = "declarativeWebRequest.SendMessageToExtension".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension]
  
  inline def declarativeWebRequestDotSetRequestHeader: typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader = "declarativeWebRequest.SetRequestHeader".asInstanceOf[typingsJapgolly.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader]
}
