package typingsJapgolly.awsSdk.configServicePlaceholdersMod

import typingsJapgolly.awsSdk.accessanalyzerMod.apiVersion
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ConfigurationServiceApiVersions extends js.Object {
  var accessanalyzer: js.UndefOr[apiVersion] = js.native
  var acm: js.UndefOr[typingsJapgolly.awsSdk.acmMod.apiVersion] = js.native
  var acmpca: js.UndefOr[typingsJapgolly.awsSdk.acmpcaMod.apiVersion] = js.native
  var alexaforbusiness: js.UndefOr[typingsJapgolly.awsSdk.alexaforbusinessMod.apiVersion] = js.native
  var amplify: js.UndefOr[typingsJapgolly.awsSdk.amplifyMod.apiVersion] = js.native
  var apigateway: js.UndefOr[typingsJapgolly.awsSdk.apigatewayMod.apiVersion] = js.native
  var apigatewaymanagementapi: js.UndefOr[typingsJapgolly.awsSdk.apigatewaymanagementapiMod.apiVersion] = js.native
  var apigatewayv2: js.UndefOr[typingsJapgolly.awsSdk.apigatewayv2Mod.apiVersion] = js.native
  var appconfig: js.UndefOr[typingsJapgolly.awsSdk.appconfigMod.apiVersion] = js.native
  var applicationautoscaling: js.UndefOr[typingsJapgolly.awsSdk.applicationautoscalingMod.apiVersion] = js.native
  var applicationinsights: js.UndefOr[typingsJapgolly.awsSdk.applicationinsightsMod.apiVersion] = js.native
  var appmesh: js.UndefOr[typingsJapgolly.awsSdk.appmeshMod.apiVersion] = js.native
  var appstream: js.UndefOr[typingsJapgolly.awsSdk.appstreamMod.apiVersion] = js.native
  var appsync: js.UndefOr[typingsJapgolly.awsSdk.appsyncMod.apiVersion] = js.native
  var athena: js.UndefOr[typingsJapgolly.awsSdk.athenaMod.apiVersion] = js.native
  var augmentedairuntime: js.UndefOr[typingsJapgolly.awsSdk.augmentedairuntimeMod.apiVersion] = js.native
  var autoscaling: js.UndefOr[typingsJapgolly.awsSdk.autoscalingMod.apiVersion] = js.native
  var autoscalingplans: js.UndefOr[typingsJapgolly.awsSdk.autoscalingplansMod.apiVersion] = js.native
  var backup: js.UndefOr[typingsJapgolly.awsSdk.backupMod.apiVersion] = js.native
  var batch: js.UndefOr[typingsJapgolly.awsSdk.batchMod.apiVersion] = js.native
  var budgets: js.UndefOr[typingsJapgolly.awsSdk.budgetsMod.apiVersion] = js.native
  var chime: js.UndefOr[typingsJapgolly.awsSdk.chimeMod.apiVersion] = js.native
  var cloud9: js.UndefOr[typingsJapgolly.awsSdk.cloud9Mod.apiVersion] = js.native
  var clouddirectory: js.UndefOr[typingsJapgolly.awsSdk.clouddirectoryMod.apiVersion] = js.native
  var cloudformation: js.UndefOr[typingsJapgolly.awsSdk.cloudformationMod.apiVersion] = js.native
  var cloudfront: js.UndefOr[typingsJapgolly.awsSdk.cloudfrontMod.apiVersion] = js.native
  var cloudhsm: js.UndefOr[typingsJapgolly.awsSdk.cloudhsmMod.apiVersion] = js.native
  var cloudhsmv2: js.UndefOr[typingsJapgolly.awsSdk.cloudhsmv2Mod.apiVersion] = js.native
  var cloudsearch: js.UndefOr[typingsJapgolly.awsSdk.cloudsearchMod.apiVersion] = js.native
  var cloudsearchdomain: js.UndefOr[typingsJapgolly.awsSdk.cloudsearchdomainMod.apiVersion] = js.native
  var cloudtrail: js.UndefOr[typingsJapgolly.awsSdk.cloudtrailMod.apiVersion] = js.native
  var cloudwatch: js.UndefOr[typingsJapgolly.awsSdk.cloudwatchMod.apiVersion] = js.native
  var cloudwatchevents: js.UndefOr[typingsJapgolly.awsSdk.cloudwatcheventsMod.apiVersion] = js.native
  var cloudwatchlogs: js.UndefOr[typingsJapgolly.awsSdk.cloudwatchlogsMod.apiVersion] = js.native
  var codebuild: js.UndefOr[typingsJapgolly.awsSdk.codebuildMod.apiVersion] = js.native
  var codecommit: js.UndefOr[typingsJapgolly.awsSdk.codecommitMod.apiVersion] = js.native
  var codedeploy: js.UndefOr[typingsJapgolly.awsSdk.codedeployMod.apiVersion] = js.native
  var codeguruprofiler: js.UndefOr[typingsJapgolly.awsSdk.codeguruprofilerMod.apiVersion] = js.native
  var codegurureviewer: js.UndefOr[typingsJapgolly.awsSdk.codegurureviewerMod.apiVersion] = js.native
  var codepipeline: js.UndefOr[typingsJapgolly.awsSdk.codepipelineMod.apiVersion] = js.native
  var codestar: js.UndefOr[typingsJapgolly.awsSdk.codestarMod.apiVersion] = js.native
  var codestarconnections: js.UndefOr[typingsJapgolly.awsSdk.codestarconnectionsMod.apiVersion] = js.native
  var codestarnotifications: js.UndefOr[typingsJapgolly.awsSdk.codestarnotificationsMod.apiVersion] = js.native
  var cognitoidentity: js.UndefOr[typingsJapgolly.awsSdk.cognitoidentityMod.apiVersion] = js.native
  var cognitoidentityserviceprovider: js.UndefOr[typingsJapgolly.awsSdk.cognitoidentityserviceproviderMod.apiVersion] = js.native
  var cognitosync: js.UndefOr[typingsJapgolly.awsSdk.cognitosyncMod.apiVersion] = js.native
  var comprehend: js.UndefOr[typingsJapgolly.awsSdk.comprehendMod.apiVersion] = js.native
  var comprehendmedical: js.UndefOr[typingsJapgolly.awsSdk.comprehendmedicalMod.apiVersion] = js.native
  var computeoptimizer: js.UndefOr[typingsJapgolly.awsSdk.computeoptimizerMod.apiVersion] = js.native
  var configservice: js.UndefOr[typingsJapgolly.awsSdk.configserviceMod.apiVersion] = js.native
  var connect: js.UndefOr[typingsJapgolly.awsSdk.connectMod.apiVersion] = js.native
  var connectparticipant: js.UndefOr[typingsJapgolly.awsSdk.connectparticipantMod.apiVersion] = js.native
  var costexplorer: js.UndefOr[typingsJapgolly.awsSdk.costexplorerMod.apiVersion] = js.native
  var cur: js.UndefOr[typingsJapgolly.awsSdk.curMod.apiVersion] = js.native
  var dataexchange: js.UndefOr[typingsJapgolly.awsSdk.dataexchangeMod.apiVersion] = js.native
  var datapipeline: js.UndefOr[typingsJapgolly.awsSdk.datapipelineMod.apiVersion] = js.native
  var datasync: js.UndefOr[typingsJapgolly.awsSdk.datasyncMod.apiVersion] = js.native
  var dax: js.UndefOr[typingsJapgolly.awsSdk.daxMod.apiVersion] = js.native
  var detective: js.UndefOr[typingsJapgolly.awsSdk.detectiveMod.apiVersion] = js.native
  var devicefarm: js.UndefOr[typingsJapgolly.awsSdk.devicefarmMod.apiVersion] = js.native
  var directconnect: js.UndefOr[typingsJapgolly.awsSdk.directconnectMod.apiVersion] = js.native
  var directoryservice: js.UndefOr[typingsJapgolly.awsSdk.directoryserviceMod.apiVersion] = js.native
  var discovery: js.UndefOr[typingsJapgolly.awsSdk.discoveryMod.apiVersion] = js.native
  var dlm: js.UndefOr[typingsJapgolly.awsSdk.dlmMod.apiVersion] = js.native
  var dms: js.UndefOr[typingsJapgolly.awsSdk.dmsMod.apiVersion] = js.native
  var docdb: js.UndefOr[typingsJapgolly.awsSdk.docdbMod.apiVersion] = js.native
  var dynamodb: js.UndefOr[typingsJapgolly.awsSdk.dynamodbMod.apiVersion] = js.native
  var dynamodbstreams: js.UndefOr[typingsJapgolly.awsSdk.dynamodbstreamsMod.apiVersion] = js.native
  var ebs: js.UndefOr[typingsJapgolly.awsSdk.ebsMod.apiVersion] = js.native
  var ec2: js.UndefOr[typingsJapgolly.awsSdk.ec2Mod.apiVersion] = js.native
  var ec2instanceconnect: js.UndefOr[typingsJapgolly.awsSdk.ec2instanceconnectMod.apiVersion] = js.native
  var ecr: js.UndefOr[typingsJapgolly.awsSdk.ecrMod.apiVersion] = js.native
  var ecs: js.UndefOr[typingsJapgolly.awsSdk.ecsMod.apiVersion] = js.native
  var efs: js.UndefOr[typingsJapgolly.awsSdk.efsMod.apiVersion] = js.native
  var eks: js.UndefOr[typingsJapgolly.awsSdk.eksMod.apiVersion] = js.native
  var elasticache: js.UndefOr[typingsJapgolly.awsSdk.elasticacheMod.apiVersion] = js.native
  var elasticbeanstalk: js.UndefOr[typingsJapgolly.awsSdk.elasticbeanstalkMod.apiVersion] = js.native
  var elasticinference: js.UndefOr[typingsJapgolly.awsSdk.elasticinferenceMod.apiVersion] = js.native
  var elastictranscoder: js.UndefOr[typingsJapgolly.awsSdk.elastictranscoderMod.apiVersion] = js.native
  var elb: js.UndefOr[typingsJapgolly.awsSdk.elbMod.apiVersion] = js.native
  var elbv2: js.UndefOr[typingsJapgolly.awsSdk.elbv2Mod.apiVersion] = js.native
  var emr: js.UndefOr[typingsJapgolly.awsSdk.emrMod.apiVersion] = js.native
  var es: js.UndefOr[typingsJapgolly.awsSdk.esMod.apiVersion] = js.native
  var eventbridge: js.UndefOr[typingsJapgolly.awsSdk.eventbridgeMod.apiVersion] = js.native
  var firehose: js.UndefOr[typingsJapgolly.awsSdk.firehoseMod.apiVersion] = js.native
  var fms: js.UndefOr[typingsJapgolly.awsSdk.fmsMod.apiVersion] = js.native
  var forecastqueryservice: js.UndefOr[typingsJapgolly.awsSdk.forecastqueryserviceMod.apiVersion] = js.native
  var forecastservice: js.UndefOr[typingsJapgolly.awsSdk.forecastserviceMod.apiVersion] = js.native
  var frauddetector: js.UndefOr[typingsJapgolly.awsSdk.frauddetectorMod.apiVersion] = js.native
  var fsx: js.UndefOr[typingsJapgolly.awsSdk.fsxMod.apiVersion] = js.native
  var gamelift: js.UndefOr[typingsJapgolly.awsSdk.gameliftMod.apiVersion] = js.native
  var glacier: js.UndefOr[typingsJapgolly.awsSdk.glacierMod.apiVersion] = js.native
  var globalaccelerator: js.UndefOr[typingsJapgolly.awsSdk.globalacceleratorMod.apiVersion] = js.native
  var glue: js.UndefOr[typingsJapgolly.awsSdk.glueMod.apiVersion] = js.native
  var greengrass: js.UndefOr[typingsJapgolly.awsSdk.greengrassMod.apiVersion] = js.native
  var groundstation: js.UndefOr[typingsJapgolly.awsSdk.groundstationMod.apiVersion] = js.native
  var guardduty: js.UndefOr[typingsJapgolly.awsSdk.guarddutyMod.apiVersion] = js.native
  var health: js.UndefOr[typingsJapgolly.awsSdk.healthMod.apiVersion] = js.native
  var iam: js.UndefOr[typingsJapgolly.awsSdk.iamMod.apiVersion] = js.native
  var imagebuilder: js.UndefOr[typingsJapgolly.awsSdk.imagebuilderMod.apiVersion] = js.native
  var importexport: js.UndefOr[typingsJapgolly.awsSdk.importexportMod.apiVersion] = js.native
  var inspector: js.UndefOr[typingsJapgolly.awsSdk.inspectorMod.apiVersion] = js.native
  var iot: js.UndefOr[typingsJapgolly.awsSdk.iotMod.apiVersion] = js.native
  var iot1clickdevicesservice: js.UndefOr[typingsJapgolly.awsSdk.iot1clickdevicesserviceMod.apiVersion] = js.native
  var iot1clickprojects: js.UndefOr[typingsJapgolly.awsSdk.iot1clickprojectsMod.apiVersion] = js.native
  var iotanalytics: js.UndefOr[typingsJapgolly.awsSdk.iotanalyticsMod.apiVersion] = js.native
  var iotdata: js.UndefOr[typingsJapgolly.awsSdk.iotdataMod.apiVersion] = js.native
  var iotevents: js.UndefOr[typingsJapgolly.awsSdk.ioteventsMod.apiVersion] = js.native
  var ioteventsdata: js.UndefOr[typingsJapgolly.awsSdk.ioteventsdataMod.apiVersion] = js.native
  var iotjobsdataplane: js.UndefOr[typingsJapgolly.awsSdk.iotjobsdataplaneMod.apiVersion] = js.native
  var iotsecuretunneling: js.UndefOr[typingsJapgolly.awsSdk.iotsecuretunnelingMod.apiVersion] = js.native
  var iotthingsgraph: js.UndefOr[typingsJapgolly.awsSdk.iotthingsgraphMod.apiVersion] = js.native
  var kafka: js.UndefOr[typingsJapgolly.awsSdk.kafkaMod.apiVersion] = js.native
  var kendra: js.UndefOr[typingsJapgolly.awsSdk.kendraMod.apiVersion] = js.native
  var kinesis: js.UndefOr[typingsJapgolly.awsSdk.kinesisMod.apiVersion] = js.native
  var kinesisanalytics: js.UndefOr[typingsJapgolly.awsSdk.kinesisanalyticsMod.apiVersion] = js.native
  var kinesisanalyticsv2: js.UndefOr[typingsJapgolly.awsSdk.kinesisanalyticsv2Mod.apiVersion] = js.native
  var kinesisvideo: js.UndefOr[typingsJapgolly.awsSdk.kinesisvideoMod.apiVersion] = js.native
  var kinesisvideoarchivedmedia: js.UndefOr[typingsJapgolly.awsSdk.kinesisvideoarchivedmediaMod.apiVersion] = js.native
  var kinesisvideomedia: js.UndefOr[typingsJapgolly.awsSdk.kinesisvideomediaMod.apiVersion] = js.native
  var kinesisvideosignalingchannels: js.UndefOr[typingsJapgolly.awsSdk.kinesisvideosignalingchannelsMod.apiVersion] = js.native
  var kms: js.UndefOr[typingsJapgolly.awsSdk.kmsMod.apiVersion] = js.native
  var lakeformation: js.UndefOr[typingsJapgolly.awsSdk.lakeformationMod.apiVersion] = js.native
  var lambda: js.UndefOr[typingsJapgolly.awsSdk.lambdaMod.apiVersion] = js.native
  var lexmodelbuildingservice: js.UndefOr[typingsJapgolly.awsSdk.lexmodelbuildingserviceMod.apiVersion] = js.native
  var lexruntime: js.UndefOr[typingsJapgolly.awsSdk.lexruntimeMod.apiVersion] = js.native
  var licensemanager: js.UndefOr[typingsJapgolly.awsSdk.licensemanagerMod.apiVersion] = js.native
  var lightsail: js.UndefOr[typingsJapgolly.awsSdk.lightsailMod.apiVersion] = js.native
  var machinelearning: js.UndefOr[typingsJapgolly.awsSdk.machinelearningMod.apiVersion] = js.native
  var macie: js.UndefOr[typingsJapgolly.awsSdk.macieMod.apiVersion] = js.native
  var managedblockchain: js.UndefOr[typingsJapgolly.awsSdk.managedblockchainMod.apiVersion] = js.native
  var marketplacecatalog: js.UndefOr[typingsJapgolly.awsSdk.marketplacecatalogMod.apiVersion] = js.native
  var marketplacecommerceanalytics: js.UndefOr[typingsJapgolly.awsSdk.marketplacecommerceanalyticsMod.apiVersion] = js.native
  var marketplaceentitlementservice: js.UndefOr[typingsJapgolly.awsSdk.marketplaceentitlementserviceMod.apiVersion] = js.native
  var marketplacemetering: js.UndefOr[typingsJapgolly.awsSdk.marketplacemeteringMod.apiVersion] = js.native
  var mediaconnect: js.UndefOr[typingsJapgolly.awsSdk.mediaconnectMod.apiVersion] = js.native
  var mediaconvert: js.UndefOr[typingsJapgolly.awsSdk.mediaconvertMod.apiVersion] = js.native
  var medialive: js.UndefOr[typingsJapgolly.awsSdk.medialiveMod.apiVersion] = js.native
  var mediapackage: js.UndefOr[typingsJapgolly.awsSdk.mediapackageMod.apiVersion] = js.native
  var mediapackagevod: js.UndefOr[typingsJapgolly.awsSdk.mediapackagevodMod.apiVersion] = js.native
  var mediastore: js.UndefOr[typingsJapgolly.awsSdk.mediastoreMod.apiVersion] = js.native
  var mediastoredata: js.UndefOr[typingsJapgolly.awsSdk.mediastoredataMod.apiVersion] = js.native
  var mediatailor: js.UndefOr[typingsJapgolly.awsSdk.mediatailorMod.apiVersion] = js.native
  var migrationhub: js.UndefOr[typingsJapgolly.awsSdk.migrationhubMod.apiVersion] = js.native
  var migrationhubconfig: js.UndefOr[typingsJapgolly.awsSdk.migrationhubconfigMod.apiVersion] = js.native
  var mobile: js.UndefOr[typingsJapgolly.awsSdk.mobileMod.apiVersion] = js.native
  var mobileanalytics: js.UndefOr[typingsJapgolly.awsSdk.mobileanalyticsMod.apiVersion] = js.native
  var mq: js.UndefOr[typingsJapgolly.awsSdk.mqMod.apiVersion] = js.native
  var mturk: js.UndefOr[typingsJapgolly.awsSdk.mturkMod.apiVersion] = js.native
  var neptune: js.UndefOr[typingsJapgolly.awsSdk.neptuneMod.apiVersion] = js.native
  var networkmanager: js.UndefOr[typingsJapgolly.awsSdk.networkmanagerMod.apiVersion] = js.native
  var opsworks: js.UndefOr[typingsJapgolly.awsSdk.opsworksMod.apiVersion] = js.native
  var opsworkscm: js.UndefOr[typingsJapgolly.awsSdk.opsworkscmMod.apiVersion] = js.native
  var organizations: js.UndefOr[typingsJapgolly.awsSdk.organizationsMod.apiVersion] = js.native
  var outposts: js.UndefOr[typingsJapgolly.awsSdk.outpostsMod.apiVersion] = js.native
  var personalize: js.UndefOr[typingsJapgolly.awsSdk.personalizeMod.apiVersion] = js.native
  var personalizeevents: js.UndefOr[typingsJapgolly.awsSdk.personalizeeventsMod.apiVersion] = js.native
  var personalizeruntime: js.UndefOr[typingsJapgolly.awsSdk.personalizeruntimeMod.apiVersion] = js.native
  var pi: js.UndefOr[typingsJapgolly.awsSdk.piMod.apiVersion] = js.native
  var pinpoint: js.UndefOr[typingsJapgolly.awsSdk.pinpointMod.apiVersion] = js.native
  var pinpointemail: js.UndefOr[typingsJapgolly.awsSdk.pinpointemailMod.apiVersion] = js.native
  var pinpointsmsvoice: js.UndefOr[typingsJapgolly.awsSdk.pinpointsmsvoiceMod.apiVersion] = js.native
  var polly: js.UndefOr[typingsJapgolly.awsSdk.pollyMod.apiVersion] = js.native
  var pricing: js.UndefOr[typingsJapgolly.awsSdk.pricingMod.apiVersion] = js.native
  var qldb: js.UndefOr[typingsJapgolly.awsSdk.qldbMod.apiVersion] = js.native
  var qldbsession: js.UndefOr[typingsJapgolly.awsSdk.qldbsessionMod.apiVersion] = js.native
  var quicksight: js.UndefOr[typingsJapgolly.awsSdk.quicksightMod.apiVersion] = js.native
  var ram: js.UndefOr[typingsJapgolly.awsSdk.ramMod.apiVersion] = js.native
  var rds: js.UndefOr[typingsJapgolly.awsSdk.rdsMod.apiVersion] = js.native
  var rdsdataservice: js.UndefOr[typingsJapgolly.awsSdk.rdsdataserviceMod.apiVersion] = js.native
  var redshift: js.UndefOr[typingsJapgolly.awsSdk.redshiftMod.apiVersion] = js.native
  var rekognition: js.UndefOr[typingsJapgolly.awsSdk.rekognitionMod.apiVersion] = js.native
  var resourcegroups: js.UndefOr[typingsJapgolly.awsSdk.resourcegroupsMod.apiVersion] = js.native
  var resourcegroupstaggingapi: js.UndefOr[typingsJapgolly.awsSdk.resourcegroupstaggingapiMod.apiVersion] = js.native
  var robomaker: js.UndefOr[typingsJapgolly.awsSdk.robomakerMod.apiVersion] = js.native
  var route53: js.UndefOr[typingsJapgolly.awsSdk.route53Mod.apiVersion] = js.native
  var route53domains: js.UndefOr[typingsJapgolly.awsSdk.route53domainsMod.apiVersion] = js.native
  var route53resolver: js.UndefOr[typingsJapgolly.awsSdk.route53resolverMod.apiVersion] = js.native
  var s3: js.UndefOr[typingsJapgolly.awsSdk.s3Mod.apiVersion] = js.native
  var s3control: js.UndefOr[typingsJapgolly.awsSdk.s3controlMod.apiVersion] = js.native
  var sagemaker: js.UndefOr[typingsJapgolly.awsSdk.sagemakerMod.apiVersion] = js.native
  var sagemakerruntime: js.UndefOr[typingsJapgolly.awsSdk.sagemakerruntimeMod.apiVersion] = js.native
  var savingsplans: js.UndefOr[typingsJapgolly.awsSdk.savingsplansMod.apiVersion] = js.native
  var schemas: js.UndefOr[typingsJapgolly.awsSdk.schemasMod.apiVersion] = js.native
  var secretsmanager: js.UndefOr[typingsJapgolly.awsSdk.secretsmanagerMod.apiVersion] = js.native
  var securityhub: js.UndefOr[typingsJapgolly.awsSdk.securityhubMod.apiVersion] = js.native
  var serverlessapplicationrepository: js.UndefOr[typingsJapgolly.awsSdk.serverlessapplicationrepositoryMod.apiVersion] = js.native
  var servicecatalog: js.UndefOr[typingsJapgolly.awsSdk.servicecatalogMod.apiVersion] = js.native
  var servicediscovery: js.UndefOr[typingsJapgolly.awsSdk.servicediscoveryMod.apiVersion] = js.native
  var servicequotas: js.UndefOr[typingsJapgolly.awsSdk.servicequotasMod.apiVersion] = js.native
  var ses: js.UndefOr[typingsJapgolly.awsSdk.sesMod.apiVersion] = js.native
  var sesv2: js.UndefOr[typingsJapgolly.awsSdk.sesv2Mod.apiVersion] = js.native
  var shield: js.UndefOr[typingsJapgolly.awsSdk.shieldMod.apiVersion] = js.native
  var signer: js.UndefOr[typingsJapgolly.awsSdk.signerMod.apiVersion] = js.native
  var simpledb: js.UndefOr[typingsJapgolly.awsSdk.simpledbMod.apiVersion] = js.native
  var sms: js.UndefOr[typingsJapgolly.awsSdk.smsMod.apiVersion] = js.native
  var snowball: js.UndefOr[typingsJapgolly.awsSdk.snowballMod.apiVersion] = js.native
  var sns: js.UndefOr[typingsJapgolly.awsSdk.snsMod.apiVersion] = js.native
  var sqs: js.UndefOr[typingsJapgolly.awsSdk.sqsMod.apiVersion] = js.native
  var ssm: js.UndefOr[typingsJapgolly.awsSdk.ssmMod.apiVersion] = js.native
  var sso: js.UndefOr[typingsJapgolly.awsSdk.ssoMod.apiVersion] = js.native
  var ssooidc: js.UndefOr[typingsJapgolly.awsSdk.ssooidcMod.apiVersion] = js.native
  var stepfunctions: js.UndefOr[typingsJapgolly.awsSdk.stepfunctionsMod.apiVersion] = js.native
  var storagegateway: js.UndefOr[typingsJapgolly.awsSdk.storagegatewayMod.apiVersion] = js.native
  var sts: js.UndefOr[typingsJapgolly.awsSdk.stsMod.apiVersion] = js.native
  var support: js.UndefOr[typingsJapgolly.awsSdk.supportMod.apiVersion] = js.native
  var swf: js.UndefOr[typingsJapgolly.awsSdk.swfMod.apiVersion] = js.native
  var textract: js.UndefOr[typingsJapgolly.awsSdk.textractMod.apiVersion] = js.native
  var transcribeservice: js.UndefOr[typingsJapgolly.awsSdk.transcribeserviceMod.apiVersion] = js.native
  var transfer: js.UndefOr[typingsJapgolly.awsSdk.transferMod.apiVersion] = js.native
  var translate: js.UndefOr[typingsJapgolly.awsSdk.translateMod.apiVersion] = js.native
  var waf: js.UndefOr[typingsJapgolly.awsSdk.wafMod.apiVersion] = js.native
  var wafregional: js.UndefOr[typingsJapgolly.awsSdk.wafregionalMod.apiVersion] = js.native
  var wafv2: js.UndefOr[typingsJapgolly.awsSdk.wafv2Mod.apiVersion] = js.native
  var workdocs: js.UndefOr[typingsJapgolly.awsSdk.workdocsMod.apiVersion] = js.native
  var worklink: js.UndefOr[typingsJapgolly.awsSdk.worklinkMod.apiVersion] = js.native
  var workmail: js.UndefOr[typingsJapgolly.awsSdk.workmailMod.apiVersion] = js.native
  var workmailmessageflow: js.UndefOr[typingsJapgolly.awsSdk.workmailmessageflowMod.apiVersion] = js.native
  var workspaces: js.UndefOr[typingsJapgolly.awsSdk.workspacesMod.apiVersion] = js.native
  var xray: js.UndefOr[typingsJapgolly.awsSdk.xrayMod.apiVersion] = js.native
}

object ConfigurationServiceApiVersions {
  @scala.inline
  def apply(
    accessanalyzer: apiVersion = null,
    acm: typingsJapgolly.awsSdk.acmMod.apiVersion = null,
    acmpca: typingsJapgolly.awsSdk.acmpcaMod.apiVersion = null,
    alexaforbusiness: typingsJapgolly.awsSdk.alexaforbusinessMod.apiVersion = null,
    amplify: typingsJapgolly.awsSdk.amplifyMod.apiVersion = null,
    apigateway: typingsJapgolly.awsSdk.apigatewayMod.apiVersion = null,
    apigatewaymanagementapi: typingsJapgolly.awsSdk.apigatewaymanagementapiMod.apiVersion = null,
    apigatewayv2: typingsJapgolly.awsSdk.apigatewayv2Mod.apiVersion = null,
    appconfig: typingsJapgolly.awsSdk.appconfigMod.apiVersion = null,
    applicationautoscaling: typingsJapgolly.awsSdk.applicationautoscalingMod.apiVersion = null,
    applicationinsights: typingsJapgolly.awsSdk.applicationinsightsMod.apiVersion = null,
    appmesh: typingsJapgolly.awsSdk.appmeshMod.apiVersion = null,
    appstream: typingsJapgolly.awsSdk.appstreamMod.apiVersion = null,
    appsync: typingsJapgolly.awsSdk.appsyncMod.apiVersion = null,
    athena: typingsJapgolly.awsSdk.athenaMod.apiVersion = null,
    augmentedairuntime: typingsJapgolly.awsSdk.augmentedairuntimeMod.apiVersion = null,
    autoscaling: typingsJapgolly.awsSdk.autoscalingMod.apiVersion = null,
    autoscalingplans: typingsJapgolly.awsSdk.autoscalingplansMod.apiVersion = null,
    backup: typingsJapgolly.awsSdk.backupMod.apiVersion = null,
    batch: typingsJapgolly.awsSdk.batchMod.apiVersion = null,
    budgets: typingsJapgolly.awsSdk.budgetsMod.apiVersion = null,
    chime: typingsJapgolly.awsSdk.chimeMod.apiVersion = null,
    cloud9: typingsJapgolly.awsSdk.cloud9Mod.apiVersion = null,
    clouddirectory: typingsJapgolly.awsSdk.clouddirectoryMod.apiVersion = null,
    cloudformation: typingsJapgolly.awsSdk.cloudformationMod.apiVersion = null,
    cloudfront: typingsJapgolly.awsSdk.cloudfrontMod.apiVersion = null,
    cloudhsm: typingsJapgolly.awsSdk.cloudhsmMod.apiVersion = null,
    cloudhsmv2: typingsJapgolly.awsSdk.cloudhsmv2Mod.apiVersion = null,
    cloudsearch: typingsJapgolly.awsSdk.cloudsearchMod.apiVersion = null,
    cloudsearchdomain: typingsJapgolly.awsSdk.cloudsearchdomainMod.apiVersion = null,
    cloudtrail: typingsJapgolly.awsSdk.cloudtrailMod.apiVersion = null,
    cloudwatch: typingsJapgolly.awsSdk.cloudwatchMod.apiVersion = null,
    cloudwatchevents: typingsJapgolly.awsSdk.cloudwatcheventsMod.apiVersion = null,
    cloudwatchlogs: typingsJapgolly.awsSdk.cloudwatchlogsMod.apiVersion = null,
    codebuild: typingsJapgolly.awsSdk.codebuildMod.apiVersion = null,
    codecommit: typingsJapgolly.awsSdk.codecommitMod.apiVersion = null,
    codedeploy: typingsJapgolly.awsSdk.codedeployMod.apiVersion = null,
    codeguruprofiler: typingsJapgolly.awsSdk.codeguruprofilerMod.apiVersion = null,
    codegurureviewer: typingsJapgolly.awsSdk.codegurureviewerMod.apiVersion = null,
    codepipeline: typingsJapgolly.awsSdk.codepipelineMod.apiVersion = null,
    codestar: typingsJapgolly.awsSdk.codestarMod.apiVersion = null,
    codestarconnections: typingsJapgolly.awsSdk.codestarconnectionsMod.apiVersion = null,
    codestarnotifications: typingsJapgolly.awsSdk.codestarnotificationsMod.apiVersion = null,
    cognitoidentity: typingsJapgolly.awsSdk.cognitoidentityMod.apiVersion = null,
    cognitoidentityserviceprovider: typingsJapgolly.awsSdk.cognitoidentityserviceproviderMod.apiVersion = null,
    cognitosync: typingsJapgolly.awsSdk.cognitosyncMod.apiVersion = null,
    comprehend: typingsJapgolly.awsSdk.comprehendMod.apiVersion = null,
    comprehendmedical: typingsJapgolly.awsSdk.comprehendmedicalMod.apiVersion = null,
    computeoptimizer: typingsJapgolly.awsSdk.computeoptimizerMod.apiVersion = null,
    configservice: typingsJapgolly.awsSdk.configserviceMod.apiVersion = null,
    connect: typingsJapgolly.awsSdk.connectMod.apiVersion = null,
    connectparticipant: typingsJapgolly.awsSdk.connectparticipantMod.apiVersion = null,
    costexplorer: typingsJapgolly.awsSdk.costexplorerMod.apiVersion = null,
    cur: typingsJapgolly.awsSdk.curMod.apiVersion = null,
    dataexchange: typingsJapgolly.awsSdk.dataexchangeMod.apiVersion = null,
    datapipeline: typingsJapgolly.awsSdk.datapipelineMod.apiVersion = null,
    datasync: typingsJapgolly.awsSdk.datasyncMod.apiVersion = null,
    dax: typingsJapgolly.awsSdk.daxMod.apiVersion = null,
    detective: typingsJapgolly.awsSdk.detectiveMod.apiVersion = null,
    devicefarm: typingsJapgolly.awsSdk.devicefarmMod.apiVersion = null,
    directconnect: typingsJapgolly.awsSdk.directconnectMod.apiVersion = null,
    directoryservice: typingsJapgolly.awsSdk.directoryserviceMod.apiVersion = null,
    discovery: typingsJapgolly.awsSdk.discoveryMod.apiVersion = null,
    dlm: typingsJapgolly.awsSdk.dlmMod.apiVersion = null,
    dms: typingsJapgolly.awsSdk.dmsMod.apiVersion = null,
    docdb: typingsJapgolly.awsSdk.docdbMod.apiVersion = null,
    dynamodb: typingsJapgolly.awsSdk.dynamodbMod.apiVersion = null,
    dynamodbstreams: typingsJapgolly.awsSdk.dynamodbstreamsMod.apiVersion = null,
    ebs: typingsJapgolly.awsSdk.ebsMod.apiVersion = null,
    ec2: typingsJapgolly.awsSdk.ec2Mod.apiVersion = null,
    ec2instanceconnect: typingsJapgolly.awsSdk.ec2instanceconnectMod.apiVersion = null,
    ecr: typingsJapgolly.awsSdk.ecrMod.apiVersion = null,
    ecs: typingsJapgolly.awsSdk.ecsMod.apiVersion = null,
    efs: typingsJapgolly.awsSdk.efsMod.apiVersion = null,
    eks: typingsJapgolly.awsSdk.eksMod.apiVersion = null,
    elasticache: typingsJapgolly.awsSdk.elasticacheMod.apiVersion = null,
    elasticbeanstalk: typingsJapgolly.awsSdk.elasticbeanstalkMod.apiVersion = null,
    elasticinference: typingsJapgolly.awsSdk.elasticinferenceMod.apiVersion = null,
    elastictranscoder: typingsJapgolly.awsSdk.elastictranscoderMod.apiVersion = null,
    elb: typingsJapgolly.awsSdk.elbMod.apiVersion = null,
    elbv2: typingsJapgolly.awsSdk.elbv2Mod.apiVersion = null,
    emr: typingsJapgolly.awsSdk.emrMod.apiVersion = null,
    es: typingsJapgolly.awsSdk.esMod.apiVersion = null,
    eventbridge: typingsJapgolly.awsSdk.eventbridgeMod.apiVersion = null,
    firehose: typingsJapgolly.awsSdk.firehoseMod.apiVersion = null,
    fms: typingsJapgolly.awsSdk.fmsMod.apiVersion = null,
    forecastqueryservice: typingsJapgolly.awsSdk.forecastqueryserviceMod.apiVersion = null,
    forecastservice: typingsJapgolly.awsSdk.forecastserviceMod.apiVersion = null,
    frauddetector: typingsJapgolly.awsSdk.frauddetectorMod.apiVersion = null,
    fsx: typingsJapgolly.awsSdk.fsxMod.apiVersion = null,
    gamelift: typingsJapgolly.awsSdk.gameliftMod.apiVersion = null,
    glacier: typingsJapgolly.awsSdk.glacierMod.apiVersion = null,
    globalaccelerator: typingsJapgolly.awsSdk.globalacceleratorMod.apiVersion = null,
    glue: typingsJapgolly.awsSdk.glueMod.apiVersion = null,
    greengrass: typingsJapgolly.awsSdk.greengrassMod.apiVersion = null,
    groundstation: typingsJapgolly.awsSdk.groundstationMod.apiVersion = null,
    guardduty: typingsJapgolly.awsSdk.guarddutyMod.apiVersion = null,
    health: typingsJapgolly.awsSdk.healthMod.apiVersion = null,
    iam: typingsJapgolly.awsSdk.iamMod.apiVersion = null,
    imagebuilder: typingsJapgolly.awsSdk.imagebuilderMod.apiVersion = null,
    importexport: typingsJapgolly.awsSdk.importexportMod.apiVersion = null,
    inspector: typingsJapgolly.awsSdk.inspectorMod.apiVersion = null,
    iot: typingsJapgolly.awsSdk.iotMod.apiVersion = null,
    iot1clickdevicesservice: typingsJapgolly.awsSdk.iot1clickdevicesserviceMod.apiVersion = null,
    iot1clickprojects: typingsJapgolly.awsSdk.iot1clickprojectsMod.apiVersion = null,
    iotanalytics: typingsJapgolly.awsSdk.iotanalyticsMod.apiVersion = null,
    iotdata: typingsJapgolly.awsSdk.iotdataMod.apiVersion = null,
    iotevents: typingsJapgolly.awsSdk.ioteventsMod.apiVersion = null,
    ioteventsdata: typingsJapgolly.awsSdk.ioteventsdataMod.apiVersion = null,
    iotjobsdataplane: typingsJapgolly.awsSdk.iotjobsdataplaneMod.apiVersion = null,
    iotsecuretunneling: typingsJapgolly.awsSdk.iotsecuretunnelingMod.apiVersion = null,
    iotthingsgraph: typingsJapgolly.awsSdk.iotthingsgraphMod.apiVersion = null,
    kafka: typingsJapgolly.awsSdk.kafkaMod.apiVersion = null,
    kendra: typingsJapgolly.awsSdk.kendraMod.apiVersion = null,
    kinesis: typingsJapgolly.awsSdk.kinesisMod.apiVersion = null,
    kinesisanalytics: typingsJapgolly.awsSdk.kinesisanalyticsMod.apiVersion = null,
    kinesisanalyticsv2: typingsJapgolly.awsSdk.kinesisanalyticsv2Mod.apiVersion = null,
    kinesisvideo: typingsJapgolly.awsSdk.kinesisvideoMod.apiVersion = null,
    kinesisvideoarchivedmedia: typingsJapgolly.awsSdk.kinesisvideoarchivedmediaMod.apiVersion = null,
    kinesisvideomedia: typingsJapgolly.awsSdk.kinesisvideomediaMod.apiVersion = null,
    kinesisvideosignalingchannels: typingsJapgolly.awsSdk.kinesisvideosignalingchannelsMod.apiVersion = null,
    kms: typingsJapgolly.awsSdk.kmsMod.apiVersion = null,
    lakeformation: typingsJapgolly.awsSdk.lakeformationMod.apiVersion = null,
    lambda: typingsJapgolly.awsSdk.lambdaMod.apiVersion = null,
    lexmodelbuildingservice: typingsJapgolly.awsSdk.lexmodelbuildingserviceMod.apiVersion = null,
    lexruntime: typingsJapgolly.awsSdk.lexruntimeMod.apiVersion = null,
    licensemanager: typingsJapgolly.awsSdk.licensemanagerMod.apiVersion = null,
    lightsail: typingsJapgolly.awsSdk.lightsailMod.apiVersion = null,
    machinelearning: typingsJapgolly.awsSdk.machinelearningMod.apiVersion = null,
    macie: typingsJapgolly.awsSdk.macieMod.apiVersion = null,
    managedblockchain: typingsJapgolly.awsSdk.managedblockchainMod.apiVersion = null,
    marketplacecatalog: typingsJapgolly.awsSdk.marketplacecatalogMod.apiVersion = null,
    marketplacecommerceanalytics: typingsJapgolly.awsSdk.marketplacecommerceanalyticsMod.apiVersion = null,
    marketplaceentitlementservice: typingsJapgolly.awsSdk.marketplaceentitlementserviceMod.apiVersion = null,
    marketplacemetering: typingsJapgolly.awsSdk.marketplacemeteringMod.apiVersion = null,
    mediaconnect: typingsJapgolly.awsSdk.mediaconnectMod.apiVersion = null,
    mediaconvert: typingsJapgolly.awsSdk.mediaconvertMod.apiVersion = null,
    medialive: typingsJapgolly.awsSdk.medialiveMod.apiVersion = null,
    mediapackage: typingsJapgolly.awsSdk.mediapackageMod.apiVersion = null,
    mediapackagevod: typingsJapgolly.awsSdk.mediapackagevodMod.apiVersion = null,
    mediastore: typingsJapgolly.awsSdk.mediastoreMod.apiVersion = null,
    mediastoredata: typingsJapgolly.awsSdk.mediastoredataMod.apiVersion = null,
    mediatailor: typingsJapgolly.awsSdk.mediatailorMod.apiVersion = null,
    migrationhub: typingsJapgolly.awsSdk.migrationhubMod.apiVersion = null,
    migrationhubconfig: typingsJapgolly.awsSdk.migrationhubconfigMod.apiVersion = null,
    mobile: typingsJapgolly.awsSdk.mobileMod.apiVersion = null,
    mobileanalytics: typingsJapgolly.awsSdk.mobileanalyticsMod.apiVersion = null,
    mq: typingsJapgolly.awsSdk.mqMod.apiVersion = null,
    mturk: typingsJapgolly.awsSdk.mturkMod.apiVersion = null,
    neptune: typingsJapgolly.awsSdk.neptuneMod.apiVersion = null,
    networkmanager: typingsJapgolly.awsSdk.networkmanagerMod.apiVersion = null,
    opsworks: typingsJapgolly.awsSdk.opsworksMod.apiVersion = null,
    opsworkscm: typingsJapgolly.awsSdk.opsworkscmMod.apiVersion = null,
    organizations: typingsJapgolly.awsSdk.organizationsMod.apiVersion = null,
    outposts: typingsJapgolly.awsSdk.outpostsMod.apiVersion = null,
    personalize: typingsJapgolly.awsSdk.personalizeMod.apiVersion = null,
    personalizeevents: typingsJapgolly.awsSdk.personalizeeventsMod.apiVersion = null,
    personalizeruntime: typingsJapgolly.awsSdk.personalizeruntimeMod.apiVersion = null,
    pi: typingsJapgolly.awsSdk.piMod.apiVersion = null,
    pinpoint: typingsJapgolly.awsSdk.pinpointMod.apiVersion = null,
    pinpointemail: typingsJapgolly.awsSdk.pinpointemailMod.apiVersion = null,
    pinpointsmsvoice: typingsJapgolly.awsSdk.pinpointsmsvoiceMod.apiVersion = null,
    polly: typingsJapgolly.awsSdk.pollyMod.apiVersion = null,
    pricing: typingsJapgolly.awsSdk.pricingMod.apiVersion = null,
    qldb: typingsJapgolly.awsSdk.qldbMod.apiVersion = null,
    qldbsession: typingsJapgolly.awsSdk.qldbsessionMod.apiVersion = null,
    quicksight: typingsJapgolly.awsSdk.quicksightMod.apiVersion = null,
    ram: typingsJapgolly.awsSdk.ramMod.apiVersion = null,
    rds: typingsJapgolly.awsSdk.rdsMod.apiVersion = null,
    rdsdataservice: typingsJapgolly.awsSdk.rdsdataserviceMod.apiVersion = null,
    redshift: typingsJapgolly.awsSdk.redshiftMod.apiVersion = null,
    rekognition: typingsJapgolly.awsSdk.rekognitionMod.apiVersion = null,
    resourcegroups: typingsJapgolly.awsSdk.resourcegroupsMod.apiVersion = null,
    resourcegroupstaggingapi: typingsJapgolly.awsSdk.resourcegroupstaggingapiMod.apiVersion = null,
    robomaker: typingsJapgolly.awsSdk.robomakerMod.apiVersion = null,
    route53: typingsJapgolly.awsSdk.route53Mod.apiVersion = null,
    route53domains: typingsJapgolly.awsSdk.route53domainsMod.apiVersion = null,
    route53resolver: typingsJapgolly.awsSdk.route53resolverMod.apiVersion = null,
    s3: typingsJapgolly.awsSdk.s3Mod.apiVersion = null,
    s3control: typingsJapgolly.awsSdk.s3controlMod.apiVersion = null,
    sagemaker: typingsJapgolly.awsSdk.sagemakerMod.apiVersion = null,
    sagemakerruntime: typingsJapgolly.awsSdk.sagemakerruntimeMod.apiVersion = null,
    savingsplans: typingsJapgolly.awsSdk.savingsplansMod.apiVersion = null,
    schemas: typingsJapgolly.awsSdk.schemasMod.apiVersion = null,
    secretsmanager: typingsJapgolly.awsSdk.secretsmanagerMod.apiVersion = null,
    securityhub: typingsJapgolly.awsSdk.securityhubMod.apiVersion = null,
    serverlessapplicationrepository: typingsJapgolly.awsSdk.serverlessapplicationrepositoryMod.apiVersion = null,
    servicecatalog: typingsJapgolly.awsSdk.servicecatalogMod.apiVersion = null,
    servicediscovery: typingsJapgolly.awsSdk.servicediscoveryMod.apiVersion = null,
    servicequotas: typingsJapgolly.awsSdk.servicequotasMod.apiVersion = null,
    ses: typingsJapgolly.awsSdk.sesMod.apiVersion = null,
    sesv2: typingsJapgolly.awsSdk.sesv2Mod.apiVersion = null,
    shield: typingsJapgolly.awsSdk.shieldMod.apiVersion = null,
    signer: typingsJapgolly.awsSdk.signerMod.apiVersion = null,
    simpledb: typingsJapgolly.awsSdk.simpledbMod.apiVersion = null,
    sms: typingsJapgolly.awsSdk.smsMod.apiVersion = null,
    snowball: typingsJapgolly.awsSdk.snowballMod.apiVersion = null,
    sns: typingsJapgolly.awsSdk.snsMod.apiVersion = null,
    sqs: typingsJapgolly.awsSdk.sqsMod.apiVersion = null,
    ssm: typingsJapgolly.awsSdk.ssmMod.apiVersion = null,
    sso: typingsJapgolly.awsSdk.ssoMod.apiVersion = null,
    ssooidc: typingsJapgolly.awsSdk.ssooidcMod.apiVersion = null,
    stepfunctions: typingsJapgolly.awsSdk.stepfunctionsMod.apiVersion = null,
    storagegateway: typingsJapgolly.awsSdk.storagegatewayMod.apiVersion = null,
    sts: typingsJapgolly.awsSdk.stsMod.apiVersion = null,
    support: typingsJapgolly.awsSdk.supportMod.apiVersion = null,
    swf: typingsJapgolly.awsSdk.swfMod.apiVersion = null,
    textract: typingsJapgolly.awsSdk.textractMod.apiVersion = null,
    transcribeservice: typingsJapgolly.awsSdk.transcribeserviceMod.apiVersion = null,
    transfer: typingsJapgolly.awsSdk.transferMod.apiVersion = null,
    translate: typingsJapgolly.awsSdk.translateMod.apiVersion = null,
    waf: typingsJapgolly.awsSdk.wafMod.apiVersion = null,
    wafregional: typingsJapgolly.awsSdk.wafregionalMod.apiVersion = null,
    wafv2: typingsJapgolly.awsSdk.wafv2Mod.apiVersion = null,
    workdocs: typingsJapgolly.awsSdk.workdocsMod.apiVersion = null,
    worklink: typingsJapgolly.awsSdk.worklinkMod.apiVersion = null,
    workmail: typingsJapgolly.awsSdk.workmailMod.apiVersion = null,
    workmailmessageflow: typingsJapgolly.awsSdk.workmailmessageflowMod.apiVersion = null,
    workspaces: typingsJapgolly.awsSdk.workspacesMod.apiVersion = null,
    xray: typingsJapgolly.awsSdk.xrayMod.apiVersion = null
  ): ConfigurationServiceApiVersions = {
    val __obj = js.Dynamic.literal()
    if (accessanalyzer != null) __obj.updateDynamic("accessanalyzer")(accessanalyzer.asInstanceOf[js.Any])
    if (acm != null) __obj.updateDynamic("acm")(acm.asInstanceOf[js.Any])
    if (acmpca != null) __obj.updateDynamic("acmpca")(acmpca.asInstanceOf[js.Any])
    if (alexaforbusiness != null) __obj.updateDynamic("alexaforbusiness")(alexaforbusiness.asInstanceOf[js.Any])
    if (amplify != null) __obj.updateDynamic("amplify")(amplify.asInstanceOf[js.Any])
    if (apigateway != null) __obj.updateDynamic("apigateway")(apigateway.asInstanceOf[js.Any])
    if (apigatewaymanagementapi != null) __obj.updateDynamic("apigatewaymanagementapi")(apigatewaymanagementapi.asInstanceOf[js.Any])
    if (apigatewayv2 != null) __obj.updateDynamic("apigatewayv2")(apigatewayv2.asInstanceOf[js.Any])
    if (appconfig != null) __obj.updateDynamic("appconfig")(appconfig.asInstanceOf[js.Any])
    if (applicationautoscaling != null) __obj.updateDynamic("applicationautoscaling")(applicationautoscaling.asInstanceOf[js.Any])
    if (applicationinsights != null) __obj.updateDynamic("applicationinsights")(applicationinsights.asInstanceOf[js.Any])
    if (appmesh != null) __obj.updateDynamic("appmesh")(appmesh.asInstanceOf[js.Any])
    if (appstream != null) __obj.updateDynamic("appstream")(appstream.asInstanceOf[js.Any])
    if (appsync != null) __obj.updateDynamic("appsync")(appsync.asInstanceOf[js.Any])
    if (athena != null) __obj.updateDynamic("athena")(athena.asInstanceOf[js.Any])
    if (augmentedairuntime != null) __obj.updateDynamic("augmentedairuntime")(augmentedairuntime.asInstanceOf[js.Any])
    if (autoscaling != null) __obj.updateDynamic("autoscaling")(autoscaling.asInstanceOf[js.Any])
    if (autoscalingplans != null) __obj.updateDynamic("autoscalingplans")(autoscalingplans.asInstanceOf[js.Any])
    if (backup != null) __obj.updateDynamic("backup")(backup.asInstanceOf[js.Any])
    if (batch != null) __obj.updateDynamic("batch")(batch.asInstanceOf[js.Any])
    if (budgets != null) __obj.updateDynamic("budgets")(budgets.asInstanceOf[js.Any])
    if (chime != null) __obj.updateDynamic("chime")(chime.asInstanceOf[js.Any])
    if (cloud9 != null) __obj.updateDynamic("cloud9")(cloud9.asInstanceOf[js.Any])
    if (clouddirectory != null) __obj.updateDynamic("clouddirectory")(clouddirectory.asInstanceOf[js.Any])
    if (cloudformation != null) __obj.updateDynamic("cloudformation")(cloudformation.asInstanceOf[js.Any])
    if (cloudfront != null) __obj.updateDynamic("cloudfront")(cloudfront.asInstanceOf[js.Any])
    if (cloudhsm != null) __obj.updateDynamic("cloudhsm")(cloudhsm.asInstanceOf[js.Any])
    if (cloudhsmv2 != null) __obj.updateDynamic("cloudhsmv2")(cloudhsmv2.asInstanceOf[js.Any])
    if (cloudsearch != null) __obj.updateDynamic("cloudsearch")(cloudsearch.asInstanceOf[js.Any])
    if (cloudsearchdomain != null) __obj.updateDynamic("cloudsearchdomain")(cloudsearchdomain.asInstanceOf[js.Any])
    if (cloudtrail != null) __obj.updateDynamic("cloudtrail")(cloudtrail.asInstanceOf[js.Any])
    if (cloudwatch != null) __obj.updateDynamic("cloudwatch")(cloudwatch.asInstanceOf[js.Any])
    if (cloudwatchevents != null) __obj.updateDynamic("cloudwatchevents")(cloudwatchevents.asInstanceOf[js.Any])
    if (cloudwatchlogs != null) __obj.updateDynamic("cloudwatchlogs")(cloudwatchlogs.asInstanceOf[js.Any])
    if (codebuild != null) __obj.updateDynamic("codebuild")(codebuild.asInstanceOf[js.Any])
    if (codecommit != null) __obj.updateDynamic("codecommit")(codecommit.asInstanceOf[js.Any])
    if (codedeploy != null) __obj.updateDynamic("codedeploy")(codedeploy.asInstanceOf[js.Any])
    if (codeguruprofiler != null) __obj.updateDynamic("codeguruprofiler")(codeguruprofiler.asInstanceOf[js.Any])
    if (codegurureviewer != null) __obj.updateDynamic("codegurureviewer")(codegurureviewer.asInstanceOf[js.Any])
    if (codepipeline != null) __obj.updateDynamic("codepipeline")(codepipeline.asInstanceOf[js.Any])
    if (codestar != null) __obj.updateDynamic("codestar")(codestar.asInstanceOf[js.Any])
    if (codestarconnections != null) __obj.updateDynamic("codestarconnections")(codestarconnections.asInstanceOf[js.Any])
    if (codestarnotifications != null) __obj.updateDynamic("codestarnotifications")(codestarnotifications.asInstanceOf[js.Any])
    if (cognitoidentity != null) __obj.updateDynamic("cognitoidentity")(cognitoidentity.asInstanceOf[js.Any])
    if (cognitoidentityserviceprovider != null) __obj.updateDynamic("cognitoidentityserviceprovider")(cognitoidentityserviceprovider.asInstanceOf[js.Any])
    if (cognitosync != null) __obj.updateDynamic("cognitosync")(cognitosync.asInstanceOf[js.Any])
    if (comprehend != null) __obj.updateDynamic("comprehend")(comprehend.asInstanceOf[js.Any])
    if (comprehendmedical != null) __obj.updateDynamic("comprehendmedical")(comprehendmedical.asInstanceOf[js.Any])
    if (computeoptimizer != null) __obj.updateDynamic("computeoptimizer")(computeoptimizer.asInstanceOf[js.Any])
    if (configservice != null) __obj.updateDynamic("configservice")(configservice.asInstanceOf[js.Any])
    if (connect != null) __obj.updateDynamic("connect")(connect.asInstanceOf[js.Any])
    if (connectparticipant != null) __obj.updateDynamic("connectparticipant")(connectparticipant.asInstanceOf[js.Any])
    if (costexplorer != null) __obj.updateDynamic("costexplorer")(costexplorer.asInstanceOf[js.Any])
    if (cur != null) __obj.updateDynamic("cur")(cur.asInstanceOf[js.Any])
    if (dataexchange != null) __obj.updateDynamic("dataexchange")(dataexchange.asInstanceOf[js.Any])
    if (datapipeline != null) __obj.updateDynamic("datapipeline")(datapipeline.asInstanceOf[js.Any])
    if (datasync != null) __obj.updateDynamic("datasync")(datasync.asInstanceOf[js.Any])
    if (dax != null) __obj.updateDynamic("dax")(dax.asInstanceOf[js.Any])
    if (detective != null) __obj.updateDynamic("detective")(detective.asInstanceOf[js.Any])
    if (devicefarm != null) __obj.updateDynamic("devicefarm")(devicefarm.asInstanceOf[js.Any])
    if (directconnect != null) __obj.updateDynamic("directconnect")(directconnect.asInstanceOf[js.Any])
    if (directoryservice != null) __obj.updateDynamic("directoryservice")(directoryservice.asInstanceOf[js.Any])
    if (discovery != null) __obj.updateDynamic("discovery")(discovery.asInstanceOf[js.Any])
    if (dlm != null) __obj.updateDynamic("dlm")(dlm.asInstanceOf[js.Any])
    if (dms != null) __obj.updateDynamic("dms")(dms.asInstanceOf[js.Any])
    if (docdb != null) __obj.updateDynamic("docdb")(docdb.asInstanceOf[js.Any])
    if (dynamodb != null) __obj.updateDynamic("dynamodb")(dynamodb.asInstanceOf[js.Any])
    if (dynamodbstreams != null) __obj.updateDynamic("dynamodbstreams")(dynamodbstreams.asInstanceOf[js.Any])
    if (ebs != null) __obj.updateDynamic("ebs")(ebs.asInstanceOf[js.Any])
    if (ec2 != null) __obj.updateDynamic("ec2")(ec2.asInstanceOf[js.Any])
    if (ec2instanceconnect != null) __obj.updateDynamic("ec2instanceconnect")(ec2instanceconnect.asInstanceOf[js.Any])
    if (ecr != null) __obj.updateDynamic("ecr")(ecr.asInstanceOf[js.Any])
    if (ecs != null) __obj.updateDynamic("ecs")(ecs.asInstanceOf[js.Any])
    if (efs != null) __obj.updateDynamic("efs")(efs.asInstanceOf[js.Any])
    if (eks != null) __obj.updateDynamic("eks")(eks.asInstanceOf[js.Any])
    if (elasticache != null) __obj.updateDynamic("elasticache")(elasticache.asInstanceOf[js.Any])
    if (elasticbeanstalk != null) __obj.updateDynamic("elasticbeanstalk")(elasticbeanstalk.asInstanceOf[js.Any])
    if (elasticinference != null) __obj.updateDynamic("elasticinference")(elasticinference.asInstanceOf[js.Any])
    if (elastictranscoder != null) __obj.updateDynamic("elastictranscoder")(elastictranscoder.asInstanceOf[js.Any])
    if (elb != null) __obj.updateDynamic("elb")(elb.asInstanceOf[js.Any])
    if (elbv2 != null) __obj.updateDynamic("elbv2")(elbv2.asInstanceOf[js.Any])
    if (emr != null) __obj.updateDynamic("emr")(emr.asInstanceOf[js.Any])
    if (es != null) __obj.updateDynamic("es")(es.asInstanceOf[js.Any])
    if (eventbridge != null) __obj.updateDynamic("eventbridge")(eventbridge.asInstanceOf[js.Any])
    if (firehose != null) __obj.updateDynamic("firehose")(firehose.asInstanceOf[js.Any])
    if (fms != null) __obj.updateDynamic("fms")(fms.asInstanceOf[js.Any])
    if (forecastqueryservice != null) __obj.updateDynamic("forecastqueryservice")(forecastqueryservice.asInstanceOf[js.Any])
    if (forecastservice != null) __obj.updateDynamic("forecastservice")(forecastservice.asInstanceOf[js.Any])
    if (frauddetector != null) __obj.updateDynamic("frauddetector")(frauddetector.asInstanceOf[js.Any])
    if (fsx != null) __obj.updateDynamic("fsx")(fsx.asInstanceOf[js.Any])
    if (gamelift != null) __obj.updateDynamic("gamelift")(gamelift.asInstanceOf[js.Any])
    if (glacier != null) __obj.updateDynamic("glacier")(glacier.asInstanceOf[js.Any])
    if (globalaccelerator != null) __obj.updateDynamic("globalaccelerator")(globalaccelerator.asInstanceOf[js.Any])
    if (glue != null) __obj.updateDynamic("glue")(glue.asInstanceOf[js.Any])
    if (greengrass != null) __obj.updateDynamic("greengrass")(greengrass.asInstanceOf[js.Any])
    if (groundstation != null) __obj.updateDynamic("groundstation")(groundstation.asInstanceOf[js.Any])
    if (guardduty != null) __obj.updateDynamic("guardduty")(guardduty.asInstanceOf[js.Any])
    if (health != null) __obj.updateDynamic("health")(health.asInstanceOf[js.Any])
    if (iam != null) __obj.updateDynamic("iam")(iam.asInstanceOf[js.Any])
    if (imagebuilder != null) __obj.updateDynamic("imagebuilder")(imagebuilder.asInstanceOf[js.Any])
    if (importexport != null) __obj.updateDynamic("importexport")(importexport.asInstanceOf[js.Any])
    if (inspector != null) __obj.updateDynamic("inspector")(inspector.asInstanceOf[js.Any])
    if (iot != null) __obj.updateDynamic("iot")(iot.asInstanceOf[js.Any])
    if (iot1clickdevicesservice != null) __obj.updateDynamic("iot1clickdevicesservice")(iot1clickdevicesservice.asInstanceOf[js.Any])
    if (iot1clickprojects != null) __obj.updateDynamic("iot1clickprojects")(iot1clickprojects.asInstanceOf[js.Any])
    if (iotanalytics != null) __obj.updateDynamic("iotanalytics")(iotanalytics.asInstanceOf[js.Any])
    if (iotdata != null) __obj.updateDynamic("iotdata")(iotdata.asInstanceOf[js.Any])
    if (iotevents != null) __obj.updateDynamic("iotevents")(iotevents.asInstanceOf[js.Any])
    if (ioteventsdata != null) __obj.updateDynamic("ioteventsdata")(ioteventsdata.asInstanceOf[js.Any])
    if (iotjobsdataplane != null) __obj.updateDynamic("iotjobsdataplane")(iotjobsdataplane.asInstanceOf[js.Any])
    if (iotsecuretunneling != null) __obj.updateDynamic("iotsecuretunneling")(iotsecuretunneling.asInstanceOf[js.Any])
    if (iotthingsgraph != null) __obj.updateDynamic("iotthingsgraph")(iotthingsgraph.asInstanceOf[js.Any])
    if (kafka != null) __obj.updateDynamic("kafka")(kafka.asInstanceOf[js.Any])
    if (kendra != null) __obj.updateDynamic("kendra")(kendra.asInstanceOf[js.Any])
    if (kinesis != null) __obj.updateDynamic("kinesis")(kinesis.asInstanceOf[js.Any])
    if (kinesisanalytics != null) __obj.updateDynamic("kinesisanalytics")(kinesisanalytics.asInstanceOf[js.Any])
    if (kinesisanalyticsv2 != null) __obj.updateDynamic("kinesisanalyticsv2")(kinesisanalyticsv2.asInstanceOf[js.Any])
    if (kinesisvideo != null) __obj.updateDynamic("kinesisvideo")(kinesisvideo.asInstanceOf[js.Any])
    if (kinesisvideoarchivedmedia != null) __obj.updateDynamic("kinesisvideoarchivedmedia")(kinesisvideoarchivedmedia.asInstanceOf[js.Any])
    if (kinesisvideomedia != null) __obj.updateDynamic("kinesisvideomedia")(kinesisvideomedia.asInstanceOf[js.Any])
    if (kinesisvideosignalingchannels != null) __obj.updateDynamic("kinesisvideosignalingchannels")(kinesisvideosignalingchannels.asInstanceOf[js.Any])
    if (kms != null) __obj.updateDynamic("kms")(kms.asInstanceOf[js.Any])
    if (lakeformation != null) __obj.updateDynamic("lakeformation")(lakeformation.asInstanceOf[js.Any])
    if (lambda != null) __obj.updateDynamic("lambda")(lambda.asInstanceOf[js.Any])
    if (lexmodelbuildingservice != null) __obj.updateDynamic("lexmodelbuildingservice")(lexmodelbuildingservice.asInstanceOf[js.Any])
    if (lexruntime != null) __obj.updateDynamic("lexruntime")(lexruntime.asInstanceOf[js.Any])
    if (licensemanager != null) __obj.updateDynamic("licensemanager")(licensemanager.asInstanceOf[js.Any])
    if (lightsail != null) __obj.updateDynamic("lightsail")(lightsail.asInstanceOf[js.Any])
    if (machinelearning != null) __obj.updateDynamic("machinelearning")(machinelearning.asInstanceOf[js.Any])
    if (macie != null) __obj.updateDynamic("macie")(macie.asInstanceOf[js.Any])
    if (managedblockchain != null) __obj.updateDynamic("managedblockchain")(managedblockchain.asInstanceOf[js.Any])
    if (marketplacecatalog != null) __obj.updateDynamic("marketplacecatalog")(marketplacecatalog.asInstanceOf[js.Any])
    if (marketplacecommerceanalytics != null) __obj.updateDynamic("marketplacecommerceanalytics")(marketplacecommerceanalytics.asInstanceOf[js.Any])
    if (marketplaceentitlementservice != null) __obj.updateDynamic("marketplaceentitlementservice")(marketplaceentitlementservice.asInstanceOf[js.Any])
    if (marketplacemetering != null) __obj.updateDynamic("marketplacemetering")(marketplacemetering.asInstanceOf[js.Any])
    if (mediaconnect != null) __obj.updateDynamic("mediaconnect")(mediaconnect.asInstanceOf[js.Any])
    if (mediaconvert != null) __obj.updateDynamic("mediaconvert")(mediaconvert.asInstanceOf[js.Any])
    if (medialive != null) __obj.updateDynamic("medialive")(medialive.asInstanceOf[js.Any])
    if (mediapackage != null) __obj.updateDynamic("mediapackage")(mediapackage.asInstanceOf[js.Any])
    if (mediapackagevod != null) __obj.updateDynamic("mediapackagevod")(mediapackagevod.asInstanceOf[js.Any])
    if (mediastore != null) __obj.updateDynamic("mediastore")(mediastore.asInstanceOf[js.Any])
    if (mediastoredata != null) __obj.updateDynamic("mediastoredata")(mediastoredata.asInstanceOf[js.Any])
    if (mediatailor != null) __obj.updateDynamic("mediatailor")(mediatailor.asInstanceOf[js.Any])
    if (migrationhub != null) __obj.updateDynamic("migrationhub")(migrationhub.asInstanceOf[js.Any])
    if (migrationhubconfig != null) __obj.updateDynamic("migrationhubconfig")(migrationhubconfig.asInstanceOf[js.Any])
    if (mobile != null) __obj.updateDynamic("mobile")(mobile.asInstanceOf[js.Any])
    if (mobileanalytics != null) __obj.updateDynamic("mobileanalytics")(mobileanalytics.asInstanceOf[js.Any])
    if (mq != null) __obj.updateDynamic("mq")(mq.asInstanceOf[js.Any])
    if (mturk != null) __obj.updateDynamic("mturk")(mturk.asInstanceOf[js.Any])
    if (neptune != null) __obj.updateDynamic("neptune")(neptune.asInstanceOf[js.Any])
    if (networkmanager != null) __obj.updateDynamic("networkmanager")(networkmanager.asInstanceOf[js.Any])
    if (opsworks != null) __obj.updateDynamic("opsworks")(opsworks.asInstanceOf[js.Any])
    if (opsworkscm != null) __obj.updateDynamic("opsworkscm")(opsworkscm.asInstanceOf[js.Any])
    if (organizations != null) __obj.updateDynamic("organizations")(organizations.asInstanceOf[js.Any])
    if (outposts != null) __obj.updateDynamic("outposts")(outposts.asInstanceOf[js.Any])
    if (personalize != null) __obj.updateDynamic("personalize")(personalize.asInstanceOf[js.Any])
    if (personalizeevents != null) __obj.updateDynamic("personalizeevents")(personalizeevents.asInstanceOf[js.Any])
    if (personalizeruntime != null) __obj.updateDynamic("personalizeruntime")(personalizeruntime.asInstanceOf[js.Any])
    if (pi != null) __obj.updateDynamic("pi")(pi.asInstanceOf[js.Any])
    if (pinpoint != null) __obj.updateDynamic("pinpoint")(pinpoint.asInstanceOf[js.Any])
    if (pinpointemail != null) __obj.updateDynamic("pinpointemail")(pinpointemail.asInstanceOf[js.Any])
    if (pinpointsmsvoice != null) __obj.updateDynamic("pinpointsmsvoice")(pinpointsmsvoice.asInstanceOf[js.Any])
    if (polly != null) __obj.updateDynamic("polly")(polly.asInstanceOf[js.Any])
    if (pricing != null) __obj.updateDynamic("pricing")(pricing.asInstanceOf[js.Any])
    if (qldb != null) __obj.updateDynamic("qldb")(qldb.asInstanceOf[js.Any])
    if (qldbsession != null) __obj.updateDynamic("qldbsession")(qldbsession.asInstanceOf[js.Any])
    if (quicksight != null) __obj.updateDynamic("quicksight")(quicksight.asInstanceOf[js.Any])
    if (ram != null) __obj.updateDynamic("ram")(ram.asInstanceOf[js.Any])
    if (rds != null) __obj.updateDynamic("rds")(rds.asInstanceOf[js.Any])
    if (rdsdataservice != null) __obj.updateDynamic("rdsdataservice")(rdsdataservice.asInstanceOf[js.Any])
    if (redshift != null) __obj.updateDynamic("redshift")(redshift.asInstanceOf[js.Any])
    if (rekognition != null) __obj.updateDynamic("rekognition")(rekognition.asInstanceOf[js.Any])
    if (resourcegroups != null) __obj.updateDynamic("resourcegroups")(resourcegroups.asInstanceOf[js.Any])
    if (resourcegroupstaggingapi != null) __obj.updateDynamic("resourcegroupstaggingapi")(resourcegroupstaggingapi.asInstanceOf[js.Any])
    if (robomaker != null) __obj.updateDynamic("robomaker")(robomaker.asInstanceOf[js.Any])
    if (route53 != null) __obj.updateDynamic("route53")(route53.asInstanceOf[js.Any])
    if (route53domains != null) __obj.updateDynamic("route53domains")(route53domains.asInstanceOf[js.Any])
    if (route53resolver != null) __obj.updateDynamic("route53resolver")(route53resolver.asInstanceOf[js.Any])
    if (s3 != null) __obj.updateDynamic("s3")(s3.asInstanceOf[js.Any])
    if (s3control != null) __obj.updateDynamic("s3control")(s3control.asInstanceOf[js.Any])
    if (sagemaker != null) __obj.updateDynamic("sagemaker")(sagemaker.asInstanceOf[js.Any])
    if (sagemakerruntime != null) __obj.updateDynamic("sagemakerruntime")(sagemakerruntime.asInstanceOf[js.Any])
    if (savingsplans != null) __obj.updateDynamic("savingsplans")(savingsplans.asInstanceOf[js.Any])
    if (schemas != null) __obj.updateDynamic("schemas")(schemas.asInstanceOf[js.Any])
    if (secretsmanager != null) __obj.updateDynamic("secretsmanager")(secretsmanager.asInstanceOf[js.Any])
    if (securityhub != null) __obj.updateDynamic("securityhub")(securityhub.asInstanceOf[js.Any])
    if (serverlessapplicationrepository != null) __obj.updateDynamic("serverlessapplicationrepository")(serverlessapplicationrepository.asInstanceOf[js.Any])
    if (servicecatalog != null) __obj.updateDynamic("servicecatalog")(servicecatalog.asInstanceOf[js.Any])
    if (servicediscovery != null) __obj.updateDynamic("servicediscovery")(servicediscovery.asInstanceOf[js.Any])
    if (servicequotas != null) __obj.updateDynamic("servicequotas")(servicequotas.asInstanceOf[js.Any])
    if (ses != null) __obj.updateDynamic("ses")(ses.asInstanceOf[js.Any])
    if (sesv2 != null) __obj.updateDynamic("sesv2")(sesv2.asInstanceOf[js.Any])
    if (shield != null) __obj.updateDynamic("shield")(shield.asInstanceOf[js.Any])
    if (signer != null) __obj.updateDynamic("signer")(signer.asInstanceOf[js.Any])
    if (simpledb != null) __obj.updateDynamic("simpledb")(simpledb.asInstanceOf[js.Any])
    if (sms != null) __obj.updateDynamic("sms")(sms.asInstanceOf[js.Any])
    if (snowball != null) __obj.updateDynamic("snowball")(snowball.asInstanceOf[js.Any])
    if (sns != null) __obj.updateDynamic("sns")(sns.asInstanceOf[js.Any])
    if (sqs != null) __obj.updateDynamic("sqs")(sqs.asInstanceOf[js.Any])
    if (ssm != null) __obj.updateDynamic("ssm")(ssm.asInstanceOf[js.Any])
    if (sso != null) __obj.updateDynamic("sso")(sso.asInstanceOf[js.Any])
    if (ssooidc != null) __obj.updateDynamic("ssooidc")(ssooidc.asInstanceOf[js.Any])
    if (stepfunctions != null) __obj.updateDynamic("stepfunctions")(stepfunctions.asInstanceOf[js.Any])
    if (storagegateway != null) __obj.updateDynamic("storagegateway")(storagegateway.asInstanceOf[js.Any])
    if (sts != null) __obj.updateDynamic("sts")(sts.asInstanceOf[js.Any])
    if (support != null) __obj.updateDynamic("support")(support.asInstanceOf[js.Any])
    if (swf != null) __obj.updateDynamic("swf")(swf.asInstanceOf[js.Any])
    if (textract != null) __obj.updateDynamic("textract")(textract.asInstanceOf[js.Any])
    if (transcribeservice != null) __obj.updateDynamic("transcribeservice")(transcribeservice.asInstanceOf[js.Any])
    if (transfer != null) __obj.updateDynamic("transfer")(transfer.asInstanceOf[js.Any])
    if (translate != null) __obj.updateDynamic("translate")(translate.asInstanceOf[js.Any])
    if (waf != null) __obj.updateDynamic("waf")(waf.asInstanceOf[js.Any])
    if (wafregional != null) __obj.updateDynamic("wafregional")(wafregional.asInstanceOf[js.Any])
    if (wafv2 != null) __obj.updateDynamic("wafv2")(wafv2.asInstanceOf[js.Any])
    if (workdocs != null) __obj.updateDynamic("workdocs")(workdocs.asInstanceOf[js.Any])
    if (worklink != null) __obj.updateDynamic("worklink")(worklink.asInstanceOf[js.Any])
    if (workmail != null) __obj.updateDynamic("workmail")(workmail.asInstanceOf[js.Any])
    if (workmailmessageflow != null) __obj.updateDynamic("workmailmessageflow")(workmailmessageflow.asInstanceOf[js.Any])
    if (workspaces != null) __obj.updateDynamic("workspaces")(workspaces.asInstanceOf[js.Any])
    if (xray != null) __obj.updateDynamic("xray")(xray.asInstanceOf[js.Any])
    __obj.asInstanceOf[ConfigurationServiceApiVersions]
  }
}

