package typingsJapgolly.dynatable.JQueryDynatable

import japgolly.scalajs.react.CallbackTo
import org.scalajs.dom.raw.Element
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Column extends js.Object {
  var hidden: Boolean
  /**
    * Determined by the `data-dynatable-column` or using the `defaultColumnIdStyle`
    *
    * @example
    * // Using the `defaultColumnIdStyle` of `camelCase`
    * // `<th>Favorite Music</th>` would be translated into the id `favoriteMusic`
    */
  var id: String
  var index: Double
  var label: String
  /** List of ids for sorting, generated by the plugin, can be tweaked by using `data-dynatable-sorts` */
  var sorts: js.Array[String]
  /**
    * Detected internally by dynatable.
    * Possible values are:
    *
    * @enum('left', 'right', 'center', 'justify', 'initial', 'inherit')
    */
  var textAlign: String
  /**
    * Function that interprets the cell html data in order to convert it into data
    *
    * @param cell A html node of the target cell
    * @param record A data object representing the current line of data
    * @return the html content for the current cell
    *
    * @example
    * function exampleAttributeReader(cell, record) {
    *     return $(cell).html();
    * };
    */
  def attributeReader(cell: Element, record: js.Any): String
  /**
    * Function that returns the cell data to be written inside the cell
    *
    * @param record A data object representing the current line of data
    * @return The data for the current cell
    *
    * @example
    * function exampleAttributeWriter(record) {
    *     return record[this.id];
    * };
    */
  def attributeWriter(record: js.Any): js.Any
}

object Column {
  @scala.inline
  def apply(
    attributeReader: (Element, js.Any) => CallbackTo[String],
    attributeWriter: js.Any => CallbackTo[js.Any],
    hidden: Boolean,
    id: String,
    index: Double,
    label: String,
    sorts: js.Array[String],
    textAlign: String
  ): Column = {
    val __obj = js.Dynamic.literal(hidden = hidden.asInstanceOf[js.Any], id = id.asInstanceOf[js.Any], index = index.asInstanceOf[js.Any], label = label.asInstanceOf[js.Any], sorts = sorts.asInstanceOf[js.Any], textAlign = textAlign.asInstanceOf[js.Any])
    __obj.updateDynamic("attributeReader")(js.Any.fromFunction2((t0: org.scalajs.dom.raw.Element, t1: js.Any) => attributeReader(t0, t1).runNow()))
    __obj.updateDynamic("attributeWriter")(js.Any.fromFunction1((t0: js.Any) => attributeWriter(t0).runNow()))
    __obj.asInstanceOf[Column]
  }
}

