package typingsJapgolly.activexLibreoffice.com_.sun.star.awt

import japgolly.scalajs.react.Callback
import japgolly.scalajs.react.CallbackTo
import typingsJapgolly.activexLibreoffice.`type`
import typingsJapgolly.activexLibreoffice.com_.sun.star.uno.XInterface
import typingsJapgolly.std.SafeArray
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/** Handles events fired by windows represented by a {@link com.sun.star.awt.XWindow} interface. */
trait XContainerWindowEventHandler
  extends StObject
     with XInterface {
  
  /**
    * returns a sequence of supported method names
    * @returns all method names that will be accepted in calls to callHandlerMethod.
    */
  val SupportedMethodNames: SafeArray[String]
  
  /**
    * Handles an event generated by a window.
    *
    * The implementation must be aware that the EventObject argument contains types which it is not prepared to handle. Similarly this applies for the
    * MethodName argument. In this case the method should simply return false.
    * @param xWindow the window instance that generated the event. If used in the scope of {@link com.sun.star.awt.XContainerWindowProvider} this is the same
    * @param EventObject an object describing the event which occurred in the window or anything else that provides additional information for the event. If t
    * @param MethodName the name of the function which is to be called.
    * @returns true if the event was handled, otherwise false.
    * @throws com::sun::star::lang::WrappedTargetException if the implementation of the method, which is determined by the argument MethodName, throws an excep
    */
  def callHandlerMethod(xWindow: XWindow, EventObject: Any, MethodName: String): Boolean
  
  /**
    * returns a sequence of supported method names
    * @returns all method names that will be accepted in calls to callHandlerMethod.
    */
  def getSupportedMethodNames(): SafeArray[String]
}
object XContainerWindowEventHandler {
  
  inline def apply(
    SupportedMethodNames: SafeArray[String],
    acquire: Callback,
    callHandlerMethod: (XWindow, Any, String) => Boolean,
    getSupportedMethodNames: CallbackTo[SafeArray[String]],
    queryInterface: `type` => Any,
    release: Callback
  ): XContainerWindowEventHandler = {
    val __obj = js.Dynamic.literal(SupportedMethodNames = SupportedMethodNames.asInstanceOf[js.Any], acquire = acquire.toJsFn, callHandlerMethod = js.Any.fromFunction3(callHandlerMethod), getSupportedMethodNames = getSupportedMethodNames.toJsFn, queryInterface = js.Any.fromFunction1(queryInterface), release = release.toJsFn)
    __obj.asInstanceOf[XContainerWindowEventHandler]
  }
  
  extension [Self <: XContainerWindowEventHandler](x: Self) {
    
    inline def setCallHandlerMethod(value: (XWindow, Any, String) => Boolean): Self = StObject.set(x, "callHandlerMethod", js.Any.fromFunction3(value))
    
    inline def setGetSupportedMethodNames(value: CallbackTo[SafeArray[String]]): Self = StObject.set(x, "getSupportedMethodNames", value.toJsFn)
    
    inline def setSupportedMethodNames(value: SafeArray[String]): Self = StObject.set(x, "SupportedMethodNames", value.asInstanceOf[js.Any])
  }
}
