package typingsJapgolly.p5

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object mod {
  type ADD = typingsJapgolly.p5.p5Strings.lighter
  type ANGLE_MODE = typingsJapgolly.p5.mod.RADIANS | typingsJapgolly.p5.mod.DEGREES
  type ARC_MODE = typingsJapgolly.p5.mod.CHORD | typingsJapgolly.p5.mod.PIE | typingsJapgolly.p5.mod.OPEN
  type ARROW = typingsJapgolly.p5.p5Strings.arrow
  type AUDIO = typingsJapgolly.p5.p5Strings.audio
  type AUTO = typingsJapgolly.p5.p5Strings.auto
  type AXES = typingsJapgolly.p5.p5Strings.axes
  type BASELINE = typingsJapgolly.p5.p5Strings.alphabetic
  type BEGIN_KIND = typingsJapgolly.p5.mod.POINTS | typingsJapgolly.p5.mod.LINES | typingsJapgolly.p5.mod.TRIANGLES | typingsJapgolly.p5.mod.TRIANGLE_FAN | typingsJapgolly.p5.mod.TRIANGLE_STRIP | typingsJapgolly.p5.mod.QUADS | typingsJapgolly.p5.mod.QUAD_STRIP
  type BEVEL = typingsJapgolly.p5.p5Strings.bevel
  type BEZIER = typingsJapgolly.p5.p5Strings.bezier
  type BLEND = typingsJapgolly.p5.p5Strings.`source-over`
  type BLEND_MODE = typingsJapgolly.p5.mod.BLEND | typingsJapgolly.p5.mod.DARKEST | typingsJapgolly.p5.mod.LIGHTEST | typingsJapgolly.p5.mod.DIFFERENCE | typingsJapgolly.p5.mod.MULTIPLY | typingsJapgolly.p5.mod.EXCLUSION | typingsJapgolly.p5.mod.SCREEN | typingsJapgolly.p5.mod.REPLACE | typingsJapgolly.p5.mod.OVERLAY | typingsJapgolly.p5.mod.HARD_LIGHT | typingsJapgolly.p5.mod.SOFT_LIGHT | typingsJapgolly.p5.mod.DODGE | typingsJapgolly.p5.mod.BURN | typingsJapgolly.p5.mod.ADD | typingsJapgolly.p5.mod.NORMAL
  type BLUR = typingsJapgolly.p5.p5Strings.blur
  type BOLD = typingsJapgolly.p5.p5Strings.bold
  type BOLDITALIC = typingsJapgolly.p5.p5Strings.bolditalic
  type BOTTOM = typingsJapgolly.p5.p5Strings.bottom
  type BURN = typingsJapgolly.p5.p5Strings.`color-burn`
  type BandPass = typingsJapgolly.p5.mod.Filter
  type CENTER = typingsJapgolly.p5.p5Strings.center
  type CHORD = typingsJapgolly.p5.p5Strings.chord
  type CLAMP = typingsJapgolly.p5.p5Strings.clamp
  type CLOSE = typingsJapgolly.p5.p5Strings.close
  type COLOR_MODE = typingsJapgolly.p5.mod.RGB | typingsJapgolly.p5.mod.HSB | typingsJapgolly.p5.mod.HSL
  type CORNER = typingsJapgolly.p5.p5Strings.corner
  type CORNERS = typingsJapgolly.p5.p5Strings.corners
  type CROSS = typingsJapgolly.p5.p5Strings.cross
  type CURSOR_TYPE = typingsJapgolly.p5.mod.ARROW | typingsJapgolly.p5.mod.CROSS | typingsJapgolly.p5.mod.HAND | typingsJapgolly.p5.mod.MOVE | typingsJapgolly.p5.mod.TEXT
  type CURVE = typingsJapgolly.p5.p5Strings.curve
  type DARKEST = typingsJapgolly.p5.p5Strings.darkest
  type DEBUG_MODE = typingsJapgolly.p5.mod.GRID | typingsJapgolly.p5.mod.AXES
  type DEGREES = typingsJapgolly.p5.p5Strings.degrees
  type DIFFERENCE = typingsJapgolly.p5.p5Strings.difference
  type DILATE = typingsJapgolly.p5.p5Strings.dilate
  type DODGE = typingsJapgolly.p5.p5Strings.`color-dodge`
  type ELLIPSE_MODE = typingsJapgolly.p5.mod.CENTER | typingsJapgolly.p5.mod.RADIUS | typingsJapgolly.p5.mod.CORNER | typingsJapgolly.p5.mod.CORNERS
  type END_MODE = typingsJapgolly.p5.mod.CLOSE
  type ERODE = typingsJapgolly.p5.p5Strings.erode
  type EXCLUSION = typingsJapgolly.p5.p5Strings.exclusion
  type FILL = typingsJapgolly.p5.p5Strings.fill
  type FILTER_TYPE = typingsJapgolly.p5.mod.THRESHOLD | typingsJapgolly.p5.mod.GRAY | typingsJapgolly.p5.mod.OPAQUE | typingsJapgolly.p5.mod.INVERT | typingsJapgolly.p5.mod.POSTERIZE | typingsJapgolly.p5.mod.BLUR | typingsJapgolly.p5.mod.ERODE | typingsJapgolly.p5.mod.DILATE
  type GRAPHICS_RENDERER = typingsJapgolly.p5.mod.P2D | typingsJapgolly.p5.mod.WEBGL
  type GRAY = typingsJapgolly.p5.p5Strings.gray
  type GRID = typingsJapgolly.p5.p5Strings.grid
  // Work-around for p5.Graphics inheriting from both p5 and p5.Element
  type Graphics = typingsJapgolly.p5.mod._Graphics with typingsJapgolly.p5.mod.p5
  type HAND = typingsJapgolly.p5.p5Strings.hand
  type HARD_LIGHT = typingsJapgolly.p5.p5Strings.`hard-light`
  type HORIZ_ALIGN = typingsJapgolly.p5.mod.LEFT | typingsJapgolly.p5.mod.CENTER | typingsJapgolly.p5.mod.RIGHT
  type HSB = typingsJapgolly.p5.p5Strings.hsb
  type HSL = typingsJapgolly.p5.p5Strings.hsl
  type HighPass = typingsJapgolly.p5.mod.Filter
  type IMAGE_ = typingsJapgolly.p5.p5Strings.image
  type IMAGE_MODE = typingsJapgolly.p5.mod.CORNER | typingsJapgolly.p5.mod.CORNERS | typingsJapgolly.p5.mod.CENTER
  type IMMEDIATE = typingsJapgolly.p5.p5Strings.immediate
  type INVERT = typingsJapgolly.p5.p5Strings.invert
  type ITALIC = typingsJapgolly.p5.p5Strings.italic
  type LANDSCAPE = typingsJapgolly.p5.p5Strings.landscape
  type LEFT = typingsJapgolly.p5.p5Strings.left
  type LIGHTEST = typingsJapgolly.p5.p5Strings.lighten
  type LINEAR = typingsJapgolly.p5.p5Strings.linear
  type LINES = typingsJapgolly.p5.p5Numbers.`0x0001`
  type LINE_LOOP = typingsJapgolly.p5.p5Numbers.`0x0002`
  type LINE_STRIP = typingsJapgolly.p5.p5Numbers.`0x0003`
  type LowPass = typingsJapgolly.p5.mod.Filter
  type MIRROR = typingsJapgolly.p5.p5Strings.mirror
  type MITER = typingsJapgolly.p5.p5Strings.miter
  type MOVE = typingsJapgolly.p5.p5Strings.move
  type MULTIPLY = typingsJapgolly.p5.p5Strings.multiply
  type NEAREST = typingsJapgolly.p5.p5Strings.nearest
  type NORMAL = typingsJapgolly.p5.p5Strings.normal
  type OPAQUE = typingsJapgolly.p5.p5Strings.opaque
  type OPEN = typingsJapgolly.p5.p5Strings.open
  type OVERLAY = typingsJapgolly.p5.p5Strings.overlay
  type P2D = typingsJapgolly.p5.p5Strings.p2d
  type PIE = typingsJapgolly.p5.p5Strings.pie
  type POINTS = typingsJapgolly.p5.p5Numbers.`0x0000`
  type PORTRAIT = typingsJapgolly.p5.p5Strings.portrait
  type POSTERIZE = typingsJapgolly.p5.p5Strings.posterize
  type PROJECT = typingsJapgolly.p5.p5Strings.square
  type QUADRATIC = typingsJapgolly.p5.p5Strings.quadratic
  type QUADS = typingsJapgolly.p5.p5Strings.quads
  type QUAD_STRIP = typingsJapgolly.p5.p5Strings.quad_strip
  type RADIANS = typingsJapgolly.p5.p5Strings.radians
  type RADIUS = typingsJapgolly.p5.p5Strings.radius
  type RECT_MODE = typingsJapgolly.p5.mod.CORNER | typingsJapgolly.p5.mod.CORNERS | typingsJapgolly.p5.mod.CENTER | typingsJapgolly.p5.mod.RADIUS
  type RENDERER_ = typingsJapgolly.p5.mod.P2D | typingsJapgolly.p5.mod.WEBGL
  type REPEAT = typingsJapgolly.p5.p5Strings.repeat
  type REPLACE = typingsJapgolly.p5.p5Strings.copy
  type RGB = typingsJapgolly.p5.p5Strings.rgb
  type RIGHT = typingsJapgolly.p5.p5Strings.right
  type ROUND = typingsJapgolly.p5.p5Strings.round
  type Renderer = typingsJapgolly.p5.mod.Element
  type SCREEN = typingsJapgolly.p5.p5Strings.screen
  type SIZE_H = typingsJapgolly.p5.mod.AUTO
  type SIZE_W = typingsJapgolly.p5.mod.AUTO
  type SOFT_LIGHT = typingsJapgolly.p5.p5Strings.`soft-light`
  type SQUARE = typingsJapgolly.p5.p5Strings.butt
  type STROKE = typingsJapgolly.p5.p5Strings.stroke
  type STROKE_CAP = typingsJapgolly.p5.mod.SQUARE | typingsJapgolly.p5.mod.PROJECT | typingsJapgolly.p5.mod.ROUND
  type STROKE_JOIN = typingsJapgolly.p5.mod.MITER | typingsJapgolly.p5.mod.BEVEL | typingsJapgolly.p5.mod.ROUND
  type SUBTRACT = typingsJapgolly.p5.p5Strings.subtract
  type SawOsc = typingsJapgolly.p5.mod.Oscillator
  type SinOsc = typingsJapgolly.p5.mod.Oscillator
  type SqrOsc = typingsJapgolly.p5.mod.Oscillator
  type StringDict = typingsJapgolly.p5.mod.TypedDict
  type TEXT = typingsJapgolly.p5.p5Strings.text
  type TEXTURE = typingsJapgolly.p5.p5Strings.texture
  type TEXTURE_MODE = typingsJapgolly.p5.mod.IMAGE_ | typingsJapgolly.p5.mod.NORMAL
  type THE_STYLE = typingsJapgolly.p5.mod.NORMAL | typingsJapgolly.p5.mod.ITALIC | typingsJapgolly.p5.mod.BOLD | typingsJapgolly.p5.mod.BOLDITALIC
  type THRESHOLD = typingsJapgolly.p5.p5Strings.threshold
  type TOP = typingsJapgolly.p5.p5Strings.top
  type TRIANGLES = typingsJapgolly.p5.p5Numbers.`0x0004`
  type TRIANGLE_FAN = typingsJapgolly.p5.p5Numbers.`0x0006`
  type TRIANGLE_STRIP = typingsJapgolly.p5.p5Numbers.`0x0005`
  type TYPE = typingsJapgolly.p5.mod.VIDEO | typingsJapgolly.p5.mod.AUDIO
  type TriOsc = typingsJapgolly.p5.mod.Oscillator
  type UNKNOWN_P5_CONSTANT = js.Any
  type VERT_ALIGN = typingsJapgolly.p5.mod.TOP | typingsJapgolly.p5.mod.BOTTOM | typingsJapgolly.p5.mod.CENTER | typingsJapgolly.p5.mod.BASELINE
  type VIDEO = typingsJapgolly.p5.p5Strings.video
  type WAIT = typingsJapgolly.p5.p5Strings.wait
  type WEBGL = typingsJapgolly.p5.p5Strings.webgl
  type WRAP_X = typingsJapgolly.p5.mod.CLAMP | typingsJapgolly.p5.mod.REPEAT | typingsJapgolly.p5.mod.MIRROR
  type WRAP_Y = typingsJapgolly.p5.mod.CLAMP | typingsJapgolly.p5.mod.REPEAT | typingsJapgolly.p5.mod.MIRROR
}
