package typingsJapgolly.reactMdMenu

import japgolly.scalajs.react.facade.React.Element
import typingsJapgolly.reactMdMenu.typesTypesMod.DropdownMenuProps
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object typesDropdownMenuMod {
  
  @JSImport("@react-md/menu/types/DropdownMenu", JSImport.Namespace)
  @js.native
  val ^ : js.Any = js.native
  
  inline def DropdownMenu(
    hasIdOnClickOnKeyDownOnMouseEnterOnMouseLeaveMenuLabelPropMenuPropsMenuStyleMenuClassNameSheetPropsSheetMenuPropsSheetStyleSheetClassNamePropSheetHeaderPropSheetFooterPropRenderAsSheetPropSheetPositionPropSheetVerticalSizeListStyleListClassNameListPropsAppearEnterExitPropTimeoutClassNamesAnchorFixedPositionOptionsGetFixedPositionOptionsTemporaryPortalPortalIntoPortalIntoIdOnEnterOnEnteringOnEnteredOnExitOnExitingOnExitedPropHorizontalChildrenPreventScrollCloseOnResizeCloseOnScrollPropIconRotator: DropdownMenuProps
  ): Element = ^.asInstanceOf[js.Dynamic].applyDynamic("DropdownMenu")(hasIdOnClickOnKeyDownOnMouseEnterOnMouseLeaveMenuLabelPropMenuPropsMenuStyleMenuClassNameSheetPropsSheetMenuPropsSheetStyleSheetClassNamePropSheetHeaderPropSheetFooterPropRenderAsSheetPropSheetPositionPropSheetVerticalSizeListStyleListClassNameListPropsAppearEnterExitPropTimeoutClassNamesAnchorFixedPositionOptionsGetFixedPositionOptionsTemporaryPortalPortalIntoPortalIntoIdOnEnterOnEnteringOnEnteredOnExitOnExitingOnExitedPropHorizontalChildrenPreventScrollCloseOnResizeCloseOnScrollPropIconRotator.asInstanceOf[js.Any]).asInstanceOf[Element]
}
