package typingsJapgolly.atSemanticDashUiDashReactEventDashStack.components

import typingsJapgolly.atSemanticDashUiDashReactEventDashStack.atSemanticDashUiDashReactEventDashStackMod.default
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object EventDashStack extends SharedApply_typingsJapgollyatSemanticDashUiDashReactEventDashStacklibTypesEventStackModEventStackProps1833997815[default] {
  override val __component: js.Any = js.constructorOf[typingsJapgolly.atSemanticDashUiDashReactEventDashStack.atSemanticDashUiDashReactEventDashStackMod.default]
}

