package typingsJapgolly.awsSdkClientGlacierNode.typesServiceUnavailableExceptionMod

import typingsJapgolly.awsSdkClientGlacierNode.abortMultipartUploadExceptionsUnionMod.AbortMultipartUploadExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.abortVaultLockExceptionsUnionMod.AbortVaultLockExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.addTagsToVaultExceptionsUnionMod.AddTagsToVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.completeMultipartUploadExceptionsUnionMod.CompleteMultipartUploadExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.completeVaultLockExceptionsUnionMod.CompleteVaultLockExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.createVaultExceptionsUnionMod.CreateVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.deleteArchiveExceptionsUnionMod.DeleteArchiveExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.deleteVaultAccessPolicyExceptionsUnionMod.DeleteVaultAccessPolicyExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.deleteVaultExceptionsUnionMod.DeleteVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.deleteVaultNotificationsExceptionsUnionMod.DeleteVaultNotificationsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.describeJobExceptionsUnionMod.DescribeJobExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.describeVaultExceptionsUnionMod.DescribeVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.getDataRetrievalPolicyExceptionsUnionMod.GetDataRetrievalPolicyExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.getJobOutputExceptionsUnionMod.GetJobOutputExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.getVaultAccessPolicyExceptionsUnionMod.GetVaultAccessPolicyExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.getVaultLockExceptionsUnionMod.GetVaultLockExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.getVaultNotificationsExceptionsUnionMod.GetVaultNotificationsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.initiateJobExceptionsUnionMod.InitiateJobExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.initiateMultipartUploadExceptionsUnionMod.InitiateMultipartUploadExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.initiateVaultLockExceptionsUnionMod.InitiateVaultLockExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listJobsExceptionsUnionMod.ListJobsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listMultipartUploadsExceptionsUnionMod.ListMultipartUploadsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listPartsExceptionsUnionMod.ListPartsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listProvisionedCapacityExceptionsUnionMod.ListProvisionedCapacityExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listTagsForVaultExceptionsUnionMod.ListTagsForVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.listVaultsExceptionsUnionMod.ListVaultsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.purchaseProvisionedCapacityExceptionsUnionMod.PurchaseProvisionedCapacityExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.removeTagsFromVaultExceptionsUnionMod.RemoveTagsFromVaultExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.setDataRetrievalPolicyExceptionsUnionMod.SetDataRetrievalPolicyExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.setVaultAccessPolicyExceptionsUnionMod.SetVaultAccessPolicyExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.setVaultNotificationsExceptionsUnionMod.SetVaultNotificationsExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.uploadArchiveExceptionsUnionMod.UploadArchiveExceptionsUnion
import typingsJapgolly.awsSdkClientGlacierNode.uploadMultipartPartExceptionsUnionMod.UploadMultipartPartExceptionsUnion
import typingsJapgolly.awsSdkTypes.exceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ServiceUnavailableException
  extends ServiceException[ServiceUnavailableExceptionDetails]
     with AbortMultipartUploadExceptionsUnion
     with AbortVaultLockExceptionsUnion
     with AddTagsToVaultExceptionsUnion
     with CompleteMultipartUploadExceptionsUnion
     with CompleteVaultLockExceptionsUnion
     with CreateVaultExceptionsUnion
     with DeleteArchiveExceptionsUnion
     with DeleteVaultAccessPolicyExceptionsUnion
     with DeleteVaultExceptionsUnion
     with DeleteVaultNotificationsExceptionsUnion
     with DescribeJobExceptionsUnion
     with DescribeVaultExceptionsUnion
     with GetDataRetrievalPolicyExceptionsUnion
     with GetJobOutputExceptionsUnion
     with GetVaultAccessPolicyExceptionsUnion
     with GetVaultLockExceptionsUnion
     with GetVaultNotificationsExceptionsUnion
     with InitiateJobExceptionsUnion
     with InitiateMultipartUploadExceptionsUnion
     with InitiateVaultLockExceptionsUnion
     with ListJobsExceptionsUnion
     with ListMultipartUploadsExceptionsUnion
     with ListPartsExceptionsUnion
     with ListProvisionedCapacityExceptionsUnion
     with ListTagsForVaultExceptionsUnion
     with ListVaultsExceptionsUnion
     with PurchaseProvisionedCapacityExceptionsUnion
     with RemoveTagsFromVaultExceptionsUnion
     with SetDataRetrievalPolicyExceptionsUnion
     with SetVaultAccessPolicyExceptionsUnion
     with SetVaultNotificationsExceptionsUnion
     with UploadArchiveExceptionsUnion
     with UploadMultipartPartExceptionsUnion {
  @JSName("name")
  var name_ServiceUnavailableException: typingsJapgolly.awsSdkClientGlacierNode.awsSdkClientGlacierNodeStrings.ServiceUnavailableException = js.native
}

