package typingsJapgolly.fuzzyset

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object global {
  
  inline def FuzzySet(): typingsJapgolly.fuzzyset.mod.FuzzySet = js.Dynamic.global.applyDynamic("FuzzySet")().asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String]): typingsJapgolly.fuzzyset.mod.FuzzySet = js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Boolean): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Boolean, gramSizeLower: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Boolean, gramSizeLower: Double, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Boolean, gramSizeLower: Unit, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Unit, gramSizeLower: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Unit, gramSizeLower: Double, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: js.Array[String], useLevenshtein: Unit, gramSizeLower: Unit, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Boolean): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Boolean, gramSizeLower: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Boolean, gramSizeLower: Double, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Boolean, gramSizeLower: Unit, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Unit, gramSizeLower: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Unit, gramSizeLower: Double, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
  inline def FuzzySet(source: Unit, useLevenshtein: Unit, gramSizeLower: Unit, gramSizeUpper: Double): typingsJapgolly.fuzzyset.mod.FuzzySet = (js.Dynamic.global.applyDynamic("FuzzySet")(source.asInstanceOf[js.Any], useLevenshtein.asInstanceOf[js.Any], gramSizeLower.asInstanceOf[js.Any], gramSizeUpper.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.fuzzyset.mod.FuzzySet]
}
