package typingsJapgolly.raml1Parser

import typingsJapgolly.raml1Parser.distParserArtifactsRaml10parserapiMod.Api
import typingsJapgolly.raml1Parser.distParserHighLevelASTMod.ApiLoadingError
import typingsJapgolly.raml1Parser.distParserHighLevelASTMod.ITypeDefinition
import typingsJapgolly.raml1Parser.distParserJsyamlResolversApiMod.FSResolver
import typingsJapgolly.raml1Parser.distParserWrappedAstParserCoreApiMod.LoadOptions
import typingsJapgolly.raml1Parser.distParserWrappedAstParserCoreApiMod.Options
import typingsJapgolly.raml1Parser.distParserWrappedAstParserCoreMod.BasicNode
import typingsJapgolly.raml1Parser.distTypingsNewFormatRamlMod.RAMLParseResult
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distParserApiLoaderMod {
  
  @JSImport("raml-1-parser/dist/parser/apiLoader", JSImport.Namespace)
  @js.native
  val ^ : js.Any = js.native
  
  inline def getLanguageElementByRuntimeType(runtimeType: ITypeDefinition): BasicNode = ^.asInstanceOf[js.Dynamic].applyDynamic("getLanguageElementByRuntimeType")(runtimeType.asInstanceOf[js.Any]).asInstanceOf[BasicNode]
  
  inline def load(ramlPathOrContent: String): js.Promise[RAMLParseResult] = ^.asInstanceOf[js.Dynamic].applyDynamic("load")(ramlPathOrContent.asInstanceOf[js.Any]).asInstanceOf[js.Promise[RAMLParseResult]]
  inline def load(ramlPathOrContent: String, options: LoadOptions): js.Promise[RAMLParseResult] = (^.asInstanceOf[js.Dynamic].applyDynamic("load")(ramlPathOrContent.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[js.Promise[RAMLParseResult]]
  
  inline def loadApi(apiPath: String): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: js.Array[String], arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: js.Array[String], arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: Unit, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: Unit, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: Options): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: Options, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApi(apiPath: String, arg1: Options, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApi")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  
  inline def loadApiAsync(apiPath: String): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any]).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: js.Array[String]): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: js.Array[String], arg2: js.Array[String]): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: js.Array[String], arg2: Options): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: Unit, arg2: js.Array[String]): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: Unit, arg2: Options): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: Options): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: Options, arg2: js.Array[String]): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  inline def loadApiAsync(apiPath: String, arg1: Options, arg2: Options): js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApiAsync")(apiPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[Api | typingsJapgolly.raml1Parser.distParserArtifactsRaml08parserapiMod.Api]]
  
  inline def loadApis1(projectRoot: String): js.Array[Api] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadApis1")(projectRoot.asInstanceOf[js.Any]).asInstanceOf[js.Array[Api]]
  inline def loadApis1(projectRoot: String, cacheChildren: Boolean): js.Array[Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApis1")(projectRoot.asInstanceOf[js.Any], cacheChildren.asInstanceOf[js.Any])).asInstanceOf[js.Array[Api]]
  inline def loadApis1(projectRoot: String, cacheChildren: Boolean, expandTraitsAndResourceTypes: Boolean): js.Array[Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApis1")(projectRoot.asInstanceOf[js.Any], cacheChildren.asInstanceOf[js.Any], expandTraitsAndResourceTypes.asInstanceOf[js.Any])).asInstanceOf[js.Array[Api]]
  inline def loadApis1(projectRoot: String, cacheChildren: Unit, expandTraitsAndResourceTypes: Boolean): js.Array[Api] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadApis1")(projectRoot.asInstanceOf[js.Any], cacheChildren.asInstanceOf[js.Any], expandTraitsAndResourceTypes.asInstanceOf[js.Any])).asInstanceOf[js.Array[Api]]
  
  inline def loadOptionsForContent(content: String): LoadOptions = ^.asInstanceOf[js.Dynamic].applyDynamic("loadOptionsForContent")(content.asInstanceOf[js.Any]).asInstanceOf[LoadOptions]
  inline def loadOptionsForContent(content: String, arg2: Unit, _filePath: String): LoadOptions = (^.asInstanceOf[js.Dynamic].applyDynamic("loadOptionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any], _filePath.asInstanceOf[js.Any])).asInstanceOf[LoadOptions]
  inline def loadOptionsForContent(content: String, arg2: LoadOptions): LoadOptions = (^.asInstanceOf[js.Dynamic].applyDynamic("loadOptionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[LoadOptions]
  inline def loadOptionsForContent(content: String, arg2: LoadOptions, _filePath: String): LoadOptions = (^.asInstanceOf[js.Dynamic].applyDynamic("loadOptionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any], _filePath.asInstanceOf[js.Any])).asInstanceOf[LoadOptions]
  
  inline def loadRAML(ramlPath: String): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: js.Array[String], arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: js.Array[String], arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: Unit, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: Unit, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: Options, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAML(ramlPath: String, arg1: Options, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAML")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  
  inline def loadRAMLAsync(ramlPath: String): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any]).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: js.Array[String], arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: js.Array[String], arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: Unit, arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: Unit, arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: Options, arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  inline def loadRAMLAsync(ramlPath: String, arg1: Options, arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsync")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.BasicNode]]
  
  inline def loadRAMLAsyncHL(ramlPath: String): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any]).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: js.Array[String], arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: js.Array[String], arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: Unit, arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: Unit, arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: Options, arg2: js.Array[String]): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLAsyncHL(ramlPath: String, arg1: Options, arg2: Options): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLAsyncHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  
  inline def loadRAMLHL(ramlPath: String): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: js.Array[String], arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: js.Array[String], arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: Unit, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: Unit, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: Options, arg2: js.Array[String]): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def loadRAMLHL(ramlPath: String, arg1: Options, arg2: Options): typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadRAMLHL")(ramlPath.asInstanceOf[js.Any], arg1.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distOptMod.^[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  
  inline def loadSync(ramlPathOrContent: String): RAMLParseResult = ^.asInstanceOf[js.Dynamic].applyDynamic("loadSync")(ramlPathOrContent.asInstanceOf[js.Any]).asInstanceOf[RAMLParseResult]
  inline def loadSync(ramlPathOrContent: String, options: LoadOptions): RAMLParseResult = (^.asInstanceOf[js.Dynamic].applyDynamic("loadSync")(ramlPathOrContent.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[RAMLParseResult]
  
  inline def optionsForContent(content: String): Options = ^.asInstanceOf[js.Dynamic].applyDynamic("optionsForContent")(content.asInstanceOf[js.Any]).asInstanceOf[Options]
  inline def optionsForContent(content: String, arg2: Unit, _filePath: String): Options = (^.asInstanceOf[js.Dynamic].applyDynamic("optionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any], _filePath.asInstanceOf[js.Any])).asInstanceOf[Options]
  inline def optionsForContent(content: String, arg2: Options): Options = (^.asInstanceOf[js.Dynamic].applyDynamic("optionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any])).asInstanceOf[Options]
  inline def optionsForContent(content: String, arg2: Options, _filePath: String): Options = (^.asInstanceOf[js.Dynamic].applyDynamic("optionsForContent")(content.asInstanceOf[js.Any], arg2.asInstanceOf[js.Any], _filePath.asInstanceOf[js.Any])).asInstanceOf[Options]
  
  inline def parse(ramlPathOrContent: String): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = ^.asInstanceOf[js.Dynamic].applyDynamic("parse")(ramlPathOrContent.asInstanceOf[js.Any]).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  inline def parse(ramlPathOrContent: String, options: LoadOptions): js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode] = (^.asInstanceOf[js.Dynamic].applyDynamic("parse")(ramlPathOrContent.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[js.Promise[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]]
  
  inline def parseSync(ramlPathOrContent: String): typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode = ^.asInstanceOf[js.Dynamic].applyDynamic("parseSync")(ramlPathOrContent.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]
  inline def parseSync(ramlPathOrContent: String, options: LoadOptions): typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode = (^.asInstanceOf[js.Dynamic].applyDynamic("parseSync")(ramlPathOrContent.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode]
  
  inline def toError(api: typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode): ApiLoadingError = ^.asInstanceOf[js.Dynamic].applyDynamic("toError")(api.asInstanceOf[js.Any]).asInstanceOf[ApiLoadingError]
  
  inline def virtualFSResolver(filePath: String, content: String, originalResolver: FSResolver): FSResolver = (^.asInstanceOf[js.Dynamic].applyDynamic("virtualFSResolver")(filePath.asInstanceOf[js.Any], content.asInstanceOf[js.Any], originalResolver.asInstanceOf[js.Any])).asInstanceOf[FSResolver]
  
  inline def virtualFilePath(opt: LoadOptions): String = ^.asInstanceOf[js.Dynamic].applyDynamic("virtualFilePath")(opt.asInstanceOf[js.Any]).asInstanceOf[String]
  inline def virtualFilePath(opt: Options): String = ^.asInstanceOf[js.Dynamic].applyDynamic("virtualFilePath")(opt.asInstanceOf[js.Any]).asInstanceOf[String]
  
  type IHighLevelNode = typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IHighLevelNode
  
  type IParseResult = typingsJapgolly.raml1Parser.distParserHighLevelASTMod.IParseResult
}
