package typingsJapgolly.babylonWalk

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object mod {
  type AncestorStatelessVisitor = js.Function3[
    /* node */ typingsJapgolly.babylonWalk.mod.NodeTypes, 
    /* state */ js.Any, 
    /* ancestors */ js.Array[typingsJapgolly.babelTypes.mod.Node], 
    scala.Unit
  ]
  type AncestorVisitor = js.Function3[
    /* node */ typingsJapgolly.babylonWalk.mod.NodeTypes, 
    /* state */ js.Any, 
    /* ancestors */ js.Array[typingsJapgolly.babelTypes.mod.Node], 
    scala.Unit
  ]
  type NodeTypes = typingsJapgolly.babylonWalk.mod.coreTypes | typingsJapgolly.babylonWalk.mod.es2015Types | typingsJapgolly.babylonWalk.mod.flowTypes | typingsJapgolly.babylonWalk.mod.jsxTypes | typingsJapgolly.babylonWalk.mod.miscTypes
  type RecursiveVisitor = js.Function3[
    /* node */ typingsJapgolly.babylonWalk.mod.NodeTypes, 
    /* state */ js.Any, 
    /* next */ js.Function1[/* node */ typingsJapgolly.babelTypes.mod.Node, scala.Unit], 
    scala.Unit
  ]
  type SimpleVisitor = js.Function2[/* node */ typingsJapgolly.babylonWalk.mod.NodeTypes, /* state */ js.Any, scala.Unit]
  type Visitor = js.Function2[
    /* commentBlock */ typingsJapgolly.babylonWalk.mod.NodeTypes, 
    /* state */ js.Any, 
    scala.Unit
  ]
  type coreTypes = typingsJapgolly.babelTypes.mod.ArrayExpression_ | typingsJapgolly.babelTypes.mod.AssignmentExpression_ | typingsJapgolly.babelTypes.mod.BinaryExpression_ | typingsJapgolly.babelTypes.mod.Directive_ | typingsJapgolly.babelTypes.mod.DirectiveLiteral_ | typingsJapgolly.babelTypes.mod.BlockStatement_ | typingsJapgolly.babelTypes.mod.BreakStatement_ | typingsJapgolly.babelTypes.mod.CallExpression_ | typingsJapgolly.babelTypes.mod.CatchClause_ | typingsJapgolly.babelTypes.mod.ConditionalExpression_ | typingsJapgolly.babelTypes.mod.ContinueStatement_ | typingsJapgolly.babelTypes.mod.DebuggerStatement_ | typingsJapgolly.babelTypes.mod.DoWhileStatement_ | typingsJapgolly.babelTypes.mod.EmptyStatement_ | typingsJapgolly.babelTypes.mod.ExpressionStatement_ | typingsJapgolly.babelTypes.mod.File_ | typingsJapgolly.babelTypes.mod.ForInStatement_ | typingsJapgolly.babelTypes.mod.ForStatement_ | typingsJapgolly.babelTypes.mod.FunctionDeclaration_ | typingsJapgolly.babelTypes.mod.FunctionExpression_ | typingsJapgolly.babelTypes.mod.Identifier_ | typingsJapgolly.babelTypes.mod.IfStatement_ | typingsJapgolly.babelTypes.mod.LabeledStatement_ | typingsJapgolly.babelTypes.mod.StringLiteral_ | typingsJapgolly.babelTypes.mod.NumericLiteral_ | typingsJapgolly.babelTypes.mod.NullLiteral_ | typingsJapgolly.babelTypes.mod.BooleanLiteral_ | typingsJapgolly.babelTypes.mod.RegExpLiteral_ | typingsJapgolly.babelTypes.mod.LogicalExpression_ | typingsJapgolly.babelTypes.mod.MemberExpression_ | typingsJapgolly.babelTypes.mod.NewExpression_ | typingsJapgolly.babelTypes.mod.Program_ | typingsJapgolly.babelTypes.mod.ObjectExpression_ | typingsJapgolly.babelTypes.mod.ObjectMethod_ | typingsJapgolly.babelTypes.mod.ObjectProperty_ | typingsJapgolly.babelTypes.mod.RestElement_ | typingsJapgolly.babelTypes.mod.ReturnStatement_ | typingsJapgolly.babelTypes.mod.SequenceExpression_ | typingsJapgolly.babelTypes.mod.SwitchCase_ | typingsJapgolly.babelTypes.mod.SwitchStatement_ | typingsJapgolly.babelTypes.mod.ThisExpression_ | typingsJapgolly.babelTypes.mod.ThrowStatement_ | typingsJapgolly.babelTypes.mod.TryStatement_ | typingsJapgolly.babelTypes.mod.UnaryExpression_ | typingsJapgolly.babelTypes.mod.UpdateExpression_ | typingsJapgolly.babelTypes.mod.VariableDeclaration_ | typingsJapgolly.babelTypes.mod.VariableDeclarator_ | typingsJapgolly.babelTypes.mod.WhileStatement_ | typingsJapgolly.babelTypes.mod.WithStatement_
  type es2015Types = typingsJapgolly.babelTypes.mod.AssignmentPattern_ | typingsJapgolly.babelTypes.mod.ArrayPattern_ | typingsJapgolly.babelTypes.mod.ArrowFunctionExpression_ | typingsJapgolly.babelTypes.mod.ClassBody_ | typingsJapgolly.babelTypes.mod.ClassDeclaration_ | typingsJapgolly.babelTypes.mod.ClassExpression_ | typingsJapgolly.babelTypes.mod.ExportAllDeclaration_ | typingsJapgolly.babelTypes.mod.ExportDefaultDeclaration_ | typingsJapgolly.babelTypes.mod.ExportNamedDeclaration_ | typingsJapgolly.babelTypes.mod.ExportSpecifier_ | typingsJapgolly.babelTypes.mod.ForOfStatement_ | typingsJapgolly.babelTypes.mod.ImportDeclaration_ | typingsJapgolly.babelTypes.mod.ImportDefaultSpecifier_ | typingsJapgolly.babelTypes.mod.ImportNamespaceSpecifier_ | typingsJapgolly.babelTypes.mod.ImportSpecifier_ | typingsJapgolly.babelTypes.mod.MetaProperty_ | typingsJapgolly.babelTypes.mod.ClassMethod_ | typingsJapgolly.babelTypes.mod.ObjectPattern_ | typingsJapgolly.babelTypes.mod.SpreadElement_ | typingsJapgolly.babelTypes.mod.Super | typingsJapgolly.babelTypes.mod.TaggedTemplateExpression_ | typingsJapgolly.babelTypes.mod.TemplateElement_ | typingsJapgolly.babelTypes.mod.TemplateLiteral_ | typingsJapgolly.babelTypes.mod.YieldExpression_ | typingsJapgolly.babelTypes.mod.AwaitExpression_ | typingsJapgolly.babelTypes.mod.BindExpression_ | typingsJapgolly.babelTypes.mod.ClassProperty_ | typingsJapgolly.babelTypes.mod.Decorator_ | typingsJapgolly.babelTypes.mod.DoExpression_ | typingsJapgolly.babelTypes.mod.ExportDefaultSpecifier_ | typingsJapgolly.babelTypes.mod.ExportNamespaceSpecifier_
  type flowTypes = typingsJapgolly.babelTypes.mod.AnyTypeAnnotation_ | typingsJapgolly.babelTypes.mod.ArrayTypeAnnotation_ | typingsJapgolly.babelTypes.mod.BooleanTypeAnnotation_ | typingsJapgolly.babelTypes.mod.BooleanLiteralTypeAnnotation_ | typingsJapgolly.babelTypes.mod.NullLiteralTypeAnnotation_ | typingsJapgolly.babelTypes.mod.ClassImplements_ | typingsJapgolly.babelTypes.mod.DeclareClass_ | typingsJapgolly.babelTypes.mod.DeclareFunction_ | typingsJapgolly.babelTypes.mod.DeclareInterface_ | typingsJapgolly.babelTypes.mod.DeclareModule_ | typingsJapgolly.babelTypes.mod.DeclareTypeAlias_ | typingsJapgolly.babelTypes.mod.DeclareVariable_ | typingsJapgolly.babelTypes.mod.FunctionTypeAnnotation_ | typingsJapgolly.babelTypes.mod.FunctionTypeParam_ | typingsJapgolly.babelTypes.mod.GenericTypeAnnotation_ | typingsJapgolly.babelTypes.mod.InterfaceExtends_ | typingsJapgolly.babelTypes.mod.InterfaceDeclaration_ | typingsJapgolly.babelTypes.mod.IntersectionTypeAnnotation_ | typingsJapgolly.babelTypes.mod.MixedTypeAnnotation_ | typingsJapgolly.babelTypes.mod.NullableTypeAnnotation_ | typingsJapgolly.babelTypes.mod.NumberTypeAnnotation_ | typingsJapgolly.babelTypes.mod.ObjectTypeAnnotation_ | typingsJapgolly.babelTypes.mod.ObjectTypeCallProperty_ | typingsJapgolly.babelTypes.mod.ObjectTypeIndexer_ | typingsJapgolly.babelTypes.mod.ObjectTypeProperty_ | typingsJapgolly.babelTypes.mod.QualifiedTypeIdentifier_ | typingsJapgolly.babelTypes.mod.StringLiteralTypeAnnotation_ | typingsJapgolly.babelTypes.mod.StringTypeAnnotation_ | typingsJapgolly.babelTypes.mod.ThisTypeAnnotation_ | typingsJapgolly.babelTypes.mod.TupleTypeAnnotation_ | typingsJapgolly.babelTypes.mod.TypeofTypeAnnotation_ | typingsJapgolly.babelTypes.mod.TypeAlias_ | typingsJapgolly.babelTypes.mod.TypeAnnotation_ | typingsJapgolly.babelTypes.mod.TypeCastExpression_ | typingsJapgolly.babelTypes.mod.TypeParameterDeclaration_ | typingsJapgolly.babelTypes.mod.TypeParameterInstantiation_ | typingsJapgolly.babelTypes.mod.UnionTypeAnnotation_ | typingsJapgolly.babelTypes.mod.VoidTypeAnnotation_
  type jsxTypes = typingsJapgolly.babelTypes.mod.JSXAttribute_ | typingsJapgolly.babelTypes.mod.JSXClosingElement_ | typingsJapgolly.babelTypes.mod.JSXElement_ | typingsJapgolly.babelTypes.mod.JSXEmptyExpression_ | typingsJapgolly.babelTypes.mod.JSXExpressionContainer_ | typingsJapgolly.babelTypes.mod.JSXIdentifier_ | typingsJapgolly.babelTypes.mod.JSXMemberExpression_ | typingsJapgolly.babelTypes.mod.JSXNamespacedName_ | typingsJapgolly.babelTypes.mod.JSXOpeningElement_ | typingsJapgolly.babelTypes.mod.JSXSpreadAttribute_ | typingsJapgolly.babelTypes.mod.JSXText_
  type miscTypes = typingsJapgolly.babelTypes.mod.Noop_ | typingsJapgolly.babelTypes.mod.ParenthesizedExpression_
}
