package typingsJapgolly.dexie.mod.Dexie

import typingsJapgolly.dexie.dexieStrings.Error
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

// errnames - handy spellcheck in switch (error.name) {} cases.        
@JSImport("dexie", "Dexie.errnames")
@js.native
object errnames extends js.Object {
  var Abort: typingsJapgolly.dexie.dexieStrings.AbortError = js.native
  var Constraint: typingsJapgolly.dexie.dexieStrings.ConstraintError = js.native
  var Data: typingsJapgolly.dexie.dexieStrings.DataError = js.native
  var DataClone: typingsJapgolly.dexie.dexieStrings.DataCloneError = js.native
  var DatabaseClosed: typingsJapgolly.dexie.dexieStrings.DatabaseClosedError = js.native
  var Internal: typingsJapgolly.dexie.dexieStrings.InternalError = js.native
  var InvalidAccess: typingsJapgolly.dexie.dexieStrings.InvalidAccessError = js.native
  var InvalidArgument: typingsJapgolly.dexie.dexieStrings.InvalidArgumentError = js.native
  var InvalidState: typingsJapgolly.dexie.dexieStrings.InvalidStateError = js.native
  var InvalidTable: typingsJapgolly.dexie.dexieStrings.InvalidTableError = js.native
  var MissingAPI: typingsJapgolly.dexie.dexieStrings.MissingAPIError = js.native
  // Dexie-specific error names:
  var Modify: typingsJapgolly.dexie.dexieStrings.ModifyError = js.native
  var NoSuchDatabase: typingsJapgolly.dexie.dexieStrings.NoSuchDatabaseError = js.native
  var NotFound: typingsJapgolly.dexie.dexieStrings.NotFoundError = js.native
  var OpenFailed: typingsJapgolly.dexie.dexieStrings.OpenFailedError = js.native
  var QuotaExceeded: typingsJapgolly.dexie.dexieStrings.QuotaExceededError = js.native
  var ReadOnly: typingsJapgolly.dexie.dexieStrings.ReadOnlyError = js.native
  var Schema: typingsJapgolly.dexie.dexieStrings.SchemaError = js.native
  var SubTransaction: Error = js.native
  var Syntax: typingsJapgolly.dexie.dexieStrings.SyntaxError = js.native
  var Timeout: typingsJapgolly.dexie.dexieStrings.TimeoutError = js.native
  var TransactionInactive: typingsJapgolly.dexie.dexieStrings.TransactionInactiveError = js.native
  // Error names generated by indexedDB:
  var Unknown: typingsJapgolly.dexie.dexieStrings.UnknownError = js.native
  var Unsupported: typingsJapgolly.dexie.dexieStrings.UnsupportedError = js.native
  var Upgrade: typingsJapgolly.dexie.dexieStrings.UpgradeError = js.native
  var Version: typingsJapgolly.dexie.dexieStrings.VersionError = js.native
  var VersionChange: typingsJapgolly.dexie.dexieStrings.VersionChangeError = js.native
}

