package typingsJapgolly.vsoNodeApi.interfacesTaskAgentInterfacesMod

import typingsJapgolly.vsoNodeApi.interfacesDistributedTaskCommonInterfacesMod.DataSourceBindingBase
import typingsJapgolly.vsoNodeApi.interfacesDistributedTaskCommonInterfacesMod.TaskInputDefinitionBase
import typingsJapgolly.vsoNodeApi.interfacesDistributedTaskCommonInterfacesMod.TaskSourceDefinitionBase
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


type DataSourceBinding = DataSourceBindingBase

type JobStartedEvent = JobEvent

type TaskInputDefinition = TaskInputDefinitionBase

type TaskSourceDefinition = TaskSourceDefinitionBase
