package typingsJapgolly.awsSdkClientCodecommitNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@aws-sdk/client-codecommit-node/types/CreatePullRequestExceptionsUnion", JSImport.Namespace)
@js.native
object createPullRequestExceptionsUnionMod extends js.Object {
  /* Rewritten from type alias, can be one of: 
    - typingsJapgolly.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesReferenceNameRequiredExceptionMod.ReferenceNameRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidReferenceNameExceptionMod.InvalidReferenceNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesReferenceTypeNotSupportedExceptionMod.ReferenceTypeNotSupportedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidDescriptionExceptionMod.InvalidDescriptionException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesTargetsRequiredExceptionMod.TargetsRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidTargetsExceptionMod.InvalidTargetsException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesTargetRequiredExceptionMod.TargetRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidTargetExceptionMod.InvalidTargetException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesMultipleRepositoriesInPullRequestExceptionMod.MultipleRepositoriesInPullRequestException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesMaximumOpenPullRequestsExceededExceptionMod.MaximumOpenPullRequestsExceededException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesSourceAndDestinationAreSameExceptionMod.SourceAndDestinationAreSameException
  */
  trait CreatePullRequestExceptionsUnion extends js.Object
  
}

