package typingsJapgolly.awsSdkClientCodecommitNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@aws-sdk/client-codecommit-node/types/PutFileExceptionsUnion", JSImport.Namespace)
@js.native
object putFileExceptionsUnionMod extends js.Object {
  /* Rewritten from type alias, can be one of: 
    - typingsJapgolly.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesParentCommitIdRequiredExceptionMod.ParentCommitIdRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidParentCommitIdExceptionMod.InvalidParentCommitIdException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesParentCommitDoesNotExistExceptionMod.ParentCommitDoesNotExistException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesParentCommitIdOutdatedExceptionMod.ParentCommitIdOutdatedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesFileContentRequiredExceptionMod.FileContentRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesFileContentSizeLimitExceededExceptionMod.FileContentSizeLimitExceededException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesPathRequiredExceptionMod.PathRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesBranchNameRequiredExceptionMod.BranchNameRequiredException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidBranchNameExceptionMod.InvalidBranchNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesBranchDoesNotExistExceptionMod.BranchDoesNotExistException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesBranchNameIsTagNameExceptionMod.BranchNameIsTagNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidFileModeExceptionMod.InvalidFileModeException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesNameLengthExceededExceptionMod.NameLengthExceededException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidEmailExceptionMod.InvalidEmailException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesCommitMessageLengthExceededExceptionMod.CommitMessageLengthExceededException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesInvalidDeletionParameterExceptionMod.InvalidDeletionParameterException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesSameFileContentExceptionMod.SameFileContentException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesFileNameConflictsWithDirectoryNameExceptionMod.FileNameConflictsWithDirectoryNameException
    - typingsJapgolly.awsSdkClientCodecommitNode.typesDirectoryNameConflictsWithFileNameExceptionMod.DirectoryNameConflictsWithFileNameException
  */
  trait PutFileExceptionsUnion extends js.Object
  
}

