package typingsJapgolly.kamailioKemi

import japgolly.scalajs.react.CallbackTo
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Typeofhdr extends js.Object {
  // Append header to current SIP message (request or reply). It will be added after the last header.
  def append(hdr: String): Double
  // Append header to current SIP message (request or reply).
  // It will be added after the first header matching the name hdrName.
  def append_after(hdr: String, hdrName: String): Double
  // Add a header to the SIP response to be generated by Kamailio for the current SIP request.
  def append_to_reply(hdr: String): Double
  // Insert header to current SIP message (request or reply).
  // It will be added before the first header.
  def insert(hdr: String): Double
  // Insert header to current SIP message (request or reply).
  // It will be added before the header matching the name hdrName.
  def insert_before(hdr: String, hdrName: String): Double
  // Return greater than 0 if a header with the name hdrName exists and less than 0 if there is no such header.
  def is_present(hdrName: String): Double
  // Remove all the headers with the name hdrName.
  def remove(hdrName: String): Double
}

object Typeofhdr {
  @scala.inline
  def apply(
    append: String => CallbackTo[Double],
    append_after: (String, String) => CallbackTo[Double],
    append_to_reply: String => CallbackTo[Double],
    insert: String => CallbackTo[Double],
    insert_before: (String, String) => CallbackTo[Double],
    is_present: String => CallbackTo[Double],
    remove: String => CallbackTo[Double]
  ): Typeofhdr = {
    val __obj = js.Dynamic.literal()
    __obj.updateDynamic("append")(js.Any.fromFunction1((t0: java.lang.String) => append(t0).runNow()))
    __obj.updateDynamic("append_after")(js.Any.fromFunction2((t0: java.lang.String, t1: java.lang.String) => append_after(t0, t1).runNow()))
    __obj.updateDynamic("append_to_reply")(js.Any.fromFunction1((t0: java.lang.String) => append_to_reply(t0).runNow()))
    __obj.updateDynamic("insert")(js.Any.fromFunction1((t0: java.lang.String) => insert(t0).runNow()))
    __obj.updateDynamic("insert_before")(js.Any.fromFunction2((t0: java.lang.String, t1: java.lang.String) => insert_before(t0, t1).runNow()))
    __obj.updateDynamic("is_present")(js.Any.fromFunction1((t0: java.lang.String) => is_present(t0).runNow()))
    __obj.updateDynamic("remove")(js.Any.fromFunction1((t0: java.lang.String) => remove(t0).runNow()))
    __obj.asInstanceOf[Typeofhdr]
  }
}

