package typingsJapgolly.authmosphere

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object oauthconfigMod {
  type AuthorizationCodeGrantConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsConfig with typingsJapgolly.authmosphere.oauthconfigMod.GrantConfigBase with typingsJapgolly.authmosphere.AnonCode
  type ClientCredentialsGrantConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsConfig with typingsJapgolly.authmosphere.oauthconfigMod.GrantConfigBase
  type CredentialsPasswordConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsDirConfig | typingsJapgolly.authmosphere.oauthconfigMod.CredentialsUserClientConfig
  type CredentialsUserClientConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsClientConfig with typingsJapgolly.authmosphere.oauthconfigMod.CredentialsUserConfig
  type OAuthConfig = typingsJapgolly.authmosphere.oauthconfigMod.ClientCredentialsGrantConfig | typingsJapgolly.authmosphere.oauthconfigMod.AuthorizationCodeGrantConfig | typingsJapgolly.authmosphere.oauthconfigMod.PasswordCredentialsGrantConfig | typingsJapgolly.authmosphere.oauthconfigMod.RefreshGrantConfig
  type PasswordCredentialsGrantConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsPasswordConfig with typingsJapgolly.authmosphere.oauthconfigMod.GrantConfigBase
  type RefreshGrantConfig = typingsJapgolly.authmosphere.oauthconfigMod.CredentialsConfig with typingsJapgolly.authmosphere.oauthconfigMod.GrantConfigBase with typingsJapgolly.authmosphere.AnonRefreshToken
  type TokenCacheOAuthConfig = (typingsJapgolly.authmosphere.oauthconfigMod.ClientCredentialsGrantConfig | typingsJapgolly.authmosphere.oauthconfigMod.PasswordCredentialsGrantConfig) with typingsJapgolly.authmosphere.AnonTokenInfoEndpoint
}
