package typingsJapgolly.webgpuTypes

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

// *********************************************************************************************
// Semi-auto-generated (by manual diff with autogenerated types)
// *********************************************************************************************
/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.webgpuTypes.GPUSampler
  - typingsJapgolly.webgpuTypes.GPUTextureView
  - typingsJapgolly.webgpuTypes.GPUBufferBinding
  - typingsJapgolly.webgpuTypes.GPUExternalTexture
*/
trait GPUBindingResource extends StObject
object GPUBindingResource {
  
  inline def GPUBufferBinding(buffer: GPUBuffer): typingsJapgolly.webgpuTypes.GPUBufferBinding = {
    val __obj = js.Dynamic.literal(buffer = buffer.asInstanceOf[js.Any])
    __obj.asInstanceOf[typingsJapgolly.webgpuTypes.GPUBufferBinding]
  }
  
  inline def GPUExternalTexture(expired: Boolean, label: String): typingsJapgolly.webgpuTypes.GPUExternalTexture = {
    val __obj = js.Dynamic.literal(__brand = "GPUExternalTexture", expired = expired.asInstanceOf[js.Any], label = label.asInstanceOf[js.Any])
    __obj.asInstanceOf[typingsJapgolly.webgpuTypes.GPUExternalTexture]
  }
  
  inline def GPUSampler(label: String): typingsJapgolly.webgpuTypes.GPUSampler = {
    val __obj = js.Dynamic.literal(__brand = "GPUSampler", label = label.asInstanceOf[js.Any])
    __obj.asInstanceOf[typingsJapgolly.webgpuTypes.GPUSampler]
  }
  
  inline def GPUTextureView(label: String): typingsJapgolly.webgpuTypes.GPUTextureView = {
    val __obj = js.Dynamic.literal(__brand = "GPUTextureView", label = label.asInstanceOf[js.Any])
    __obj.asInstanceOf[typingsJapgolly.webgpuTypes.GPUTextureView]
  }
}
