package typingsJapgolly.breeze.global.breeze

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSGlobal("breeze.AutoGeneratedKeyType")
@js.native
open class AutoGeneratedKeyType ()
  extends StObject
     with typingsJapgolly.breeze.breeze.AutoGeneratedKeyType
/* static members */
object AutoGeneratedKeyType {
  
  @JSGlobal("breeze.AutoGeneratedKeyType")
  @js.native
  val ^ : js.Any = js.native
  
  @JSGlobal("breeze.AutoGeneratedKeyType.Identity")
  @js.native
  def Identity: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
  inline def Identity_=(x: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("Identity")(x.asInstanceOf[js.Any])
  
  @JSGlobal("breeze.AutoGeneratedKeyType.KeyGenerator")
  @js.native
  def KeyGenerator: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
  inline def KeyGenerator_=(x: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("KeyGenerator")(x.asInstanceOf[js.Any])
  
  @JSGlobal("breeze.AutoGeneratedKeyType.None")
  @js.native
  def None: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
  inline def None_=(x: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("None")(x.asInstanceOf[js.Any])
}
