package typingsJapgolly.vscodeLanguageserverProtocol

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object protocolMod {
  type ClientCapabilities = typingsJapgolly.vscodeLanguageserverProtocol.protocolMod._ClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolImplementationMod.ImplementationClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolTypeDefinitionMod.TypeDefinitionClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolConfigurationMod.ConfigurationClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolColorProviderMod.ColorClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolFoldingRangeMod.FoldingRangeClientCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolDeclarationMod.DeclarationClientCapabilities
  type DocumentSelector = js.Array[
    java.lang.String | typingsJapgolly.vscodeLanguageserverProtocol.protocolMod.DocumentFilter
  ]
  type ExecuteCommandRegistrationOptions = typingsJapgolly.vscodeLanguageserverProtocol.protocolMod.ExecuteCommandOptions
  type InitializeParams = typingsJapgolly.vscodeLanguageserverProtocol.protocolMod._InitializeParams with typingsJapgolly.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersInitializeParams
  type ServerCapabilities = typingsJapgolly.vscodeLanguageserverProtocol.protocolMod._ServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolImplementationMod.ImplementationServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolTypeDefinitionMod.TypeDefinitionServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolColorProviderMod.ColorServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolFoldingRangeMod.FoldingRangeServerCapabilities with typingsJapgolly.vscodeLanguageserverProtocol.protocolDeclarationMod.DeclarationServerCapabilities
}
