package typingsJapgolly.semanticUiSearch.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object SearchSettings {
  type Param = (typingsJapgolly.semanticUiSearch.PickImplapiSettings | typingsJapgolly.semanticUiSearch.PickImpltype | typingsJapgolly.semanticUiSearch.PickImplminCharacters | typingsJapgolly.semanticUiSearch.PickImpltransition | typingsJapgolly.semanticUiSearch.PickImplduration | typingsJapgolly.semanticUiSearch.PickImplmaxResults | typingsJapgolly.semanticUiSearch.PickImplcache | typingsJapgolly.semanticUiSearch.PickImplsource | typingsJapgolly.semanticUiSearch.PickImplselectFirstResult | typingsJapgolly.semanticUiSearch.PickImplshowNoResults | typingsJapgolly.semanticUiSearch.PickImplsearchFullText | typingsJapgolly.semanticUiSearch.PickImplfields | typingsJapgolly.semanticUiSearch.PickImplsearchFields | typingsJapgolly.semanticUiSearch.PickImplhideDelay | typingsJapgolly.semanticUiSearch.PickImplsearchDelay | typingsJapgolly.semanticUiSearch.PickImpleasing | typingsJapgolly.semanticUiSearch.PickImplonSelect | typingsJapgolly.semanticUiSearch.PickImplonResultsAdd | typingsJapgolly.semanticUiSearch.PickImplonSearchQuery | typingsJapgolly.semanticUiSearch.PickImplonResults | typingsJapgolly.semanticUiSearch.PickImplonResultsOpen | typingsJapgolly.semanticUiSearch.PickImplonResultsClose | typingsJapgolly.semanticUiSearch.PickImpltemplates | typingsJapgolly.semanticUiSearch.PickImplregExp | typingsJapgolly.semanticUiSearch.PickImplselector | typingsJapgolly.semanticUiSearch.PickImplmetadata | typingsJapgolly.semanticUiSearch.PickImplclassName | typingsJapgolly.semanticUiSearch.PickImplerror | typingsJapgolly.semanticUiSearch.PickImplnamespace | typingsJapgolly.semanticUiSearch.PickImplname | typingsJapgolly.semanticUiSearch.PickImplsilent | typingsJapgolly.semanticUiSearch.PickImpldebug | typingsJapgolly.semanticUiSearch.PickImplperformance | typingsJapgolly.semanticUiSearch.PickImplverbose) with typingsJapgolly.semanticUiSearch.PartialPickImplkeyofImpl
}
