package typingsJapgolly.reactDashNativeDashVectorDashIcons.components

import typingsJapgolly.reactDashNativeDashVectorDashIcons.materialCommunityIconsMod.default.ToolbarAndroid
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

object MaterialCommunityIconsToolbarAndroid extends SharedApply_typingsJapgollyreactDashNativeDashVectorDashIconsiconModToolbarAndroidProps1373982361[ToolbarAndroid] {
  override val __component: js.Any = js.constructorOf[typingsJapgolly.reactDashNativeDashVectorDashIcons.materialCommunityIconsMod.default.ToolbarAndroid]
}

