package typingsJapgolly.qunitDom

import org.scalajs.dom.raw.Element
import org.scalajs.dom.raw.Node
import typingsJapgolly.std.HTMLAnchorElement
import typingsJapgolly.std.HTMLAppletElement
import typingsJapgolly.std.HTMLAreaElement
import typingsJapgolly.std.HTMLAudioElement
import typingsJapgolly.std.HTMLBRElement
import typingsJapgolly.std.HTMLBaseElement
import typingsJapgolly.std.HTMLBaseFontElement
import typingsJapgolly.std.HTMLBodyElement
import typingsJapgolly.std.HTMLButtonElement
import typingsJapgolly.std.HTMLCanvasElement
import typingsJapgolly.std.HTMLDListElement
import typingsJapgolly.std.HTMLDataElement
import typingsJapgolly.std.HTMLDataListElement
import typingsJapgolly.std.HTMLDetailsElement
import typingsJapgolly.std.HTMLDialogElement
import typingsJapgolly.std.HTMLDirectoryElement
import typingsJapgolly.std.HTMLDivElement
import typingsJapgolly.std.HTMLElement
import typingsJapgolly.std.HTMLEmbedElement
import typingsJapgolly.std.HTMLFieldSetElement
import typingsJapgolly.std.HTMLFontElement
import typingsJapgolly.std.HTMLFormElement
import typingsJapgolly.std.HTMLFrameElement
import typingsJapgolly.std.HTMLFrameSetElement
import typingsJapgolly.std.HTMLHRElement
import typingsJapgolly.std.HTMLHeadElement
import typingsJapgolly.std.HTMLHeadingElement
import typingsJapgolly.std.HTMLHtmlElement
import typingsJapgolly.std.HTMLIFrameElement
import typingsJapgolly.std.HTMLImageElement
import typingsJapgolly.std.HTMLInputElement
import typingsJapgolly.std.HTMLLIElement
import typingsJapgolly.std.HTMLLabelElement
import typingsJapgolly.std.HTMLLegendElement
import typingsJapgolly.std.HTMLLinkElement
import typingsJapgolly.std.HTMLMapElement
import typingsJapgolly.std.HTMLMarqueeElement
import typingsJapgolly.std.HTMLMenuElement
import typingsJapgolly.std.HTMLMetaElement
import typingsJapgolly.std.HTMLMeterElement
import typingsJapgolly.std.HTMLModElement
import typingsJapgolly.std.HTMLOListElement
import typingsJapgolly.std.HTMLObjectElement
import typingsJapgolly.std.HTMLOptGroupElement
import typingsJapgolly.std.HTMLOptionElement
import typingsJapgolly.std.HTMLOutputElement
import typingsJapgolly.std.HTMLParagraphElement
import typingsJapgolly.std.HTMLParamElement
import typingsJapgolly.std.HTMLPictureElement
import typingsJapgolly.std.HTMLPreElement
import typingsJapgolly.std.HTMLProgressElement
import typingsJapgolly.std.HTMLQuoteElement
import typingsJapgolly.std.HTMLScriptElement
import typingsJapgolly.std.HTMLSelectElement
import typingsJapgolly.std.HTMLSlotElement
import typingsJapgolly.std.HTMLSourceElement
import typingsJapgolly.std.HTMLSpanElement
import typingsJapgolly.std.HTMLStyleElement
import typingsJapgolly.std.HTMLTableCaptionElement
import typingsJapgolly.std.HTMLTableColElement
import typingsJapgolly.std.HTMLTableDataCellElement
import typingsJapgolly.std.HTMLTableElement
import typingsJapgolly.std.HTMLTableHeaderCellElement
import typingsJapgolly.std.HTMLTableRowElement
import typingsJapgolly.std.HTMLTableSectionElement
import typingsJapgolly.std.HTMLTemplateElement
import typingsJapgolly.std.HTMLTextAreaElement
import typingsJapgolly.std.HTMLTimeElement
import typingsJapgolly.std.HTMLTitleElement
import typingsJapgolly.std.HTMLTrackElement
import typingsJapgolly.std.HTMLUListElement
import typingsJapgolly.std.HTMLVideoElement
import typingsJapgolly.std.NodeList
import typingsJapgolly.std.NodeListOf
import typingsJapgolly.std.SVGAElement
import typingsJapgolly.std.SVGCircleElement
import typingsJapgolly.std.SVGClipPathElement
import typingsJapgolly.std.SVGDefsElement
import typingsJapgolly.std.SVGDescElement
import typingsJapgolly.std.SVGEllipseElement
import typingsJapgolly.std.SVGFEBlendElement
import typingsJapgolly.std.SVGFEColorMatrixElement
import typingsJapgolly.std.SVGFEComponentTransferElement
import typingsJapgolly.std.SVGFECompositeElement
import typingsJapgolly.std.SVGFEConvolveMatrixElement
import typingsJapgolly.std.SVGFEDiffuseLightingElement
import typingsJapgolly.std.SVGFEDisplacementMapElement
import typingsJapgolly.std.SVGFEDistantLightElement
import typingsJapgolly.std.SVGFEFloodElement
import typingsJapgolly.std.SVGFEFuncAElement
import typingsJapgolly.std.SVGFEFuncBElement
import typingsJapgolly.std.SVGFEFuncGElement
import typingsJapgolly.std.SVGFEFuncRElement
import typingsJapgolly.std.SVGFEGaussianBlurElement
import typingsJapgolly.std.SVGFEImageElement
import typingsJapgolly.std.SVGFEMergeElement
import typingsJapgolly.std.SVGFEMergeNodeElement
import typingsJapgolly.std.SVGFEMorphologyElement
import typingsJapgolly.std.SVGFEOffsetElement
import typingsJapgolly.std.SVGFEPointLightElement
import typingsJapgolly.std.SVGFESpecularLightingElement
import typingsJapgolly.std.SVGFESpotLightElement
import typingsJapgolly.std.SVGFETileElement
import typingsJapgolly.std.SVGFETurbulenceElement
import typingsJapgolly.std.SVGFilterElement
import typingsJapgolly.std.SVGForeignObjectElement
import typingsJapgolly.std.SVGGElement
import typingsJapgolly.std.SVGImageElement
import typingsJapgolly.std.SVGLineElement
import typingsJapgolly.std.SVGLinearGradientElement
import typingsJapgolly.std.SVGMarkerElement
import typingsJapgolly.std.SVGMaskElement
import typingsJapgolly.std.SVGMetadataElement
import typingsJapgolly.std.SVGPathElement
import typingsJapgolly.std.SVGPatternElement
import typingsJapgolly.std.SVGPolygonElement
import typingsJapgolly.std.SVGPolylineElement
import typingsJapgolly.std.SVGRadialGradientElement
import typingsJapgolly.std.SVGRectElement
import typingsJapgolly.std.SVGSVGElement
import typingsJapgolly.std.SVGScriptElement
import typingsJapgolly.std.SVGStopElement
import typingsJapgolly.std.SVGStyleElement
import typingsJapgolly.std.SVGSwitchElement
import typingsJapgolly.std.SVGSymbolElement
import typingsJapgolly.std.SVGTSpanElement
import typingsJapgolly.std.SVGTextElement
import typingsJapgolly.std.SVGTextPathElement
import typingsJapgolly.std.SVGTitleElement
import typingsJapgolly.std.SVGUseElement
import typingsJapgolly.std.SVGViewElement
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("qunit-dom/dist/helpers/node-list", JSImport.Namespace)
@js.native
object nodeListMod extends js.Object {
  def toArray(list: NodeList): js.Array[Node] = js.native
  def toArray(
    selectors: NodeListOf[
      HTMLAnchorElement | HTMLAppletElement | HTMLAreaElement | HTMLAudioElement | HTMLBRElement | HTMLBaseElement | HTMLBaseFontElement | HTMLBodyElement | HTMLButtonElement | HTMLCanvasElement | HTMLDListElement | HTMLDataElement | HTMLDataListElement | HTMLDetailsElement | HTMLDialogElement | HTMLDirectoryElement | HTMLDivElement | HTMLElement | HTMLEmbedElement | HTMLFieldSetElement | HTMLFontElement | HTMLFormElement | HTMLFrameElement | HTMLFrameSetElement | HTMLHRElement | HTMLHeadElement | HTMLHeadingElement | HTMLHtmlElement | HTMLIFrameElement | HTMLImageElement | HTMLInputElement | HTMLLIElement | HTMLLabelElement | HTMLLegendElement | HTMLLinkElement | HTMLMapElement | HTMLMarqueeElement | HTMLMenuElement | HTMLMetaElement | HTMLMeterElement | HTMLModElement | HTMLOListElement | HTMLObjectElement | HTMLOptGroupElement | HTMLOptionElement | HTMLOutputElement | HTMLParagraphElement | HTMLParamElement | HTMLPictureElement | HTMLPreElement | HTMLProgressElement | HTMLQuoteElement | HTMLScriptElement | HTMLSelectElement | HTMLSlotElement | HTMLSourceElement | HTMLSpanElement | HTMLStyleElement | HTMLTableCaptionElement | HTMLTableColElement | HTMLTableDataCellElement | HTMLTableElement | HTMLTableHeaderCellElement | HTMLTableRowElement | HTMLTableSectionElement | HTMLTemplateElement | HTMLTextAreaElement | HTMLTimeElement | HTMLTitleElement | HTMLTrackElement | HTMLUListElement | HTMLVideoElement | SVGAElement | SVGCircleElement | SVGClipPathElement | SVGDefsElement | SVGDescElement | SVGEllipseElement | SVGFEBlendElement | SVGFEColorMatrixElement | SVGFEComponentTransferElement | SVGFECompositeElement | SVGFEConvolveMatrixElement | SVGFEDiffuseLightingElement | SVGFEDisplacementMapElement | SVGFEDistantLightElement | SVGFEFloodElement | SVGFEFuncAElement | SVGFEFuncBElement | SVGFEFuncGElement | SVGFEFuncRElement | SVGFEGaussianBlurElement | SVGFEImageElement | SVGFEMergeElement | SVGFEMergeNodeElement | SVGFEMorphologyElement | SVGFEOffsetElement | SVGFEPointLightElement | SVGFESpecularLightingElement | SVGFESpotLightElement | SVGFETileElement | SVGFETurbulenceElement | SVGFilterElement | SVGForeignObjectElement | SVGGElement | SVGImageElement | SVGLineElement | SVGLinearGradientElement | SVGMarkerElement | SVGMaskElement | SVGMetadataElement | SVGPathElement | SVGPatternElement | SVGPolygonElement | SVGPolylineElement | SVGRadialGradientElement | SVGRectElement | SVGSVGElement | SVGScriptElement | SVGStopElement | SVGStyleElement | SVGSwitchElement | SVGSymbolElement | SVGTSpanElement | SVGTextElement | SVGTextPathElement | SVGTitleElement | SVGUseElement | SVGViewElement
    ]
  ): js.Array[org.scalajs.dom.raw.HTMLAnchorElement] = js.native
  @JSName("toArray")
  def toArray_E_Element[E /* <: Element */](selectors: org.scalajs.dom.raw.NodeListOf[E with Node]): js.Array[E] = js.native
}

