package typingsJapgolly.gitlab.mod

import typingsJapgolly.gitlab.anon.TypeofAPIServices
import typingsJapgolly.gitlab.distTypesCoreInfrastructureUtilsMod.Bundle
import typingsJapgolly.gitlab.mod.^
import typingsJapgolly.std.InstanceType
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


inline def Gitlab: Bundle[
TypeofAPIServices, 
/* import warning: LimitUnionLength.leaveTypeRef Was union type with length 90, starting with typingsJapgolly.gitlab.gitlabStrings.Groups, typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests, typingsJapgolly.gitlab.gitlabStrings.GroupBadges */ Any] = ^.asInstanceOf[js.Dynamic].selectDynamic("Gitlab").asInstanceOf[Bundle[
TypeofAPIServices, 
/* import warning: LimitUnionLength.leaveTypeRef Was union type with length 90, starting with typingsJapgolly.gitlab.gitlabStrings.Groups, typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests, typingsJapgolly.gitlab.gitlabStrings.GroupBadges */ Any]]
type Gitlab = InstanceType[
Bundle[
  /* import warning: importer.ImportType#apply Failed type conversion: typeof APIServices */ js.Any, 
  /* import warning: LimitUnionLength.leaveTypeRef Was union type with length 90, starting with typingsJapgolly.gitlab.gitlabStrings.Groups, typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests, typingsJapgolly.gitlab.gitlabStrings.GroupBadges */ Any
]]

inline def GroupsBundle: Bundle[
typingsJapgolly.gitlab.anon.EpicDiscussions, 
typingsJapgolly.gitlab.gitlabStrings.Groups | typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests | typingsJapgolly.gitlab.gitlabStrings.GroupBadges | typingsJapgolly.gitlab.gitlabStrings.GroupCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.GroupIssueBoards | typingsJapgolly.gitlab.gitlabStrings.GroupMembers | typingsJapgolly.gitlab.gitlabStrings.GroupMilestones | typingsJapgolly.gitlab.gitlabStrings.GroupProjects | typingsJapgolly.gitlab.gitlabStrings.GroupVariables | typingsJapgolly.gitlab.gitlabStrings.GroupLabels | typingsJapgolly.gitlab.gitlabStrings.Epics | typingsJapgolly.gitlab.gitlabStrings.EpicIssues | typingsJapgolly.gitlab.gitlabStrings.EpicNotes | typingsJapgolly.gitlab.gitlabStrings.EpicDiscussions] = ^.asInstanceOf[js.Dynamic].selectDynamic("GroupsBundle").asInstanceOf[Bundle[
typingsJapgolly.gitlab.anon.EpicDiscussions, 
typingsJapgolly.gitlab.gitlabStrings.Groups | typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests | typingsJapgolly.gitlab.gitlabStrings.GroupBadges | typingsJapgolly.gitlab.gitlabStrings.GroupCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.GroupIssueBoards | typingsJapgolly.gitlab.gitlabStrings.GroupMembers | typingsJapgolly.gitlab.gitlabStrings.GroupMilestones | typingsJapgolly.gitlab.gitlabStrings.GroupProjects | typingsJapgolly.gitlab.gitlabStrings.GroupVariables | typingsJapgolly.gitlab.gitlabStrings.GroupLabels | typingsJapgolly.gitlab.gitlabStrings.Epics | typingsJapgolly.gitlab.gitlabStrings.EpicIssues | typingsJapgolly.gitlab.gitlabStrings.EpicNotes | typingsJapgolly.gitlab.gitlabStrings.EpicDiscussions]]
type GroupsBundle = InstanceType[
Bundle[
  typingsJapgolly.gitlab.anon.EpicIssues, 
  typingsJapgolly.gitlab.gitlabStrings.Groups | typingsJapgolly.gitlab.gitlabStrings.GroupAccessRequests | typingsJapgolly.gitlab.gitlabStrings.GroupBadges | typingsJapgolly.gitlab.gitlabStrings.GroupCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.GroupIssueBoards | typingsJapgolly.gitlab.gitlabStrings.GroupMembers | typingsJapgolly.gitlab.gitlabStrings.GroupMilestones | typingsJapgolly.gitlab.gitlabStrings.GroupProjects | typingsJapgolly.gitlab.gitlabStrings.GroupVariables | typingsJapgolly.gitlab.gitlabStrings.GroupLabels | typingsJapgolly.gitlab.gitlabStrings.Epics | typingsJapgolly.gitlab.gitlabStrings.EpicIssues | typingsJapgolly.gitlab.gitlabStrings.EpicNotes | typingsJapgolly.gitlab.gitlabStrings.EpicDiscussions
]]

inline def ProjectsBundle: Bundle[
typingsJapgolly.gitlab.anon.Branches, 
typingsJapgolly.gitlab.gitlabStrings.Branches | typingsJapgolly.gitlab.gitlabStrings.Commits | typingsJapgolly.gitlab.gitlabStrings.CommitDiscussions | typingsJapgolly.gitlab.gitlabStrings.ContainerRegistry | typingsJapgolly.gitlab.gitlabStrings.DeployKeys | typingsJapgolly.gitlab.gitlabStrings.Deployments | typingsJapgolly.gitlab.gitlabStrings.Environments | typingsJapgolly.gitlab.gitlabStrings.Issues | typingsJapgolly.gitlab.gitlabStrings.IssuesStatistics | typingsJapgolly.gitlab.gitlabStrings.IssueAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.IssueNotes | typingsJapgolly.gitlab.gitlabStrings.IssueDiscussions | typingsJapgolly.gitlab.gitlabStrings.Jobs | typingsJapgolly.gitlab.gitlabStrings.Labels | typingsJapgolly.gitlab.gitlabStrings.MergeRequests | typingsJapgolly.gitlab.gitlabStrings.MergeRequestAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.MergeRequestDiscussions | typingsJapgolly.gitlab.gitlabStrings.MergeRequestNotes | typingsJapgolly.gitlab.gitlabStrings.Packages | typingsJapgolly.gitlab.gitlabStrings.Pipelines | typingsJapgolly.gitlab.gitlabStrings.PipelineSchedules | typingsJapgolly.gitlab.gitlabStrings.PipelineScheduleVariables | typingsJapgolly.gitlab.gitlabStrings.Projects | typingsJapgolly.gitlab.gitlabStrings.ProjectAccessRequests | typingsJapgolly.gitlab.gitlabStrings.ProjectBadges | typingsJapgolly.gitlab.gitlabStrings.ProjectCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.ProjectImportExport | typingsJapgolly.gitlab.gitlabStrings.ProjectIssueBoards | typingsJapgolly.gitlab.gitlabStrings.ProjectHooks | typingsJapgolly.gitlab.gitlabStrings.ProjectMembers | typingsJapgolly.gitlab.gitlabStrings.ProjectMilestones | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippets | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetNotes | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetDiscussions | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.ProtectedBranches | typingsJapgolly.gitlab.gitlabStrings.ProtectedTags | typingsJapgolly.gitlab.gitlabStrings.ProjectVariables | typingsJapgolly.gitlab.gitlabStrings.PushRules | typingsJapgolly.gitlab.gitlabStrings.Releases | typingsJapgolly.gitlab.gitlabStrings.ReleaseLinks | typingsJapgolly.gitlab.gitlabStrings.Repositories | typingsJapgolly.gitlab.gitlabStrings.RepositoryFiles | typingsJapgolly.gitlab.gitlabStrings.Runners | typingsJapgolly.gitlab.gitlabStrings.Services | typingsJapgolly.gitlab.gitlabStrings.Tags | typingsJapgolly.gitlab.gitlabStrings.Triggers | typingsJapgolly.gitlab.gitlabStrings.VulnerabilityFindings] = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsBundle").asInstanceOf[Bundle[
typingsJapgolly.gitlab.anon.Branches, 
typingsJapgolly.gitlab.gitlabStrings.Branches | typingsJapgolly.gitlab.gitlabStrings.Commits | typingsJapgolly.gitlab.gitlabStrings.CommitDiscussions | typingsJapgolly.gitlab.gitlabStrings.ContainerRegistry | typingsJapgolly.gitlab.gitlabStrings.DeployKeys | typingsJapgolly.gitlab.gitlabStrings.Deployments | typingsJapgolly.gitlab.gitlabStrings.Environments | typingsJapgolly.gitlab.gitlabStrings.Issues | typingsJapgolly.gitlab.gitlabStrings.IssuesStatistics | typingsJapgolly.gitlab.gitlabStrings.IssueAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.IssueNotes | typingsJapgolly.gitlab.gitlabStrings.IssueDiscussions | typingsJapgolly.gitlab.gitlabStrings.Jobs | typingsJapgolly.gitlab.gitlabStrings.Labels | typingsJapgolly.gitlab.gitlabStrings.MergeRequests | typingsJapgolly.gitlab.gitlabStrings.MergeRequestAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.MergeRequestDiscussions | typingsJapgolly.gitlab.gitlabStrings.MergeRequestNotes | typingsJapgolly.gitlab.gitlabStrings.Packages | typingsJapgolly.gitlab.gitlabStrings.Pipelines | typingsJapgolly.gitlab.gitlabStrings.PipelineSchedules | typingsJapgolly.gitlab.gitlabStrings.PipelineScheduleVariables | typingsJapgolly.gitlab.gitlabStrings.Projects | typingsJapgolly.gitlab.gitlabStrings.ProjectAccessRequests | typingsJapgolly.gitlab.gitlabStrings.ProjectBadges | typingsJapgolly.gitlab.gitlabStrings.ProjectCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.ProjectImportExport | typingsJapgolly.gitlab.gitlabStrings.ProjectIssueBoards | typingsJapgolly.gitlab.gitlabStrings.ProjectHooks | typingsJapgolly.gitlab.gitlabStrings.ProjectMembers | typingsJapgolly.gitlab.gitlabStrings.ProjectMilestones | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippets | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetNotes | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetDiscussions | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.ProtectedBranches | typingsJapgolly.gitlab.gitlabStrings.ProtectedTags | typingsJapgolly.gitlab.gitlabStrings.ProjectVariables | typingsJapgolly.gitlab.gitlabStrings.PushRules | typingsJapgolly.gitlab.gitlabStrings.Releases | typingsJapgolly.gitlab.gitlabStrings.ReleaseLinks | typingsJapgolly.gitlab.gitlabStrings.Repositories | typingsJapgolly.gitlab.gitlabStrings.RepositoryFiles | typingsJapgolly.gitlab.gitlabStrings.Runners | typingsJapgolly.gitlab.gitlabStrings.Services | typingsJapgolly.gitlab.gitlabStrings.Tags | typingsJapgolly.gitlab.gitlabStrings.Triggers | typingsJapgolly.gitlab.gitlabStrings.VulnerabilityFindings]]
type ProjectsBundle = InstanceType[
Bundle[
  typingsJapgolly.gitlab.anon.CommitDiscussions, 
  typingsJapgolly.gitlab.gitlabStrings.Branches | typingsJapgolly.gitlab.gitlabStrings.Commits | typingsJapgolly.gitlab.gitlabStrings.CommitDiscussions | typingsJapgolly.gitlab.gitlabStrings.ContainerRegistry | typingsJapgolly.gitlab.gitlabStrings.DeployKeys | typingsJapgolly.gitlab.gitlabStrings.Deployments | typingsJapgolly.gitlab.gitlabStrings.Environments | typingsJapgolly.gitlab.gitlabStrings.Issues | typingsJapgolly.gitlab.gitlabStrings.IssuesStatistics | typingsJapgolly.gitlab.gitlabStrings.IssueAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.IssueNotes | typingsJapgolly.gitlab.gitlabStrings.IssueDiscussions | typingsJapgolly.gitlab.gitlabStrings.Jobs | typingsJapgolly.gitlab.gitlabStrings.Labels | typingsJapgolly.gitlab.gitlabStrings.MergeRequests | typingsJapgolly.gitlab.gitlabStrings.MergeRequestAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.MergeRequestDiscussions | typingsJapgolly.gitlab.gitlabStrings.MergeRequestNotes | typingsJapgolly.gitlab.gitlabStrings.Packages | typingsJapgolly.gitlab.gitlabStrings.Pipelines | typingsJapgolly.gitlab.gitlabStrings.PipelineSchedules | typingsJapgolly.gitlab.gitlabStrings.PipelineScheduleVariables | typingsJapgolly.gitlab.gitlabStrings.Projects | typingsJapgolly.gitlab.gitlabStrings.ProjectAccessRequests | typingsJapgolly.gitlab.gitlabStrings.ProjectBadges | typingsJapgolly.gitlab.gitlabStrings.ProjectCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.ProjectImportExport | typingsJapgolly.gitlab.gitlabStrings.ProjectIssueBoards | typingsJapgolly.gitlab.gitlabStrings.ProjectHooks | typingsJapgolly.gitlab.gitlabStrings.ProjectMembers | typingsJapgolly.gitlab.gitlabStrings.ProjectMilestones | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippets | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetNotes | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetDiscussions | typingsJapgolly.gitlab.gitlabStrings.ProjectSnippetAwardEmojis | typingsJapgolly.gitlab.gitlabStrings.ProtectedBranches | typingsJapgolly.gitlab.gitlabStrings.ProtectedTags | typingsJapgolly.gitlab.gitlabStrings.ProjectVariables | typingsJapgolly.gitlab.gitlabStrings.PushRules | typingsJapgolly.gitlab.gitlabStrings.Releases | typingsJapgolly.gitlab.gitlabStrings.ReleaseLinks | typingsJapgolly.gitlab.gitlabStrings.Repositories | typingsJapgolly.gitlab.gitlabStrings.RepositoryFiles | typingsJapgolly.gitlab.gitlabStrings.Runners | typingsJapgolly.gitlab.gitlabStrings.Services | typingsJapgolly.gitlab.gitlabStrings.Tags | typingsJapgolly.gitlab.gitlabStrings.Triggers | typingsJapgolly.gitlab.gitlabStrings.VulnerabilityFindings
]]

inline def UsersBundle: Bundle[
typingsJapgolly.gitlab.anon.UserCustomAttributes, 
typingsJapgolly.gitlab.gitlabStrings.Users | typingsJapgolly.gitlab.gitlabStrings.UserCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.UserEmails | typingsJapgolly.gitlab.gitlabStrings.UserImpersonationTokens | typingsJapgolly.gitlab.gitlabStrings.UserKeys | typingsJapgolly.gitlab.gitlabStrings.UserGPGKeys] = ^.asInstanceOf[js.Dynamic].selectDynamic("UsersBundle").asInstanceOf[Bundle[
typingsJapgolly.gitlab.anon.UserCustomAttributes, 
typingsJapgolly.gitlab.gitlabStrings.Users | typingsJapgolly.gitlab.gitlabStrings.UserCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.UserEmails | typingsJapgolly.gitlab.gitlabStrings.UserImpersonationTokens | typingsJapgolly.gitlab.gitlabStrings.UserKeys | typingsJapgolly.gitlab.gitlabStrings.UserGPGKeys]]
type UsersBundle = InstanceType[
Bundle[
  typingsJapgolly.gitlab.anon.UserEmails, 
  typingsJapgolly.gitlab.gitlabStrings.Users | typingsJapgolly.gitlab.gitlabStrings.UserCustomAttributes | typingsJapgolly.gitlab.gitlabStrings.UserEmails | typingsJapgolly.gitlab.gitlabStrings.UserImpersonationTokens | typingsJapgolly.gitlab.gitlabStrings.UserKeys | typingsJapgolly.gitlab.gitlabStrings.UserGPGKeys
]]
