package typingsJapgolly.chromeApps.anon

import japgolly.scalajs.react.Callback
import typingsJapgolly.chromeApps.chrome.wallpaper.WallpaperDetails
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait Typeofwallpaper extends StObject {
  
  /**
    * Sets wallpaper to the image at url or wallpaperData with the specified layout
    * @param callback Contains the optional parameter thumbnail: The jpeg encoded wallpaper thumbnail. It is generated by resizing the wallpaper to 128x60.
    */
  def setWallpaper(details: WallpaperDetails, callback: js.Function1[/* thumbnail */ js.UndefOr[String], Unit]): Unit
}
object Typeofwallpaper {
  
  inline def apply(
    setWallpaper: (WallpaperDetails, js.Function1[/* thumbnail */ js.UndefOr[String], Unit]) => Callback
  ): Typeofwallpaper = {
    val __obj = js.Dynamic.literal(setWallpaper = js.Any.fromFunction2((t0: WallpaperDetails, t1: js.Function1[/* thumbnail */ js.UndefOr[String], Unit]) => (setWallpaper(t0, t1)).runNow()))
    __obj.asInstanceOf[Typeofwallpaper]
  }
  
  extension [Self <: Typeofwallpaper](x: Self) {
    
    inline def setSetWallpaper(value: (WallpaperDetails, js.Function1[/* thumbnail */ js.UndefOr[String], Unit]) => Callback): Self = StObject.set(x, "setWallpaper", js.Any.fromFunction2((t0: WallpaperDetails, t1: js.Function1[/* thumbnail */ js.UndefOr[String], Unit]) => (value(t0, t1)).runNow()))
  }
}
