package typingsJapgolly.chromeApps

import japgolly.scalajs.react.Callback
import typingsJapgolly.chromeApps.chrome.wallpaper.WallpaperDetails
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Typeofwallpaper extends js.Object {
  /**
    * Sets wallpaper to the image at url or wallpaperData with the specified layout
    * @param callback Contains the optional parameter thumbnail: The jpeg encoded wallpaper thumbnail. It is generated by resizing the wallpaper to 128x60.
    */
  def setWallpaper(details: WallpaperDetails, callback: js.Function1[/* thumbnail */ js.UndefOr[String], Unit]): Unit
}

object Typeofwallpaper {
  @scala.inline
  def apply(
    setWallpaper: (WallpaperDetails, js.Function1[/* thumbnail */ js.UndefOr[String], Unit]) => Callback
  ): Typeofwallpaper = {
    val __obj = js.Dynamic.literal()
    __obj.updateDynamic("setWallpaper")(js.Any.fromFunction2((t0: typingsJapgolly.chromeApps.chrome.wallpaper.WallpaperDetails, t1: js.Function1[/* thumbnail */ js.UndefOr[java.lang.String], scala.Unit]) => setWallpaper(t0, t1).runNow()))
    __obj.asInstanceOf[Typeofwallpaper]
  }
}

