package typingsJapgolly.arangodb.ArangoDB

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object ErrorName {
  
  inline def COMMUNICATOR_DISABLED: typingsJapgolly.arangodb.arangodbStrings.COMMUNICATOR_DISABLED = "COMMUNICATOR_DISABLED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.COMMUNICATOR_DISABLED]
  
  inline def COMMUNICATOR_REQUEST_ABORTED: typingsJapgolly.arangodb.arangodbStrings.COMMUNICATOR_REQUEST_ABORTED = "COMMUNICATOR_REQUEST_ABORTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.COMMUNICATOR_REQUEST_ABORTED]
  
  inline def ERROR_AGENCY_CANNOT_REBUILD_DBS: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_CANNOT_REBUILD_DBS = "ERROR_AGENCY_CANNOT_REBUILD_DBS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_CANNOT_REBUILD_DBS]
  
  inline def ERROR_AGENCY_INFORM_MUST_BE_OBJECT: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_BE_OBJECT = "ERROR_AGENCY_INFORM_MUST_BE_OBJECT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_BE_OBJECT]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_ACTIVE: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_ACTIVE = "ERROR_AGENCY_INFORM_MUST_CONTAIN_ACTIVE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_ACTIVE]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_ID: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_ID = "ERROR_AGENCY_INFORM_MUST_CONTAIN_ID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_ID]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_MAX_PING: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_MAX_PING = "ERROR_AGENCY_INFORM_MUST_CONTAIN_MAX_PING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_MAX_PING]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_MIN_PING: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_MIN_PING = "ERROR_AGENCY_INFORM_MUST_CONTAIN_MIN_PING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_MIN_PING]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_POOL: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_POOL = "ERROR_AGENCY_INFORM_MUST_CONTAIN_POOL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_POOL]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_TERM: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_TERM = "ERROR_AGENCY_INFORM_MUST_CONTAIN_TERM".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_TERM]
  
  inline def ERROR_AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT = "ERROR_AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT]
  
  inline def ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING = "ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING]
  
  inline def ERROR_AGENCY_INQUIRY_SYNTAX: typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INQUIRY_SYNTAX = "ERROR_AGENCY_INQUIRY_SYNTAX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_AGENCY_INQUIRY_SYNTAX]
  
  inline def ERROR_ARANGO_ATTRIBUTE_PARSER_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ATTRIBUTE_PARSER_FAILED = "ERROR_ARANGO_ATTRIBUTE_PARSER_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ATTRIBUTE_PARSER_FAILED]
  
  inline def ERROR_ARANGO_BUSY: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_BUSY = "ERROR_ARANGO_BUSY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_BUSY]
  
  inline def ERROR_ARANGO_COLLECTION_DIRECTORY_ALREADY_EXISTS: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_DIRECTORY_ALREADY_EXISTS = "ERROR_ARANGO_COLLECTION_DIRECTORY_ALREADY_EXISTS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_DIRECTORY_ALREADY_EXISTS]
  
  inline def ERROR_ARANGO_COLLECTION_NOT_LOADED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_NOT_LOADED = "ERROR_ARANGO_COLLECTION_NOT_LOADED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_NOT_LOADED]
  
  inline def ERROR_ARANGO_COLLECTION_NOT_UNLOADED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_NOT_UNLOADED = "ERROR_ARANGO_COLLECTION_NOT_UNLOADED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_NOT_UNLOADED]
  
  inline def ERROR_ARANGO_COLLECTION_PARAMETER_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_PARAMETER_MISSING = "ERROR_ARANGO_COLLECTION_PARAMETER_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_PARAMETER_MISSING]
  
  inline def ERROR_ARANGO_COLLECTION_TYPE_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_TYPE_INVALID = "ERROR_ARANGO_COLLECTION_TYPE_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_TYPE_INVALID]
  
  inline def ERROR_ARANGO_COLLECTION_TYPE_MISMATCH: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_TYPE_MISMATCH = "ERROR_ARANGO_COLLECTION_TYPE_MISMATCH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_COLLECTION_TYPE_MISMATCH]
  
  inline def ERROR_ARANGO_CONFLICT: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CONFLICT = "ERROR_ARANGO_CONFLICT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CONFLICT]
  
  inline def ERROR_ARANGO_CORRUPTED_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CORRUPTED_COLLECTION = "ERROR_ARANGO_CORRUPTED_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CORRUPTED_COLLECTION]
  
  inline def ERROR_ARANGO_CORRUPTED_DATAFILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CORRUPTED_DATAFILE = "ERROR_ARANGO_CORRUPTED_DATAFILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CORRUPTED_DATAFILE]
  
  inline def ERROR_ARANGO_CROSS_COLLECTION_REQUEST: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CROSS_COLLECTION_REQUEST = "ERROR_ARANGO_CROSS_COLLECTION_REQUEST".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_CROSS_COLLECTION_REQUEST]
  
  inline def ERROR_ARANGO_DATABASE_NAME_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATABASE_NAME_INVALID = "ERROR_ARANGO_DATABASE_NAME_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATABASE_NAME_INVALID]
  
  inline def ERROR_ARANGO_DATABASE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATABASE_NOT_FOUND = "ERROR_ARANGO_DATABASE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATABASE_NOT_FOUND]
  
  inline def ERROR_ARANGO_DATADIR_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_INVALID = "ERROR_ARANGO_DATADIR_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_INVALID]
  
  inline def ERROR_ARANGO_DATADIR_LOCKED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_LOCKED = "ERROR_ARANGO_DATADIR_LOCKED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_LOCKED]
  
  inline def ERROR_ARANGO_DATADIR_NOT_WRITABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_NOT_WRITABLE = "ERROR_ARANGO_DATADIR_NOT_WRITABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_NOT_WRITABLE]
  
  inline def ERROR_ARANGO_DATADIR_UNLOCKABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_UNLOCKABLE = "ERROR_ARANGO_DATADIR_UNLOCKABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATADIR_UNLOCKABLE]
  
  inline def ERROR_ARANGO_DATAFILE_ALREADY_EXISTS: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_ALREADY_EXISTS = "ERROR_ARANGO_DATAFILE_ALREADY_EXISTS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_ALREADY_EXISTS]
  
  inline def ERROR_ARANGO_DATAFILE_EMPTY: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_EMPTY = "ERROR_ARANGO_DATAFILE_EMPTY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_EMPTY]
  
  inline def ERROR_ARANGO_DATAFILE_FULL: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_FULL = "ERROR_ARANGO_DATAFILE_FULL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_FULL]
  
  inline def ERROR_ARANGO_DATAFILE_SEALED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_SEALED = "ERROR_ARANGO_DATAFILE_SEALED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_SEALED]
  
  inline def ERROR_ARANGO_DATAFILE_STATISTICS_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_STATISTICS_NOT_FOUND = "ERROR_ARANGO_DATAFILE_STATISTICS_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_STATISTICS_NOT_FOUND]
  
  inline def ERROR_ARANGO_DATAFILE_UNREADABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_UNREADABLE = "ERROR_ARANGO_DATAFILE_UNREADABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATAFILE_UNREADABLE]
  
  inline def ERROR_ARANGO_DATA_SOURCE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATA_SOURCE_NOT_FOUND = "ERROR_ARANGO_DATA_SOURCE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DATA_SOURCE_NOT_FOUND]
  
  inline def ERROR_ARANGO_DOCUMENT_HANDLE_BAD: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_HANDLE_BAD = "ERROR_ARANGO_DOCUMENT_HANDLE_BAD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_HANDLE_BAD]
  
  inline def ERROR_ARANGO_DOCUMENT_KEY_BAD: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_BAD = "ERROR_ARANGO_DOCUMENT_KEY_BAD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_BAD]
  
  inline def ERROR_ARANGO_DOCUMENT_KEY_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_MISSING = "ERROR_ARANGO_DOCUMENT_KEY_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_MISSING]
  
  inline def ERROR_ARANGO_DOCUMENT_KEY_UNEXPECTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_UNEXPECTED = "ERROR_ARANGO_DOCUMENT_KEY_UNEXPECTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_KEY_UNEXPECTED]
  
  inline def ERROR_ARANGO_DOCUMENT_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_NOT_FOUND = "ERROR_ARANGO_DOCUMENT_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_NOT_FOUND]
  
  inline def ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED: /* ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED */ String = "ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED".asInstanceOf[/* ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED */ String]
  
  inline def ERROR_ARANGO_DOCUMENT_REV_BAD: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_REV_BAD = "ERROR_ARANGO_DOCUMENT_REV_BAD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_REV_BAD]
  
  inline def ERROR_ARANGO_DOCUMENT_TOO_LARGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_TOO_LARGE = "ERROR_ARANGO_DOCUMENT_TOO_LARGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_TOO_LARGE]
  
  inline def ERROR_ARANGO_DOCUMENT_TYPE_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_TYPE_INVALID = "ERROR_ARANGO_DOCUMENT_TYPE_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DOCUMENT_TYPE_INVALID]
  
  inline def ERROR_ARANGO_DUPLICATE_IDENTIFIER: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DUPLICATE_IDENTIFIER = "ERROR_ARANGO_DUPLICATE_IDENTIFIER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DUPLICATE_IDENTIFIER]
  
  inline def ERROR_ARANGO_DUPLICATE_NAME: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DUPLICATE_NAME = "ERROR_ARANGO_DUPLICATE_NAME".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_DUPLICATE_NAME]
  
  inline def ERROR_ARANGO_EMPTY_DATADIR: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_EMPTY_DATADIR = "ERROR_ARANGO_EMPTY_DATADIR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_EMPTY_DATADIR]
  
  inline def ERROR_ARANGO_ENDPOINT_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ENDPOINT_NOT_FOUND = "ERROR_ARANGO_ENDPOINT_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ENDPOINT_NOT_FOUND]
  
  inline def ERROR_ARANGO_FILESYSTEM_FULL: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_FILESYSTEM_FULL = "ERROR_ARANGO_FILESYSTEM_FULL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_FILESYSTEM_FULL]
  
  inline def ERROR_ARANGO_ICU_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ICU_ERROR = "ERROR_ARANGO_ICU_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ICU_ERROR]
  
  inline def ERROR_ARANGO_ILLEGAL_NAME: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_NAME = "ERROR_ARANGO_ILLEGAL_NAME".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_NAME]
  
  inline def ERROR_ARANGO_ILLEGAL_PARAMETER_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_PARAMETER_FILE = "ERROR_ARANGO_ILLEGAL_PARAMETER_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_PARAMETER_FILE]
  
  inline def ERROR_ARANGO_ILLEGAL_STATE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_STATE = "ERROR_ARANGO_ILLEGAL_STATE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_ILLEGAL_STATE]
  
  inline def ERROR_ARANGO_INDEX_CREATION_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_CREATION_FAILED = "ERROR_ARANGO_INDEX_CREATION_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_CREATION_FAILED]
  
  inline def ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING = "ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING]
  
  inline def ERROR_ARANGO_INDEX_HANDLE_BAD: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_HANDLE_BAD = "ERROR_ARANGO_INDEX_HANDLE_BAD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_HANDLE_BAD]
  
  inline def ERROR_ARANGO_INDEX_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_NOT_FOUND = "ERROR_ARANGO_INDEX_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INDEX_NOT_FOUND]
  
  inline def ERROR_ARANGO_INVALID_EDGE_ATTRIBUTE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INVALID_EDGE_ATTRIBUTE = "ERROR_ARANGO_INVALID_EDGE_ATTRIBUTE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INVALID_EDGE_ATTRIBUTE]
  
  inline def ERROR_ARANGO_INVALID_KEY_GENERATOR: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INVALID_KEY_GENERATOR = "ERROR_ARANGO_INVALID_KEY_GENERATOR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_INVALID_KEY_GENERATOR]
  
  inline def ERROR_ARANGO_IO_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_IO_ERROR = "ERROR_ARANGO_IO_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_IO_ERROR]
  
  inline def ERROR_ARANGO_MAXIMAL_SIZE_TOO_SMALL: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MAXIMAL_SIZE_TOO_SMALL = "ERROR_ARANGO_MAXIMAL_SIZE_TOO_SMALL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MAXIMAL_SIZE_TOO_SMALL]
  
  inline def ERROR_ARANGO_MERGE_IN_PROGRESS: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MERGE_IN_PROGRESS = "ERROR_ARANGO_MERGE_IN_PROGRESS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MERGE_IN_PROGRESS]
  
  inline def ERROR_ARANGO_MMAP_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MMAP_FAILED = "ERROR_ARANGO_MMAP_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MMAP_FAILED]
  
  inline def ERROR_ARANGO_MSYNC_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MSYNC_FAILED = "ERROR_ARANGO_MSYNC_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_MSYNC_FAILED]
  
  inline def ERROR_ARANGO_NO_INDEX: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_NO_INDEX = "ERROR_ARANGO_NO_INDEX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_NO_INDEX]
  
  inline def ERROR_ARANGO_NO_JOURNAL: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_NO_JOURNAL = "ERROR_ARANGO_NO_JOURNAL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_NO_JOURNAL]
  
  inline def ERROR_ARANGO_OUT_OF_KEYS: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_OUT_OF_KEYS = "ERROR_ARANGO_OUT_OF_KEYS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_OUT_OF_KEYS]
  
  inline def ERROR_ARANGO_READ_ONLY: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_READ_ONLY = "ERROR_ARANGO_READ_ONLY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_READ_ONLY]
  
  inline def ERROR_ARANGO_RECOVERY: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_RECOVERY = "ERROR_ARANGO_RECOVERY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_RECOVERY]
  
  inline def ERROR_ARANGO_SYNC_TIMEOUT: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_SYNC_TIMEOUT = "ERROR_ARANGO_SYNC_TIMEOUT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_SYNC_TIMEOUT]
  
  inline def ERROR_ARANGO_TRY_AGAIN: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_TRY_AGAIN = "ERROR_ARANGO_TRY_AGAIN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_TRY_AGAIN]
  
  inline def ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED = "ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED]
  
  inline def ERROR_ARANGO_USE_SYSTEM_DATABASE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_USE_SYSTEM_DATABASE = "ERROR_ARANGO_USE_SYSTEM_DATABASE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_USE_SYSTEM_DATABASE]
  
  inline def ERROR_ARANGO_VALIDATION_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_VALIDATION_FAILED = "ERROR_ARANGO_VALIDATION_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_VALIDATION_FAILED]
  
  inline def ERROR_ARANGO_WRITE_THROTTLE_TIMEOUT: typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_WRITE_THROTTLE_TIMEOUT = "ERROR_ARANGO_WRITE_THROTTLE_TIMEOUT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ARANGO_WRITE_THROTTLE_TIMEOUT]
  
  inline def ERROR_BAD_PARAMETER: typingsJapgolly.arangodb.arangodbStrings.ERROR_BAD_PARAMETER = "ERROR_BAD_PARAMETER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_BAD_PARAMETER]
  
  inline def ERROR_CANNOT_CREATE_DIRECTORY: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_CREATE_DIRECTORY = "ERROR_CANNOT_CREATE_DIRECTORY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_CREATE_DIRECTORY]
  
  inline def ERROR_CANNOT_CREATE_TEMP_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_CREATE_TEMP_FILE = "ERROR_CANNOT_CREATE_TEMP_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_CREATE_TEMP_FILE]
  
  inline def ERROR_CANNOT_DROP_SMART_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_DROP_SMART_COLLECTION = "ERROR_CANNOT_DROP_SMART_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_DROP_SMART_COLLECTION]
  
  inline def ERROR_CANNOT_OVERWRITE_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_OVERWRITE_FILE = "ERROR_CANNOT_OVERWRITE_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_OVERWRITE_FILE]
  
  inline def ERROR_CANNOT_READ_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_READ_FILE = "ERROR_CANNOT_READ_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_READ_FILE]
  
  inline def ERROR_CANNOT_WRITE_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_WRITE_FILE = "ERROR_CANNOT_WRITE_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CANNOT_WRITE_FILE]
  
  inline def ERROR_CLUSTER_AGENCY_COMMUNICATION_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AGENCY_COMMUNICATION_FAILED = "ERROR_CLUSTER_AGENCY_COMMUNICATION_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AGENCY_COMMUNICATION_FAILED]
  
  inline def ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID = "ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID]
  
  inline def ERROR_CLUSTER_AQL_COLLECTION_OUT_OF_SYNC: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AQL_COLLECTION_OUT_OF_SYNC = "ERROR_CLUSTER_AQL_COLLECTION_OUT_OF_SYNC".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AQL_COLLECTION_OUT_OF_SYNC]
  
  inline def ERROR_CLUSTER_AQL_COMMUNICATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AQL_COMMUNICATION = "ERROR_CLUSTER_AQL_COMMUNICATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_AQL_COMMUNICATION]
  
  inline def ERROR_CLUSTER_BACKEND_UNAVAILABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_BACKEND_UNAVAILABLE = "ERROR_CLUSTER_BACKEND_UNAVAILABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_BACKEND_UNAVAILABLE]
  
  inline def ERROR_CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE = "ERROR_CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE]
  
  inline def ERROR_CLUSTER_COLLECTION_ID_EXISTS: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COLLECTION_ID_EXISTS = "ERROR_CLUSTER_COLLECTION_ID_EXISTS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COLLECTION_ID_EXISTS]
  
  inline def ERROR_CLUSTER_CONNECTION_LOST: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_CONNECTION_LOST = "ERROR_CLUSTER_CONNECTION_LOST".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_CONNECTION_LOST]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION = "ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE = "ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_DETERMINE_ID: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DETERMINE_ID = "ERROR_CLUSTER_COULD_NOT_DETERMINE_ID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DETERMINE_ID]
  
  inline def ERROR_CLUSTER_COULD_NOT_DROP_FOLLOWER: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DROP_FOLLOWER = "ERROR_CLUSTER_COULD_NOT_DROP_FOLLOWER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DROP_FOLLOWER]
  
  inline def ERROR_CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_LOCK_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_LOCK_PLAN = "ERROR_CLUSTER_COULD_NOT_LOCK_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_LOCK_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION = "ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION]
  
  inline def ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_CURRENT: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_CURRENT = "ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_CURRENT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_CURRENT]
  
  inline def ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT = "ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT]
  
  inline def ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN = "ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN]
  
  inline def ERROR_CLUSTER_COULD_NOT_TRUNCATE_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_TRUNCATE_COLLECTION = "ERROR_CLUSTER_COULD_NOT_TRUNCATE_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_COULD_NOT_TRUNCATE_COLLECTION]
  
  inline def ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS = "ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS]
  
  inline def ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR = "ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR]
  
  inline def ERROR_CLUSTER_GOT_CONTRADICTING_ANSWERS: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_GOT_CONTRADICTING_ANSWERS = "ERROR_CLUSTER_GOT_CONTRADICTING_ANSWERS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_GOT_CONTRADICTING_ANSWERS]
  
  inline def ERROR_CLUSTER_INSUFFICIENT_DBSERVERS: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_INSUFFICIENT_DBSERVERS = "ERROR_CLUSTER_INSUFFICIENT_DBSERVERS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_INSUFFICIENT_DBSERVERS]
  
  inline def ERROR_CLUSTER_LEADERSHIP_CHALLENGE_ONGOING: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_LEADERSHIP_CHALLENGE_ONGOING = "ERROR_CLUSTER_LEADERSHIP_CHALLENGE_ONGOING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_LEADERSHIP_CHALLENGE_ONGOING]
  
  inline def ERROR_CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES = "ERROR_CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES]
  
  inline def ERROR_CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE = "ERROR_CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE]
  
  inline def ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY = "ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY]
  
  inline def ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN = "ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN]
  
  inline def ERROR_CLUSTER_NOT_LEADER: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NOT_LEADER = "ERROR_CLUSTER_NOT_LEADER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NOT_LEADER]
  
  inline def ERROR_CLUSTER_NO_AGENCY: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NO_AGENCY = "ERROR_CLUSTER_NO_AGENCY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NO_AGENCY]
  
  inline def ERROR_CLUSTER_NO_COORDINATOR_HEADER: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NO_COORDINATOR_HEADER = "ERROR_CLUSTER_NO_COORDINATOR_HEADER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_NO_COORDINATOR_HEADER]
  
  inline def ERROR_CLUSTER_ONLY_ON_COORDINATOR: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_ONLY_ON_COORDINATOR = "ERROR_CLUSTER_ONLY_ON_COORDINATOR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_ONLY_ON_COORDINATOR]
  
  inline def ERROR_CLUSTER_ONLY_ON_DBSERVER: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_ONLY_ON_DBSERVER = "ERROR_CLUSTER_ONLY_ON_DBSERVER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_ONLY_ON_DBSERVER]
  
  inline def ERROR_CLUSTER_READING_PLAN_AGENCY: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_READING_PLAN_AGENCY = "ERROR_CLUSTER_READING_PLAN_AGENCY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_READING_PLAN_AGENCY]
  
  inline def ERROR_CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION = "ERROR_CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION]
  
  inline def ERROR_CLUSTER_SHARD_GONE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_GONE = "ERROR_CLUSTER_SHARD_GONE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_GONE]
  
  inline def ERROR_CLUSTER_SHARD_LEADER_REFUSES_REPLICATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_LEADER_REFUSES_REPLICATION = "ERROR_CLUSTER_SHARD_LEADER_REFUSES_REPLICATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_LEADER_REFUSES_REPLICATION]
  
  inline def ERROR_CLUSTER_SHARD_LEADER_RESIGNED: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_LEADER_RESIGNED = "ERROR_CLUSTER_SHARD_LEADER_RESIGNED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_SHARD_LEADER_RESIGNED]
  
  inline def ERROR_CLUSTER_TIMEOUT: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_TIMEOUT = "ERROR_CLUSTER_TIMEOUT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_TIMEOUT]
  
  inline def ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT = "ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT]
  
  inline def ERROR_CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE = "ERROR_CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE]
  
  inline def ERROR_CLUSTER_UNSUPPORTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNSUPPORTED = "ERROR_CLUSTER_UNSUPPORTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CLUSTER_UNSUPPORTED]
  
  inline def ERROR_CORRUPTED_CSV: typingsJapgolly.arangodb.arangodbStrings.ERROR_CORRUPTED_CSV = "ERROR_CORRUPTED_CSV".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CORRUPTED_CSV]
  
  inline def ERROR_CURSOR_BUSY: typingsJapgolly.arangodb.arangodbStrings.ERROR_CURSOR_BUSY = "ERROR_CURSOR_BUSY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CURSOR_BUSY]
  
  inline def ERROR_CURSOR_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_CURSOR_NOT_FOUND = "ERROR_CURSOR_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_CURSOR_NOT_FOUND]
  
  inline def ERROR_DEADLOCK: typingsJapgolly.arangodb.arangodbStrings.ERROR_DEADLOCK = "ERROR_DEADLOCK".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_DEADLOCK]
  
  inline def ERROR_DEAD_PID: typingsJapgolly.arangodb.arangodbStrings.ERROR_DEAD_PID = "ERROR_DEAD_PID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_DEAD_PID]
  
  inline def ERROR_DEBUG: typingsJapgolly.arangodb.arangodbStrings.ERROR_DEBUG = "ERROR_DEBUG".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_DEBUG]
  
  inline def ERROR_DISPATCHER_IS_STOPPING: typingsJapgolly.arangodb.arangodbStrings.ERROR_DISPATCHER_IS_STOPPING = "ERROR_DISPATCHER_IS_STOPPING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_DISPATCHER_IS_STOPPING]
  
  inline def ERROR_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_FAILED = "ERROR_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_FAILED]
  
  inline def ERROR_FILE_EXISTS: typingsJapgolly.arangodb.arangodbStrings.ERROR_FILE_EXISTS = "ERROR_FILE_EXISTS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_FILE_EXISTS]
  
  inline def ERROR_FILE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_FILE_NOT_FOUND = "ERROR_FILE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_FILE_NOT_FOUND]
  
  inline def ERROR_FORBIDDEN: typingsJapgolly.arangodb.arangodbStrings.ERROR_FORBIDDEN = "ERROR_FORBIDDEN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_FORBIDDEN]
  
  inline def ERROR_GRAPH_COULD_NOT_CHANGE_EDGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CHANGE_EDGE = "ERROR_GRAPH_COULD_NOT_CHANGE_EDGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CHANGE_EDGE]
  
  inline def ERROR_GRAPH_COULD_NOT_CHANGE_VERTEX: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CHANGE_VERTEX = "ERROR_GRAPH_COULD_NOT_CHANGE_VERTEX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CHANGE_VERTEX]
  
  inline def ERROR_GRAPH_COULD_NOT_CREATE_EDGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_EDGE = "ERROR_GRAPH_COULD_NOT_CREATE_EDGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_EDGE]
  
  inline def ERROR_GRAPH_COULD_NOT_CREATE_GRAPH: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_GRAPH = "ERROR_GRAPH_COULD_NOT_CREATE_GRAPH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_GRAPH]
  
  inline def ERROR_GRAPH_COULD_NOT_CREATE_VERTEX: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_VERTEX = "ERROR_GRAPH_COULD_NOT_CREATE_VERTEX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_COULD_NOT_CREATE_VERTEX]
  
  inline def ERROR_GRAPH_EMPTY: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_EMPTY = "ERROR_GRAPH_EMPTY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_EMPTY]
  
  inline def ERROR_GRAPH_INVALID_EDGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_EDGE = "ERROR_GRAPH_INVALID_EDGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_EDGE]
  
  inline def ERROR_GRAPH_INVALID_FILTER_RESULT: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_FILTER_RESULT = "ERROR_GRAPH_INVALID_FILTER_RESULT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_FILTER_RESULT]
  
  inline def ERROR_GRAPH_INVALID_GRAPH: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_GRAPH = "ERROR_GRAPH_INVALID_GRAPH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_GRAPH]
  
  inline def ERROR_GRAPH_INVALID_VERTEX: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_VERTEX = "ERROR_GRAPH_INVALID_VERTEX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_INVALID_VERTEX]
  
  inline def ERROR_GRAPH_TOO_MANY_ITERATIONS: typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_TOO_MANY_ITERATIONS = "ERROR_GRAPH_TOO_MANY_ITERATIONS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_GRAPH_TOO_MANY_ITERATIONS]
  
  inline def ERROR_HTTP_BAD_PARAMETER: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_BAD_PARAMETER = "ERROR_HTTP_BAD_PARAMETER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_BAD_PARAMETER]
  
  inline def ERROR_HTTP_CORRUPTED_JSON: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_CORRUPTED_JSON = "ERROR_HTTP_CORRUPTED_JSON".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_CORRUPTED_JSON]
  
  inline def ERROR_HTTP_FORBIDDEN: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_FORBIDDEN = "ERROR_HTTP_FORBIDDEN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_FORBIDDEN]
  
  inline def ERROR_HTTP_GATEWAY_TIMEOUT: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_GATEWAY_TIMEOUT = "ERROR_HTTP_GATEWAY_TIMEOUT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_GATEWAY_TIMEOUT]
  
  inline def ERROR_HTTP_METHOD_NOT_ALLOWED: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_METHOD_NOT_ALLOWED = "ERROR_HTTP_METHOD_NOT_ALLOWED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_METHOD_NOT_ALLOWED]
  
  inline def ERROR_HTTP_NOT_ACCEPTABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_NOT_ACCEPTABLE = "ERROR_HTTP_NOT_ACCEPTABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_NOT_ACCEPTABLE]
  
  inline def ERROR_HTTP_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_NOT_FOUND = "ERROR_HTTP_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_NOT_FOUND]
  
  inline def ERROR_HTTP_PRECONDITION_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_PRECONDITION_FAILED = "ERROR_HTTP_PRECONDITION_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_PRECONDITION_FAILED]
  
  inline def ERROR_HTTP_SERVER_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SERVER_ERROR = "ERROR_HTTP_SERVER_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SERVER_ERROR]
  
  inline def ERROR_HTTP_SERVICE_UNAVAILABLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SERVICE_UNAVAILABLE = "ERROR_HTTP_SERVICE_UNAVAILABLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SERVICE_UNAVAILABLE]
  
  inline def ERROR_HTTP_SUPERFLUOUS_SUFFICES: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SUPERFLUOUS_SUFFICES = "ERROR_HTTP_SUPERFLUOUS_SUFFICES".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_SUPERFLUOUS_SUFFICES]
  
  inline def ERROR_HTTP_UNAUTHORIZED: typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_UNAUTHORIZED = "ERROR_HTTP_UNAUTHORIZED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_HTTP_UNAUTHORIZED]
  
  inline def ERROR_ILLEGAL_NUMBER: typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_NUMBER = "ERROR_ILLEGAL_NUMBER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_NUMBER]
  
  inline def ERROR_ILLEGAL_OPTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_OPTION = "ERROR_ILLEGAL_OPTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_OPTION]
  
  inline def ERROR_ILLEGAL_SMART_GRAPH_ATTRIBUTE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_SMART_GRAPH_ATTRIBUTE = "ERROR_ILLEGAL_SMART_GRAPH_ATTRIBUTE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ILLEGAL_SMART_GRAPH_ATTRIBUTE]
  
  inline def ERROR_INTERNAL: typingsJapgolly.arangodb.arangodbStrings.ERROR_INTERNAL = "ERROR_INTERNAL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_INTERNAL]
  
  inline def ERROR_INVALID_FOXX_OPTIONS: typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_FOXX_OPTIONS = "ERROR_INVALID_FOXX_OPTIONS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_FOXX_OPTIONS]
  
  inline def ERROR_INVALID_MOUNTPOINT: typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_MOUNTPOINT = "ERROR_INVALID_MOUNTPOINT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_MOUNTPOINT]
  
  inline def ERROR_INVALID_SERVICE_MANIFEST: typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_SERVICE_MANIFEST = "ERROR_INVALID_SERVICE_MANIFEST".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_INVALID_SERVICE_MANIFEST]
  
  inline def ERROR_IP_ADDRESS_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_IP_ADDRESS_INVALID = "ERROR_IP_ADDRESS_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_IP_ADDRESS_INVALID]
  
  inline def ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE: typingsJapgolly.arangodb.arangodbStrings.ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE = "ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE]
  
  inline def ERROR_LDAP_CANNOT_BIND: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_BIND = "ERROR_LDAP_CANNOT_BIND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_BIND]
  
  inline def ERROR_LDAP_CANNOT_INIT: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_INIT = "ERROR_LDAP_CANNOT_INIT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_INIT]
  
  inline def ERROR_LDAP_CANNOT_SEARCH: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_SEARCH = "ERROR_LDAP_CANNOT_SEARCH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_SEARCH]
  
  inline def ERROR_LDAP_CANNOT_SET_OPTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_SET_OPTION = "ERROR_LDAP_CANNOT_SET_OPTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_SET_OPTION]
  
  inline def ERROR_LDAP_CANNOT_START_TLS: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_START_TLS = "ERROR_LDAP_CANNOT_START_TLS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_START_TLS]
  
  inline def ERROR_LDAP_CANNOT_UNBIND: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_UNBIND = "ERROR_LDAP_CANNOT_UNBIND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_CANNOT_UNBIND]
  
  inline def ERROR_LDAP_FOUND_NO_OBJECTS: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_FOUND_NO_OBJECTS = "ERROR_LDAP_FOUND_NO_OBJECTS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_FOUND_NO_OBJECTS]
  
  inline def ERROR_LDAP_INVALID_MODE: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_INVALID_MODE = "ERROR_LDAP_INVALID_MODE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_INVALID_MODE]
  
  inline def ERROR_LDAP_NOT_ONE_USER_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_NOT_ONE_USER_FOUND = "ERROR_LDAP_NOT_ONE_USER_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_NOT_ONE_USER_FOUND]
  
  inline def ERROR_LDAP_USER_NOT_IDENTIFIED: typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_USER_NOT_IDENTIFIED = "ERROR_LDAP_USER_NOT_IDENTIFIED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LDAP_USER_NOT_IDENTIFIED]
  
  inline def ERROR_LOCKED: typingsJapgolly.arangodb.arangodbStrings.ERROR_LOCKED = "ERROR_LOCKED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LOCKED]
  
  inline def ERROR_LOCK_TIMEOUT: typingsJapgolly.arangodb.arangodbStrings.ERROR_LOCK_TIMEOUT = "ERROR_LOCK_TIMEOUT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_LOCK_TIMEOUT]
  
  inline def ERROR_MALFORMED_MANIFEST_FILE: typingsJapgolly.arangodb.arangodbStrings.ERROR_MALFORMED_MANIFEST_FILE = "ERROR_MALFORMED_MANIFEST_FILE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_MALFORMED_MANIFEST_FILE]
  
  inline def ERROR_MODULE_FAILURE: typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_FAILURE = "ERROR_MODULE_FAILURE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_FAILURE]
  
  inline def ERROR_MODULE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_NOT_FOUND = "ERROR_MODULE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_NOT_FOUND]
  
  inline def ERROR_MODULE_SYNTAX_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_SYNTAX_ERROR = "ERROR_MODULE_SYNTAX_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_MODULE_SYNTAX_ERROR]
  
  inline def ERROR_NOT_IMPLEMENTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_NOT_IMPLEMENTED = "ERROR_NOT_IMPLEMENTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_NOT_IMPLEMENTED]
  
  inline def ERROR_NO_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_ERROR = "ERROR_NO_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_ERROR]
  
  inline def ERROR_NO_SMART_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_SMART_COLLECTION = "ERROR_NO_SMART_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_SMART_COLLECTION]
  
  inline def ERROR_NO_SMART_GRAPH_ATTRIBUTE: typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_SMART_GRAPH_ATTRIBUTE = "ERROR_NO_SMART_GRAPH_ATTRIBUTE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_NO_SMART_GRAPH_ATTRIBUTE]
  
  inline def ERROR_NUMERIC_OVERFLOW: typingsJapgolly.arangodb.arangodbStrings.ERROR_NUMERIC_OVERFLOW = "ERROR_NUMERIC_OVERFLOW".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_NUMERIC_OVERFLOW]
  
  inline def ERROR_ONLY_ENTERPRISE: typingsJapgolly.arangodb.arangodbStrings.ERROR_ONLY_ENTERPRISE = "ERROR_ONLY_ENTERPRISE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_ONLY_ENTERPRISE]
  
  inline def ERROR_OUT_OF_MEMORY: typingsJapgolly.arangodb.arangodbStrings.ERROR_OUT_OF_MEMORY = "ERROR_OUT_OF_MEMORY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_OUT_OF_MEMORY]
  
  inline def ERROR_OUT_OF_MEMORY_MMAP: typingsJapgolly.arangodb.arangodbStrings.ERROR_OUT_OF_MEMORY_MMAP = "ERROR_OUT_OF_MEMORY_MMAP".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_OUT_OF_MEMORY_MMAP]
  
  inline def ERROR_QUERY_ACCESS_AFTER_MODIFICATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_ACCESS_AFTER_MODIFICATION = "ERROR_QUERY_ACCESS_AFTER_MODIFICATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_ACCESS_AFTER_MODIFICATION]
  
  inline def ERROR_QUERY_ARRAY_EXPECTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_ARRAY_EXPECTED = "ERROR_QUERY_ARRAY_EXPECTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_ARRAY_EXPECTED]
  
  inline def ERROR_QUERY_BAD_JSON_PLAN: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BAD_JSON_PLAN = "ERROR_QUERY_BAD_JSON_PLAN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BAD_JSON_PLAN]
  
  inline def ERROR_QUERY_BIND_PARAMETERS_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETERS_INVALID = "ERROR_QUERY_BIND_PARAMETERS_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETERS_INVALID]
  
  inline def ERROR_QUERY_BIND_PARAMETER_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_MISSING = "ERROR_QUERY_BIND_PARAMETER_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_MISSING]
  
  inline def ERROR_QUERY_BIND_PARAMETER_TYPE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_TYPE = "ERROR_QUERY_BIND_PARAMETER_TYPE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_TYPE]
  
  inline def ERROR_QUERY_BIND_PARAMETER_UNDECLARED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_UNDECLARED = "ERROR_QUERY_BIND_PARAMETER_UNDECLARED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_BIND_PARAMETER_UNDECLARED]
  
  inline def ERROR_QUERY_COLLECTION_LOCK_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COLLECTION_LOCK_FAILED = "ERROR_QUERY_COLLECTION_LOCK_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COLLECTION_LOCK_FAILED]
  
  inline def ERROR_QUERY_COLLECTION_USED_IN_EXPRESSION: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COLLECTION_USED_IN_EXPRESSION = "ERROR_QUERY_COLLECTION_USED_IN_EXPRESSION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COLLECTION_USED_IN_EXPRESSION]
  
  inline def ERROR_QUERY_COMPILE_TIME_OPTIONS: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COMPILE_TIME_OPTIONS = "ERROR_QUERY_COMPILE_TIME_OPTIONS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_COMPILE_TIME_OPTIONS]
  
  inline def ERROR_QUERY_DISALLOWED_DYNAMIC_CALL: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DISALLOWED_DYNAMIC_CALL = "ERROR_QUERY_DISALLOWED_DYNAMIC_CALL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DISALLOWED_DYNAMIC_CALL]
  
  inline def ERROR_QUERY_DIVISION_BY_ZERO: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DIVISION_BY_ZERO = "ERROR_QUERY_DIVISION_BY_ZERO".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DIVISION_BY_ZERO]
  
  inline def ERROR_QUERY_DOCUMENT_ATTRIBUTE_REDECLARED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DOCUMENT_ATTRIBUTE_REDECLARED = "ERROR_QUERY_DOCUMENT_ATTRIBUTE_REDECLARED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_DOCUMENT_ATTRIBUTE_REDECLARED]
  
  inline def ERROR_QUERY_EMPTY: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_EMPTY = "ERROR_QUERY_EMPTY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_EMPTY]
  
  inline def ERROR_QUERY_EXCEPTION_OPTIONS: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_EXCEPTION_OPTIONS = "ERROR_QUERY_EXCEPTION_OPTIONS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_EXCEPTION_OPTIONS]
  
  inline def ERROR_QUERY_FAIL_CALLED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FAIL_CALLED = "ERROR_QUERY_FAIL_CALLED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FAIL_CALLED]
  
  inline def ERROR_QUERY_FULLTEXT_INDEX_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FULLTEXT_INDEX_MISSING = "ERROR_QUERY_FULLTEXT_INDEX_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FULLTEXT_INDEX_MISSING]
  
  inline def ERROR_QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH = "ERROR_QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH]
  
  inline def ERROR_QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH = "ERROR_QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH]
  
  inline def ERROR_QUERY_FUNCTION_INVALID_CODE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_INVALID_CODE = "ERROR_QUERY_FUNCTION_INVALID_CODE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_INVALID_CODE]
  
  inline def ERROR_QUERY_FUNCTION_INVALID_NAME: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_INVALID_NAME = "ERROR_QUERY_FUNCTION_INVALID_NAME".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_INVALID_NAME]
  
  inline def ERROR_QUERY_FUNCTION_NAME_UNKNOWN: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_NAME_UNKNOWN = "ERROR_QUERY_FUNCTION_NAME_UNKNOWN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_NAME_UNKNOWN]
  
  inline def ERROR_QUERY_FUNCTION_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_NOT_FOUND = "ERROR_QUERY_FUNCTION_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_NOT_FOUND]
  
  inline def ERROR_QUERY_FUNCTION_RUNTIME_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_RUNTIME_ERROR = "ERROR_QUERY_FUNCTION_RUNTIME_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_FUNCTION_RUNTIME_ERROR]
  
  inline def ERROR_QUERY_GEO_INDEX_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_GEO_INDEX_MISSING = "ERROR_QUERY_GEO_INDEX_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_GEO_INDEX_MISSING]
  
  inline def ERROR_QUERY_INVALID_AGGREGATE_EXPRESSION: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_AGGREGATE_EXPRESSION = "ERROR_QUERY_INVALID_AGGREGATE_EXPRESSION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_AGGREGATE_EXPRESSION]
  
  inline def ERROR_QUERY_INVALID_ARITHMETIC_VALUE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_ARITHMETIC_VALUE = "ERROR_QUERY_INVALID_ARITHMETIC_VALUE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_ARITHMETIC_VALUE]
  
  inline def ERROR_QUERY_INVALID_DATE_VALUE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_DATE_VALUE = "ERROR_QUERY_INVALID_DATE_VALUE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_DATE_VALUE]
  
  inline def ERROR_QUERY_INVALID_LOGICAL_VALUE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_LOGICAL_VALUE = "ERROR_QUERY_INVALID_LOGICAL_VALUE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_LOGICAL_VALUE]
  
  inline def ERROR_QUERY_INVALID_REGEX: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_REGEX = "ERROR_QUERY_INVALID_REGEX".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_INVALID_REGEX]
  
  inline def ERROR_QUERY_IN_USE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_IN_USE = "ERROR_QUERY_IN_USE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_IN_USE]
  
  inline def ERROR_QUERY_KILLED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_KILLED = "ERROR_QUERY_KILLED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_KILLED]
  
  inline def ERROR_QUERY_MULTI_MODIFY: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_MULTI_MODIFY = "ERROR_QUERY_MULTI_MODIFY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_MULTI_MODIFY]
  
  inline def ERROR_QUERY_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_NOT_FOUND = "ERROR_QUERY_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_NOT_FOUND]
  
  inline def ERROR_QUERY_NUMBER_OUT_OF_RANGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_NUMBER_OUT_OF_RANGE = "ERROR_QUERY_NUMBER_OUT_OF_RANGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_NUMBER_OUT_OF_RANGE]
  
  inline def ERROR_QUERY_PARSE: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_PARSE = "ERROR_QUERY_PARSE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_PARSE]
  
  inline def ERROR_QUERY_SCRIPT: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_SCRIPT = "ERROR_QUERY_SCRIPT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_SCRIPT]
  
  inline def ERROR_QUERY_TOO_MANY_COLLECTIONS: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_TOO_MANY_COLLECTIONS = "ERROR_QUERY_TOO_MANY_COLLECTIONS".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_TOO_MANY_COLLECTIONS]
  
  inline def ERROR_QUERY_USER_ASSERT: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_USER_ASSERT = "ERROR_QUERY_USER_ASSERT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_USER_ASSERT]
  
  inline def ERROR_QUERY_USER_WARN: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_USER_WARN = "ERROR_QUERY_USER_WARN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_USER_WARN]
  
  inline def ERROR_QUERY_VARIABLE_NAME_INVALID: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_NAME_INVALID = "ERROR_QUERY_VARIABLE_NAME_INVALID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_NAME_INVALID]
  
  inline def ERROR_QUERY_VARIABLE_NAME_UNKNOWN: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_NAME_UNKNOWN = "ERROR_QUERY_VARIABLE_NAME_UNKNOWN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_NAME_UNKNOWN]
  
  inline def ERROR_QUERY_VARIABLE_REDECLARED: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_REDECLARED = "ERROR_QUERY_VARIABLE_REDECLARED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUERY_VARIABLE_REDECLARED]
  
  inline def ERROR_QUEUE_FULL: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUEUE_FULL = "ERROR_QUEUE_FULL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUEUE_FULL]
  
  inline def ERROR_QUEUE_UNKNOWN: typingsJapgolly.arangodb.arangodbStrings.ERROR_QUEUE_UNKNOWN = "ERROR_QUEUE_UNKNOWN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_QUEUE_UNKNOWN]
  
  inline def ERROR_REPLICATION_APPLIER_STOPPED: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_APPLIER_STOPPED = "ERROR_REPLICATION_APPLIER_STOPPED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_APPLIER_STOPPED]
  
  inline def ERROR_REPLICATION_INVALID_APPLIER_CONFIGURATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_APPLIER_CONFIGURATION = "ERROR_REPLICATION_INVALID_APPLIER_CONFIGURATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_APPLIER_CONFIGURATION]
  
  inline def ERROR_REPLICATION_INVALID_APPLIER_STATE: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_APPLIER_STATE = "ERROR_REPLICATION_INVALID_APPLIER_STATE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_APPLIER_STATE]
  
  inline def ERROR_REPLICATION_INVALID_RESPONSE: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_RESPONSE = "ERROR_REPLICATION_INVALID_RESPONSE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_INVALID_RESPONSE]
  
  inline def ERROR_REPLICATION_LOOP: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_LOOP = "ERROR_REPLICATION_LOOP".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_LOOP]
  
  inline def ERROR_REPLICATION_MASTER_CHANGE: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_CHANGE = "ERROR_REPLICATION_MASTER_CHANGE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_CHANGE]
  
  inline def ERROR_REPLICATION_MASTER_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_ERROR = "ERROR_REPLICATION_MASTER_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_ERROR]
  
  inline def ERROR_REPLICATION_MASTER_INCOMPATIBLE: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_INCOMPATIBLE = "ERROR_REPLICATION_MASTER_INCOMPATIBLE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_MASTER_INCOMPATIBLE]
  
  inline def ERROR_REPLICATION_NO_RESPONSE: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_NO_RESPONSE = "ERROR_REPLICATION_NO_RESPONSE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_NO_RESPONSE]
  
  inline def ERROR_REPLICATION_NO_START_TICK: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_NO_START_TICK = "ERROR_REPLICATION_NO_START_TICK".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_NO_START_TICK]
  
  inline def ERROR_REPLICATION_RUNNING: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_RUNNING = "ERROR_REPLICATION_RUNNING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_RUNNING]
  
  inline def ERROR_REPLICATION_SHARD_NONEMPTY: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_SHARD_NONEMPTY = "ERROR_REPLICATION_SHARD_NONEMPTY".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_SHARD_NONEMPTY]
  
  inline def ERROR_REPLICATION_START_TICK_NOT_PRESENT: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_START_TICK_NOT_PRESENT = "ERROR_REPLICATION_START_TICK_NOT_PRESENT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_START_TICK_NOT_PRESENT]
  
  inline def ERROR_REPLICATION_UNEXPECTED_MARKER: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_UNEXPECTED_MARKER = "ERROR_REPLICATION_UNEXPECTED_MARKER".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_UNEXPECTED_MARKER]
  
  inline def ERROR_REPLICATION_UNEXPECTED_TRANSACTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_UNEXPECTED_TRANSACTION = "ERROR_REPLICATION_UNEXPECTED_TRANSACTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_UNEXPECTED_TRANSACTION]
  
  inline def ERROR_REPLICATION_WRONG_CHECKSUM: typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_WRONG_CHECKSUM = "ERROR_REPLICATION_WRONG_CHECKSUM".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REPLICATION_WRONG_CHECKSUM]
  
  inline def ERROR_REQUEST_CANCELED: typingsJapgolly.arangodb.arangodbStrings.ERROR_REQUEST_CANCELED = "ERROR_REQUEST_CANCELED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_REQUEST_CANCELED]
  
  inline def ERROR_RESOURCE_LIMIT: typingsJapgolly.arangodb.arangodbStrings.ERROR_RESOURCE_LIMIT = "ERROR_RESOURCE_LIMIT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_RESOURCE_LIMIT]
  
  inline def ERROR_SERVICE_DOWNLOAD_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_DOWNLOAD_FAILED = "ERROR_SERVICE_DOWNLOAD_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_DOWNLOAD_FAILED]
  
  inline def ERROR_SERVICE_FILES_MISSING: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_FILES_MISSING = "ERROR_SERVICE_FILES_MISSING".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_FILES_MISSING]
  
  inline def ERROR_SERVICE_FILES_OUTDATED: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_FILES_OUTDATED = "ERROR_SERVICE_FILES_OUTDATED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_FILES_OUTDATED]
  
  inline def ERROR_SERVICE_INVALID_MOUNT: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_INVALID_MOUNT = "ERROR_SERVICE_INVALID_MOUNT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_INVALID_MOUNT]
  
  inline def ERROR_SERVICE_INVALID_NAME: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_INVALID_NAME = "ERROR_SERVICE_INVALID_NAME".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_INVALID_NAME]
  
  inline def ERROR_SERVICE_MANIFEST_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_MANIFEST_NOT_FOUND = "ERROR_SERVICE_MANIFEST_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_MANIFEST_NOT_FOUND]
  
  inline def ERROR_SERVICE_MOUNTPOINT_CONFLICT: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_MOUNTPOINT_CONFLICT = "ERROR_SERVICE_MOUNTPOINT_CONFLICT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_MOUNTPOINT_CONFLICT]
  
  inline def ERROR_SERVICE_NEEDS_CONFIGURATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_NEEDS_CONFIGURATION = "ERROR_SERVICE_NEEDS_CONFIGURATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_NEEDS_CONFIGURATION]
  
  inline def ERROR_SERVICE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_NOT_FOUND = "ERROR_SERVICE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_NOT_FOUND]
  
  inline def ERROR_SERVICE_OPTIONS_MALFORMED: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_OPTIONS_MALFORMED = "ERROR_SERVICE_OPTIONS_MALFORMED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_OPTIONS_MALFORMED]
  
  inline def ERROR_SERVICE_SOURCE_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_SOURCE_ERROR = "ERROR_SERVICE_SOURCE_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_SOURCE_ERROR]
  
  inline def ERROR_SERVICE_SOURCE_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_SOURCE_NOT_FOUND = "ERROR_SERVICE_SOURCE_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_SOURCE_NOT_FOUND]
  
  inline def ERROR_SERVICE_UNKNOWN_SCRIPT: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_UNKNOWN_SCRIPT = "ERROR_SERVICE_UNKNOWN_SCRIPT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_UNKNOWN_SCRIPT]
  
  inline def ERROR_SERVICE_UPLOAD_FAILED: typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_UPLOAD_FAILED = "ERROR_SERVICE_UPLOAD_FAILED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SERVICE_UPLOAD_FAILED]
  
  inline def ERROR_SESSION_EXPIRED: typingsJapgolly.arangodb.arangodbStrings.ERROR_SESSION_EXPIRED = "ERROR_SESSION_EXPIRED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SESSION_EXPIRED]
  
  inline def ERROR_SESSION_UNKNOWN: typingsJapgolly.arangodb.arangodbStrings.ERROR_SESSION_UNKNOWN = "ERROR_SESSION_UNKNOWN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SESSION_UNKNOWN]
  
  inline def ERROR_SHUTTING_DOWN: typingsJapgolly.arangodb.arangodbStrings.ERROR_SHUTTING_DOWN = "ERROR_SHUTTING_DOWN".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SHUTTING_DOWN]
  
  inline def ERROR_SUPERVISION_GENERAL_FAILURE: typingsJapgolly.arangodb.arangodbStrings.ERROR_SUPERVISION_GENERAL_FAILURE = "ERROR_SUPERVISION_GENERAL_FAILURE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SUPERVISION_GENERAL_FAILURE]
  
  inline def ERROR_SYS_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_SYS_ERROR = "ERROR_SYS_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_SYS_ERROR]
  
  inline def ERROR_TASK_DUPLICATE_ID: typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_DUPLICATE_ID = "ERROR_TASK_DUPLICATE_ID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_DUPLICATE_ID]
  
  inline def ERROR_TASK_INVALID_ID: typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_INVALID_ID = "ERROR_TASK_INVALID_ID".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_INVALID_ID]
  
  inline def ERROR_TASK_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_NOT_FOUND = "ERROR_TASK_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TASK_NOT_FOUND]
  
  inline def ERROR_TRANSACTION_ABORTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_ABORTED = "ERROR_TRANSACTION_ABORTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_ABORTED]
  
  inline def ERROR_TRANSACTION_DISALLOWED_OPERATION: typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_DISALLOWED_OPERATION = "ERROR_TRANSACTION_DISALLOWED_OPERATION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_DISALLOWED_OPERATION]
  
  inline def ERROR_TRANSACTION_INTERNAL: typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_INTERNAL = "ERROR_TRANSACTION_INTERNAL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_INTERNAL]
  
  inline def ERROR_TRANSACTION_NESTED: typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_NESTED = "ERROR_TRANSACTION_NESTED".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_NESTED]
  
  inline def ERROR_TRANSACTION_UNREGISTERED_COLLECTION: typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_UNREGISTERED_COLLECTION = "ERROR_TRANSACTION_UNREGISTERED_COLLECTION".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TRANSACTION_UNREGISTERED_COLLECTION]
  
  inline def ERROR_TYPE_ERROR: typingsJapgolly.arangodb.arangodbStrings.ERROR_TYPE_ERROR = "ERROR_TYPE_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_TYPE_ERROR]
  
  inline def ERROR_USER_CHANGE_PASSWORD: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_CHANGE_PASSWORD = "ERROR_USER_CHANGE_PASSWORD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_CHANGE_PASSWORD]
  
  inline def ERROR_USER_DUPLICATE: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_DUPLICATE = "ERROR_USER_DUPLICATE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_DUPLICATE]
  
  inline def ERROR_USER_EXTERNAL: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_EXTERNAL = "ERROR_USER_EXTERNAL".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_EXTERNAL]
  
  inline def ERROR_USER_INVALID_NAME: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_INVALID_NAME = "ERROR_USER_INVALID_NAME".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_INVALID_NAME]
  
  inline def ERROR_USER_INVALID_PASSWORD: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_INVALID_PASSWORD = "ERROR_USER_INVALID_PASSWORD".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_INVALID_PASSWORD]
  
  inline def ERROR_USER_NOT_FOUND: typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.ERROR_USER_NOT_FOUND]
  
  inline def SIMPLE_CLIENT_COULD_NOT_CONNECT: typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_CONNECT = "SIMPLE_CLIENT_COULD_NOT_CONNECT".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_CONNECT]
  
  inline def SIMPLE_CLIENT_COULD_NOT_READ: typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_READ = "SIMPLE_CLIENT_COULD_NOT_READ".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_READ]
  
  inline def SIMPLE_CLIENT_COULD_NOT_WRITE: typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_WRITE = "SIMPLE_CLIENT_COULD_NOT_WRITE".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_COULD_NOT_WRITE]
  
  inline def SIMPLE_CLIENT_UNKNOWN_ERROR: typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_UNKNOWN_ERROR = "SIMPLE_CLIENT_UNKNOWN_ERROR".asInstanceOf[typingsJapgolly.arangodb.arangodbStrings.SIMPLE_CLIENT_UNKNOWN_ERROR]
}
