package typingsJapgolly.fluentuiReactComponentEventListener

import typingsJapgolly.fluentuiReactComponentEventListener.distEsTypesMod.EventListenerOptions
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.DOMContentLoaded
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.abort
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationcancel
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationiteration
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.auxclick
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.beforeinput
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.blur
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.canplay
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.canplaythrough
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.change
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.click
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.close
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.compositionend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.compositionstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.compositionupdate
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.contextmenu
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.copy
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.cuechange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.cut
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dblclick
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.drag
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragenter
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragleave
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragover
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.drop
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.durationchange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.emptied
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.ended
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.error
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focus
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focusin
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focusout
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.formdata
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.fullscreenchange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.fullscreenerror
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.gotpointercapture
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.input
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.invalid
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keydown
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keypress
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keyup
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.load
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadeddata
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadedmetadata
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.lostpointercapture
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mousedown
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseenter
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseleave
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mousemove
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseout
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseover
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseup
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.paste
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pause
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.play
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.playing
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointercancel
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerdown
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerenter
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerleave
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerlockchange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerlockerror
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointermove
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerout
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerover
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerup
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.progress
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.ratechange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.readystatechange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.reset
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.resize
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.scroll
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.securitypolicyviolation
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.seeked
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.seeking
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.select
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.selectionchange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.selectstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.slotchange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.stalled
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.submit
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.suspend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.timeupdate
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.toggle
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchcancel
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchmove
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitioncancel
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionrun
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.visibilitychange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.volumechange
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.waiting
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.webkitanimationend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.webkitanimationiteration
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.webkitanimationstart
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.webkittransitionend
import typingsJapgolly.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.wheel
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distEsEventListenerMod {
  
  object EventListener {
    
    inline def apply(
      props: EventListenerOptions[
          DOMContentLoaded | abort | animationcancel | animationend | animationiteration | animationstart | auxclick | beforeinput | blur | canplay | canplaythrough | change | click | close | compositionend | compositionstart | compositionupdate | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | formdata | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointerlockchange | pointerlockerror | pointermove | pointerout | pointerover | pointerup | progress | ratechange | readystatechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | slotchange | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | visibilitychange | volumechange | waiting | webkitanimationend | webkitanimationiteration | webkitanimationstart | webkittransitionend | wheel
        ]
    ): Null = ^.asInstanceOf[js.Dynamic].apply(props.asInstanceOf[js.Any]).asInstanceOf[Null]
    
    @JSImport("@fluentui/react-component-event-listener/dist/es/EventListener", "EventListener")
    @js.native
    val ^ : js.Any = js.native
    
    object defaultProps {
      
      @JSImport("@fluentui/react-component-event-listener/dist/es/EventListener", "EventListener.defaultProps")
      @js.native
      val ^ : js.Any = js.native
      
      @JSImport("@fluentui/react-component-event-listener/dist/es/EventListener", "EventListener.defaultProps.capture")
      @js.native
      def capture: Boolean = js.native
      inline def capture_=(x: Boolean): Unit = ^.asInstanceOf[js.Dynamic].updateDynamic("capture")(x.asInstanceOf[js.Any])
    }
  }
}
