package typingsJapgolly.actionsOnGoogle.distServiceActionssdkApiV2Mod

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_UNSPECIFIED
  - typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_GOOGLE
  - typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_MERCHANT
*/
trait GoogleActionsTransactionsV3PaymentInfoPaymentMethodProvenance extends StObject
object GoogleActionsTransactionsV3PaymentInfoPaymentMethodProvenance {
  
  inline def PAYMENT_METHOD_PROVENANCE_GOOGLE: typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_GOOGLE = "PAYMENT_METHOD_PROVENANCE_GOOGLE".asInstanceOf[typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_GOOGLE]
  
  inline def PAYMENT_METHOD_PROVENANCE_MERCHANT: typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_MERCHANT = "PAYMENT_METHOD_PROVENANCE_MERCHANT".asInstanceOf[typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_MERCHANT]
  
  inline def PAYMENT_METHOD_PROVENANCE_UNSPECIFIED: typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_UNSPECIFIED = "PAYMENT_METHOD_PROVENANCE_UNSPECIFIED".asInstanceOf[typingsJapgolly.actionsOnGoogle.actionsOnGoogleStrings.PAYMENT_METHOD_PROVENANCE_UNSPECIFIED]
}
