package typingsJapgolly.awsSdkClientDynamodbNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod {
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationUpdate = typingsJapgolly.awsSdkClientDynamodbNode.typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod.AutoScalingTargetTrackingScalingPolicyConfigurationUpdate
}
