package typingsJapgolly.activexLibreoffice.com_.sun.star.rendering

import japgolly.scalajs.react.Callback
import japgolly.scalajs.react.CallbackTo
import typingsJapgolly.activexLibreoffice.`type`
import typingsJapgolly.activexLibreoffice.com_.sun.star.geometry.RealPoint2D
import typingsJapgolly.activexLibreoffice.com_.sun.star.uno.XInterface
import typingsJapgolly.std.SafeArray
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/**
  * Interface to a dynamic poly-polygon generator, that generates poly-polygons depending on a given parameter value.
  *
  * The returned poly-polygon should normally be contained in the [0,1]x[0,1] rectangle. At least that is the dimension expected at other places. e.g.
  * {@link Texture} .
  */
trait XParametricPolyPolygon2D
  extends StObject
     with XInterface {
  
  /**
    * Query the color space employed by this object
    * @returns the color space the colors generated by this object are to be interpreted in.
    */
  val ColorSpace: XColorSpace
  
  /**
    * Query the color value for the polygonal area at the specified parameter value.
    * @param t Parameter value in the range [0,1]. During painting, this range is swept through starting from 0.
    */
  def getColor(t: Double): SafeArray[ColorComponent]
  
  /**
    * Query the color space employed by this object
    * @returns the color space the colors generated by this object are to be interpreted in.
    */
  def getColorSpace(): XColorSpace
  
  /**
    * Query the polygonal outline at the specified value.
    *
    * The returned outline should be clipped to the [0,1]x[0,1] rectangle.
    * @param t Parameter value in the range [0,1]. During painting, this range is swept through starting from 0. When using such a parametric poly-polygon for
    */
  def getOutline(t: Double): XPolyPolygon2D
  
  /**
    * Query the color for a dedicated point in the plane.
    * @param point The permissible parameter range for point is [0,1]x[0,1]
    */
  def getPointColor(point: RealPoint2D): SafeArray[ColorComponent]
}
object XParametricPolyPolygon2D {
  
  inline def apply(
    ColorSpace: XColorSpace,
    acquire: Callback,
    getColor: Double => SafeArray[ColorComponent],
    getColorSpace: CallbackTo[XColorSpace],
    getOutline: Double => XPolyPolygon2D,
    getPointColor: RealPoint2D => SafeArray[ColorComponent],
    queryInterface: `type` => Any,
    release: Callback
  ): XParametricPolyPolygon2D = {
    val __obj = js.Dynamic.literal(ColorSpace = ColorSpace.asInstanceOf[js.Any], acquire = acquire.toJsFn, getColor = js.Any.fromFunction1(getColor), getColorSpace = getColorSpace.toJsFn, getOutline = js.Any.fromFunction1(getOutline), getPointColor = js.Any.fromFunction1(getPointColor), queryInterface = js.Any.fromFunction1(queryInterface), release = release.toJsFn)
    __obj.asInstanceOf[XParametricPolyPolygon2D]
  }
  
  extension [Self <: XParametricPolyPolygon2D](x: Self) {
    
    inline def setColorSpace(value: XColorSpace): Self = StObject.set(x, "ColorSpace", value.asInstanceOf[js.Any])
    
    inline def setGetColor(value: Double => SafeArray[ColorComponent]): Self = StObject.set(x, "getColor", js.Any.fromFunction1(value))
    
    inline def setGetColorSpace(value: CallbackTo[XColorSpace]): Self = StObject.set(x, "getColorSpace", value.toJsFn)
    
    inline def setGetOutline(value: Double => XPolyPolygon2D): Self = StObject.set(x, "getOutline", js.Any.fromFunction1(value))
    
    inline def setGetPointColor(value: RealPoint2D => SafeArray[ColorComponent]): Self = StObject.set(x, "getPointColor", js.Any.fromFunction1(value))
  }
}
