package typingsJapgolly.libraCore.mempoolGrpcPbMod

import typingsJapgolly.grpc.mod.MethodDefinition
import typingsJapgolly.libraCore.mempoolPbMod.AddTransactionWithValidationRequest
import typingsJapgolly.libraCore.mempoolPbMod.AddTransactionWithValidationResponse
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait IMempoolServiceIAddTransactionWithValidation extends MethodDefinition[AddTransactionWithValidationRequest, AddTransactionWithValidationResponse]

