package typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mod

import typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.error_
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.location
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stationary
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.activity
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.start
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stop
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.error_
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.authorization
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.foreground
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.background
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.abort_requested
  - typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.http_authorization
*/
trait Event extends StObject
object Event {
  
  inline def abort_requested: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.abort_requested = "abort_requested".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.abort_requested]
  
  inline def activity: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.activity = "activity".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.activity]
  
  inline def authorization: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.authorization = "authorization".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.authorization]
  
  inline def background: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.background = "background".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.background]
  
  inline def error: error_ = "error".asInstanceOf[error_]
  
  inline def foreground: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.foreground = "foreground".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.foreground]
  
  inline def http_authorization: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.http_authorization = "http_authorization".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.http_authorization]
  
  inline def location: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.location = "location".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.location]
  
  inline def start: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.start = "start".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.start]
  
  inline def stationary: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stationary = "stationary".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stationary]
  
  inline def stop: typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stop = "stop".asInstanceOf[typingsJapgolly.mauron85ReactNativeBackgroundGeolocation.mauron85ReactNativeBackgroundGeolocationStrings.stop]
}
