package typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod

import org.scalablytyped.runtime.StringDictionary
import typingsJapgolly.firebaseFirestore.anon.Seconds
import typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.^
import typingsJapgolly.firebaseFirestore.firebaseFirestoreStrings.NULL_VALUE
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


inline def CompositeFilterOpEnum: ICompositeFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("CompositeFilterOpEnum").asInstanceOf[ICompositeFilterOpEnum]

inline def FieldFilterOpEnum: IFieldFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("FieldFilterOpEnum").asInstanceOf[IFieldFilterOpEnum]

inline def FieldTransformSetToServerValueEnum: IFieldTransformSetToServerValueEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("FieldTransformSetToServerValueEnum").asInstanceOf[IFieldTransformSetToServerValueEnum]

inline def IndexFieldModeEnum: IIndexFieldModeEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("IndexFieldModeEnum").asInstanceOf[IIndexFieldModeEnum]

inline def IndexStateEnum: IIndexStateEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("IndexStateEnum").asInstanceOf[IIndexStateEnum]

inline def OrderDirectionEnum: IOrderDirectionEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("OrderDirectionEnum").asInstanceOf[IOrderDirectionEnum]

inline def ProjectsDatabasesDocumentsApiClientAltEnum: IProjectsDatabasesDocumentsApiClientAltEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesDocumentsApiClientAltEnum").asInstanceOf[IProjectsDatabasesDocumentsApiClientAltEnum]

inline def ProjectsDatabasesDocumentsApiClientXgafvEnum: IProjectsDatabasesDocumentsApiClientXgafvEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesDocumentsApiClient$XgafvEnum").asInstanceOf[IProjectsDatabasesDocumentsApiClientXgafvEnum]

inline def ProjectsDatabasesIndexesApiClientAltEnum: IProjectsDatabasesIndexesApiClientAltEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesIndexesApiClientAltEnum").asInstanceOf[IProjectsDatabasesIndexesApiClientAltEnum]

inline def ProjectsDatabasesIndexesApiClientXgafvEnum: IProjectsDatabasesIndexesApiClientXgafvEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ProjectsDatabasesIndexesApiClient$XgafvEnum").asInstanceOf[IProjectsDatabasesIndexesApiClientXgafvEnum]

inline def TargetChangeTargetChangeTypeEnum: ITargetChangeTargetChangeTypeEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("TargetChangeTargetChangeTypeEnum").asInstanceOf[ITargetChangeTargetChangeTypeEnum]

inline def UnaryFilterOpEnum: IUnaryFilterOpEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("UnaryFilterOpEnum").asInstanceOf[IUnaryFilterOpEnum]

inline def ValueNullValueEnum: IValueNullValueEnum = ^.asInstanceOf[js.Dynamic].selectDynamic("ValueNullValueEnum").asInstanceOf[IValueNullValueEnum]

type ApiClientHookFactory = Any

type ApiClientObjectMap[T] = StringDictionary[T]

type ArrayValue = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ArrayValue

type BatchGetDocumentsRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BatchGetDocumentsRequest

type BatchGetDocumentsResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BatchGetDocumentsResponse

type BeginTransactionRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BeginTransactionRequest

type BeginTransactionResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.BeginTransactionResponse

type CollectionSelector = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CollectionSelector

type CommitRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CommitRequest

type CommitResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CommitResponse

type CompositeFilter = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.CompositeFilter

type Cursor = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Cursor

type Document = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Document

type DocumentChange = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentChange

type DocumentDelete = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentDelete

type DocumentMask = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentMask

type DocumentRemove = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentRemove

type DocumentTransform = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentTransform

type DocumentsTarget = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.DocumentsTarget

type Empty = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Empty

type ExistenceFilter = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ExistenceFilter

type FieldFilter = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldFilter

type FieldReference = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldReference

type FieldTransform = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.FieldTransform

type Filter = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Filter

type Index = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Index

type IndexField = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.IndexField

type LatLng = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.LatLng

type ListCollectionIdsRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListCollectionIdsRequest

type ListCollectionIdsResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListCollectionIdsResponse

type ListDocumentsResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListDocumentsResponse

type ListIndexesResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListIndexesResponse

type ListenRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListenRequest

type ListenResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ListenResponse

type MapValue = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.MapValue

type Operation = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Operation

type Order = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Order

type Precondition = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Precondition

type Projection = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Projection

type PromiseRequestService = Any

type QueryTarget = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.QueryTarget

type ReadOnly = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ReadOnly

type ReadWrite = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.ReadWrite

type RollbackRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RollbackRequest

type RunAggregationQueryRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunAggregationQueryRequest

type RunAggregationQueryResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunAggregationQueryResponse

type RunQueryRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunQueryRequest

type RunQueryResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.RunQueryResponse

type Status = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Status

type StructuredQuery = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.StructuredQuery

type Target = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Target

type TargetChange = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.TargetChange

type Timestamp = String | Seconds

type TransactionOptions = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.TransactionOptions

type UnaryFilter = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.UnaryFilter

type Value = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Value

type ValueNullValue = NULL_VALUE

type Write = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.Write

type WriteRequest = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteRequest

type WriteResponse = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteResponse

type WriteResult = typingsJapgolly.firebaseFirestore.distFirestoreSrcProtosFirestoreProtoApiMod.firestoreV1ApiClientInterfaces.WriteResult
