package typingsJapgolly.stellarBase

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object mod {
  type AssetType = typingsJapgolly.stellarBase.mod.AssetType.native | typingsJapgolly.stellarBase.mod.AssetType.credit4 | typingsJapgolly.stellarBase.mod.AssetType.credit12
  type AuthFlag = typingsJapgolly.stellarBase.mod.AuthFlag.immutable | typingsJapgolly.stellarBase.mod.AuthFlag.required | typingsJapgolly.stellarBase.mod.AuthFlag.revocable
  type KeypairType = typingsJapgolly.stellarBase.stellarBaseStrings.ed25519
  type MemoType = typingsJapgolly.stellarBase.mod.MemoType.None | typingsJapgolly.stellarBase.mod.MemoType.ID | typingsJapgolly.stellarBase.mod.MemoType.Text | typingsJapgolly.stellarBase.mod.MemoType.Hash | typingsJapgolly.stellarBase.mod.MemoType.Return
  type MemoValue = scala.Null | java.lang.String | typingsJapgolly.node.Buffer
  type Operation = typingsJapgolly.stellarBase.mod.Operation.CreateAccount_ | typingsJapgolly.stellarBase.mod.Operation.Payment_ | typingsJapgolly.stellarBase.mod.Operation.PathPaymentStrictReceive_ | typingsJapgolly.stellarBase.mod.Operation.PathPaymentStrictSend_ | typingsJapgolly.stellarBase.mod.Operation.CreatePassiveSellOffer_ | typingsJapgolly.stellarBase.mod.Operation.ManageSellOffer_ | typingsJapgolly.stellarBase.mod.Operation.ManageBuyOffer_ | typingsJapgolly.stellarBase.mod.Operation.SetOptions_[typingsJapgolly.stellarBase.mod.SignerOptions] | typingsJapgolly.stellarBase.mod.Operation.ChangeTrust_ | typingsJapgolly.stellarBase.mod.Operation.AllowTrust_ | typingsJapgolly.stellarBase.mod.Operation.AccountMerge_ | typingsJapgolly.stellarBase.mod.Operation.Inflation_ | typingsJapgolly.stellarBase.mod.Operation.ManageData_ | typingsJapgolly.stellarBase.mod.Operation.BumpSequence_
  type OperationOptions = typingsJapgolly.stellarBase.mod.OperationOptions.CreateAccount | typingsJapgolly.stellarBase.mod.OperationOptions.Payment | typingsJapgolly.stellarBase.mod.OperationOptions.PathPaymentStrictReceive | typingsJapgolly.stellarBase.mod.OperationOptions.PathPaymentStrictSend | typingsJapgolly.stellarBase.mod.OperationOptions.CreatePassiveSellOffer | typingsJapgolly.stellarBase.mod.OperationOptions.ManageSellOffer | typingsJapgolly.stellarBase.mod.OperationOptions.ManageBuyOffer | typingsJapgolly.stellarBase.mod.OperationOptions.SetOptions[scala.Nothing] | typingsJapgolly.stellarBase.mod.OperationOptions.ChangeTrust | typingsJapgolly.stellarBase.mod.OperationOptions.AllowTrust | typingsJapgolly.stellarBase.mod.OperationOptions.AccountMerge | typingsJapgolly.stellarBase.mod.OperationOptions.Inflation | typingsJapgolly.stellarBase.mod.OperationOptions.ManageData | typingsJapgolly.stellarBase.mod.OperationOptions.BumpSequence
  type OperationType = typingsJapgolly.stellarBase.mod.OperationType.CreateAccount | typingsJapgolly.stellarBase.mod.OperationType.Payment | typingsJapgolly.stellarBase.mod.OperationType.PathPaymentStrictReceive | typingsJapgolly.stellarBase.mod.OperationType.PathPaymentStrictSend | typingsJapgolly.stellarBase.mod.OperationType.CreatePassiveSellOffer | typingsJapgolly.stellarBase.mod.OperationType.ManageSellOffer | typingsJapgolly.stellarBase.mod.OperationType.ManageBuyOffer | typingsJapgolly.stellarBase.mod.OperationType.SetOptions | typingsJapgolly.stellarBase.mod.OperationType.ChangeTrust | typingsJapgolly.stellarBase.mod.OperationType.AllowTrust | typingsJapgolly.stellarBase.mod.OperationType.AccountMerge | typingsJapgolly.stellarBase.mod.OperationType.Inflation | typingsJapgolly.stellarBase.mod.OperationType.ManageData | typingsJapgolly.stellarBase.mod.OperationType.BumpSequence
  type Signer = typingsJapgolly.stellarBase.mod.Signer.Ed25519PublicKey | typingsJapgolly.stellarBase.mod.Signer.Sha256Hash | typingsJapgolly.stellarBase.mod.Signer.PreAuthTx
  type SignerOptions = typingsJapgolly.stellarBase.mod.SignerOptions.Ed25519PublicKey | typingsJapgolly.stellarBase.mod.SignerOptions.Sha256Hash | typingsJapgolly.stellarBase.mod.SignerOptions.PreAuthTx
  type TransactionBuilder = typingsJapgolly.stellarBase.mod.TransactionBuilder_
}
