package typingsJapgolly.breeze.mod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("breeze", "AutoGeneratedKeyType")
@js.native
class AutoGeneratedKeyType ()
  extends typingsJapgolly.breeze.breeze.AutoGeneratedKeyType

/* static members */
@JSImport("breeze", "AutoGeneratedKeyType")
@js.native
object AutoGeneratedKeyType extends js.Object {
  var Identity: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
  var KeyGenerator: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
  var None: typingsJapgolly.breeze.breeze.AutoGeneratedKeyType = js.native
}

