package typingsJapgolly.atAngularCore.testingTestingMod

import typingsJapgolly.atAngularCore.atAngularCoreMod.Compiler
import typingsJapgolly.atAngularCore.atAngularCoreMod.Component
import typingsJapgolly.atAngularCore.atAngularCoreMod.ComponentFactory
import typingsJapgolly.atAngularCore.atAngularCoreMod.Directive
import typingsJapgolly.atAngularCore.atAngularCoreMod.Injector
import typingsJapgolly.atAngularCore.atAngularCoreMod.NgModule
import typingsJapgolly.atAngularCore.atAngularCoreMod.Pipe
import typingsJapgolly.atAngularCore.atAngularCoreMod.Type
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@angular/core/testing/testing", "ɵTestingCompiler")
@js.native
class ɵTestingCompiler () extends Compiler {
  val injector: Injector = js.native
  /**
    * Gets the component factory for the given component.
    * This assumes that the component has been compiled before calling this call using
    * `compileModuleAndAllComponents*`.
    */
  def getComponentFactory[T](component: Type[T]): ComponentFactory[T] = js.native
  /**
    * Returns the component type that is stored in the given error.
    * This can be used for errors created by compileModule...
    */
  def getComponentFromError(error: js.Error): Type[_] | Null = js.native
  /**
    * Allows to pass the compile summary from AOT compilation to the JIT compiler,
    * so that it can use the code generated by AOT.
    */
  def loadAotSummaries(summaries: js.Function0[js.Array[_]]): Unit = js.native
  def overrideComponent(component: Type[_], overrides: MetadataOverride[Component]): Unit = js.native
  def overrideDirective(directive: Type[_], overrides: MetadataOverride[Directive]): Unit = js.native
  def overrideModule(module: Type[_], overrides: MetadataOverride[NgModule]): Unit = js.native
  def overridePipe(directive: Type[_], overrides: MetadataOverride[Pipe]): Unit = js.native
}

