package typingsJapgolly.semanticUiPopup.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object PopupSettings {
  type Param = (typingsJapgolly.semanticUiPopup.PickImplpopup | typingsJapgolly.semanticUiPopup.PickImplexclusive | typingsJapgolly.semanticUiPopup.PickImplmovePopup | typingsJapgolly.semanticUiPopup.PickImplobserveChanges | typingsJapgolly.semanticUiPopup.PickImplboundary | typingsJapgolly.semanticUiPopup.PickImplcontext | typingsJapgolly.semanticUiPopup.PickImplscrollContext | typingsJapgolly.semanticUiPopup.PickImpljitter | typingsJapgolly.semanticUiPopup.PickImplposition | typingsJapgolly.semanticUiPopup.PickImplinline | typingsJapgolly.semanticUiPopup.PickImplpreserve | typingsJapgolly.semanticUiPopup.PickImplprefer | typingsJapgolly.semanticUiPopup.PickImpllastResort | typingsJapgolly.semanticUiPopup.PickImplon | typingsJapgolly.semanticUiPopup.PickImpldelay | typingsJapgolly.semanticUiPopup.PickImpltransition | typingsJapgolly.semanticUiPopup.PickImplduration | typingsJapgolly.semanticUiPopup.PickImplsetFluidWidth | typingsJapgolly.semanticUiPopup.PickImplhoverable | typingsJapgolly.semanticUiPopup.PickImplclosable | typingsJapgolly.semanticUiPopup.PickImpladdTouchEvents | typingsJapgolly.semanticUiPopup.PickImplhideOnScroll | typingsJapgolly.semanticUiPopup.PickImpltarget | typingsJapgolly.semanticUiPopup.PickImpldistanceAway | typingsJapgolly.semanticUiPopup.PickImploffset | typingsJapgolly.semanticUiPopup.PickImplmaxSearchDepth | typingsJapgolly.semanticUiPopup.PickImplonCreate | typingsJapgolly.semanticUiPopup.PickImplonRemove | typingsJapgolly.semanticUiPopup.PickImplonShow | typingsJapgolly.semanticUiPopup.PickImplonVisible | typingsJapgolly.semanticUiPopup.PickImplonHide | typingsJapgolly.semanticUiPopup.PickImplonHidden | typingsJapgolly.semanticUiPopup.PickImplonUnplaceable | typingsJapgolly.semanticUiPopup.PickImplvariation | typingsJapgolly.semanticUiPopup.PickImplcontent | typingsJapgolly.semanticUiPopup.PickImpltitle | typingsJapgolly.semanticUiPopup.PickImplhtml | typingsJapgolly.semanticUiPopup.PickImplselector | typingsJapgolly.semanticUiPopup.PickImplmetadata | typingsJapgolly.semanticUiPopup.PickImplclassName | typingsJapgolly.semanticUiPopup.PickImplerror | typingsJapgolly.semanticUiPopup.PickImplnamespace | typingsJapgolly.semanticUiPopup.PickImplname | typingsJapgolly.semanticUiPopup.PickImplsilent | typingsJapgolly.semanticUiPopup.PickImpldebug | typingsJapgolly.semanticUiPopup.PickImplperformance | typingsJapgolly.semanticUiPopup.PickImplverbose) with typingsJapgolly.semanticUiPopup.PartialPickImplkeyofImpl
}
