package typingsJapgolly.semanticUiApi.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object ApiSettings {
  type Param = (typingsJapgolly.semanticUiApi.PickImplapi | typingsJapgolly.semanticUiApi.PickImplon | typingsJapgolly.semanticUiApi.PickImplcache | typingsJapgolly.semanticUiApi.PickImplstateContext | typingsJapgolly.semanticUiApi.PickImplencodeParameters | typingsJapgolly.semanticUiApi.PickImpldefaultData | typingsJapgolly.semanticUiApi.PickImplserializeForm | typingsJapgolly.semanticUiApi.PickImplthrottle | typingsJapgolly.semanticUiApi.PickImplthrottleFirstRequ | typingsJapgolly.semanticUiApi.PickImplinterruptRequests | typingsJapgolly.semanticUiApi.PickImplloadingDuration | typingsJapgolly.semanticUiApi.PickImplhideError | typingsJapgolly.semanticUiApi.PickImplerrorDuration | typingsJapgolly.semanticUiApi.PickImplaction | typingsJapgolly.semanticUiApi.PickImplurl | typingsJapgolly.semanticUiApi.PickImplurlData | typingsJapgolly.semanticUiApi.PickImplresponse | typingsJapgolly.semanticUiApi.PickImplresponseAsync | typingsJapgolly.semanticUiApi.PickImplmockResponse | typingsJapgolly.semanticUiApi.PickImplmockResponseAsync | typingsJapgolly.semanticUiApi.PickImplmethod | typingsJapgolly.semanticUiApi.PickImpldataType | typingsJapgolly.semanticUiApi.PickImpldata | typingsJapgolly.semanticUiApi.PickImplbeforeSend | typingsJapgolly.semanticUiApi.PickImplbeforeXHR | typingsJapgolly.semanticUiApi.PickImplonRequest | typingsJapgolly.semanticUiApi.PickImplonResponse | typingsJapgolly.semanticUiApi.PickImplsuccessTest | typingsJapgolly.semanticUiApi.PickImplonSuccess | typingsJapgolly.semanticUiApi.PickImplonComplete | typingsJapgolly.semanticUiApi.PickImplonFailure | typingsJapgolly.semanticUiApi.PickImplonError | typingsJapgolly.semanticUiApi.PickImplonAbort | typingsJapgolly.semanticUiApi.PickImplregExp | typingsJapgolly.semanticUiApi.PickImplselector | typingsJapgolly.semanticUiApi.PickImplclassName | typingsJapgolly.semanticUiApi.PickImplmetadata | typingsJapgolly.semanticUiApi.PickImplerror | typingsJapgolly.semanticUiApi.PickImplnamespace | typingsJapgolly.semanticUiApi.PickImplname | typingsJapgolly.semanticUiApi.PickImplsilent | typingsJapgolly.semanticUiApi.PickImpldebug | typingsJapgolly.semanticUiApi.PickImplperformance | typingsJapgolly.semanticUiApi.PickImplverbose) with typingsJapgolly.semanticUiApi.PartialPickImplkeyofImpl
}
