package typingsJapgolly.stardustUiReactComponentEventListener

import japgolly.scalajs.react.raw.React.RefHandle
import org.scalajs.dom.raw.Node
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.abort
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.animationcancel
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.animationend
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.animationiteration
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.animationstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.auxclick
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.blur
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.cancel
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.canplay
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.canplaythrough
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.change
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.click
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.close
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.contextmenu
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.copy
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.cuechange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.cut
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dblclick
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.drag
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragend
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragenter
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragexit
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragleave
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragover
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.dragstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.drop
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.durationchange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.emptied
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.ended
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.error
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.focus
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.focusin
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.focusout
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.fullscreenchange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.fullscreenerror
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.gotpointercapture
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.input
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.invalid
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.keydown
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.keypress
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.keyup
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.load
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.loadeddata
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.loadedmetadata
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.loadstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.lostpointercapture
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mousedown
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mouseenter
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mouseleave
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mousemove
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mouseout
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mouseover
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.mouseup
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.paste
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pause
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.play
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.playing
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointercancel
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerdown
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerenter
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerleave
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerlockchange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerlockerror
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointermove
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerout
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerover
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerup
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.progress
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.ratechange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.readystatechange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.reset
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.resize
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.scroll
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.securitypolicyviolation
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.seeked
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.seeking
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.select
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.selectionchange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.selectstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.stalled
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.submit
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.suspend
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.timeupdate
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.toggle
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.touchcancel
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.touchend
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.touchmove
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.touchstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.transitioncancel
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.transitionend
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.transitionrun
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.transitionstart
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.visibilitychange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.volumechange
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.waiting
import typingsJapgolly.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.wheel
import typingsJapgolly.stardustUiReactComponentEventListener.typesMod.EventListenerOptions
import typingsJapgolly.std.Window_
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@stardust-ui/react-component-event-listener", JSImport.Namespace)
@js.native
object mod extends js.Object {
  val documentRef: RefHandle[Node | Window_] = js.native
  val windowRef: RefHandle[Node | Window_] = js.native
  def useEventListener[T /* <: /* import warning: LimitUnionLength.leaveTypeRef Was union type with length 91 */ js.Any */](options: EventListenerOptions[T]): Unit = js.native
  @js.native
  object EventListener extends js.Object {
    var displayName: String = js.native
    var propTypes: AnonCapture | AnonListener = js.native
    def apply(
      props: EventListenerOptions[
          abort | animationcancel | animationend | animationiteration | animationstart | auxclick | blur | cancel | canplay | canplaythrough | change | click | close | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragexit | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointerlockchange | pointerlockerror | pointermove | pointerout | pointerover | pointerup | progress | ratechange | readystatechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | visibilitychange | volumechange | waiting | wheel
        ]
    ): js.Any = js.native
    @js.native
    object defaultProps extends js.Object {
      var capture: Boolean = js.native
    }
    
  }
  
}

