package typingsJapgolly.awsSdkClientCodecommitNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesPullRequestSourceReferenceUpdatedEventMetadataMod {
  type UnmarshalledPullRequestSourceReferenceUpdatedEventMetadata = typingsJapgolly.awsSdkClientCodecommitNode.typesPullRequestSourceReferenceUpdatedEventMetadataMod.PullRequestSourceReferenceUpdatedEventMetadata
}
