package typingsJapgolly.tensorflowTfjsConverter

import typingsJapgolly.tensorflowTfjsConverter.anon.Typeofio
import typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.Url
import typingsJapgolly.tensorflowTfjsConverter.distOperationsTypesMod.OpExecutor
import typingsJapgolly.tensorflowTfjsCore.distIoTypesMod.IOHandler
import typingsJapgolly.tensorflowTfjsCore.distIoTypesMod.IOHandlerSync
import typingsJapgolly.tensorflowTfjsCore.distIoTypesMod.LoadOptions
import typingsJapgolly.tensorflowTfjsCore.distIoTypesMod.ModelArtifacts
import typingsJapgolly.tensorflowTfjsCore.distIoTypesMod.ModelJSON
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object mod {
  
  @JSImport("@tensorflow/tfjs-converter", JSImport.Namespace)
  @js.native
  val ^ : js.Any = js.native
  
  @JSImport("@tensorflow/tfjs-converter", "GraphModel")
  @js.native
  open class GraphModel[ModelURL /* <: Url */] protected ()
    extends typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[ModelURL] {
    /**
      * @param modelUrl url for the model, or an `io.IOHandler`.
      * @param weightManifestUrl url for the weight file generated by
      * scripts/convert.py script.
      * @param requestOption options for Request, which allows to send credentials
      * and custom headers.
      * @param onProgress Optional, progress callback function, fired periodically
      * before the load is completed.
      */
    def this(modelUrl: ModelURL) = this()
    def this(modelUrl: ModelURL, loadOptions: LoadOptions) = this()
    def this(modelUrl: ModelURL, loadOptions: Unit, tfio: Typeofio) = this()
    def this(modelUrl: ModelURL, loadOptions: LoadOptions, tfio: Typeofio) = this()
  }
  
  inline def deregisterOp(name: String): Unit = ^.asInstanceOf[js.Dynamic].applyDynamic("deregisterOp")(name.asInstanceOf[js.Any]).asInstanceOf[Unit]
  
  inline def loadGraphModel(modelUrl: String): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any]).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: String, options: Unit, tfio: Typeofio): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any], tfio.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: String, options: LoadOptions): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: String, options: LoadOptions, tfio: Typeofio): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any], tfio.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: IOHandler): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any]).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: IOHandler, options: Unit, tfio: Typeofio): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any], tfio.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: IOHandler, options: LoadOptions): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  inline def loadGraphModel(modelUrl: IOHandler, options: LoadOptions, tfio: Typeofio): js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ] = (^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModel")(modelUrl.asInstanceOf[js.Any], options.asInstanceOf[js.Any], tfio.asInstanceOf[js.Any])).asInstanceOf[js.Promise[
    typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[String | IOHandler]
  ]]
  
  inline def loadGraphModelSync(modelSource: js.Tuple2[ModelJSON, /* Weights */ js.typedarray.ArrayBuffer]): typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModelSync")(modelSource.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync]]
  inline def loadGraphModelSync(modelSource: IOHandlerSync): typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModelSync")(modelSource.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync]]
  inline def loadGraphModelSync(modelSource: ModelArtifacts): typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync] = ^.asInstanceOf[js.Dynamic].applyDynamic("loadGraphModelSync")(modelSource.asInstanceOf[js.Any]).asInstanceOf[typingsJapgolly.tensorflowTfjsConverter.distExecutorGraphModelMod.GraphModel[IOHandlerSync]]
  
  inline def registerOp(name: String, opFunc: OpExecutor): Unit = (^.asInstanceOf[js.Dynamic].applyDynamic("registerOp")(name.asInstanceOf[js.Any], opFunc.asInstanceOf[js.Any])).asInstanceOf[Unit]
  
  @JSImport("@tensorflow/tfjs-converter", "version_converter")
  @js.native
  val versionConverter: /* "4.0.0" */ String = js.native
}
