package typingsJapgolly.preact.mod.h.JSX

import org.scalajs.dom.raw.EventTarget
import typingsJapgolly.preact.AnonHtml
import typingsJapgolly.preact.mod.ComponentChildren
import typingsJapgolly.preact.mod.PreactDOMAttributes
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait DOMAttributes[Target /* <: EventTarget */] extends PreactDOMAttributes {
  // Media Events
  var onAbort: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onAbortCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onAnimationEnd: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationEndCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationIteration: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationIterationCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  // Animation Events
  var onAnimationStart: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationStartCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onBlur: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onBlurCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onCanPlay: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayThrough: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Form Events
  var onChange: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onChangeCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // MouseEvents
  var onClick: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onClickCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  // Composition Events
  var onCompositionEnd: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionEndCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionStart: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionStartCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionUpdate: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionUpdateCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onContextMenu: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onContextMenuCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  // Clipboard Events
  var onCopy: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCopyCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCut: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCutCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onDblClick: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onDblClickCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onDrag: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnd: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEndCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnter: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnterCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragExit: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragExitCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragLeave: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragLeaveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragOver: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragOverCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragStart: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragStartCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDrop: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDropCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDurationChange: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onDurationChangeCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEmptied: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEmptiedCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEncrypted: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEncryptedCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEnded: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEndedCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onError: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onErrorCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Focus Events
  var onFocus: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onFocusCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onFormData: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onFormDataCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onGotPointerCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onGotPointerCaptureCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onInput: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInputCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInvalid: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInvalidCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Keyboard Events
  var onKeyDown: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyDownCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyPress: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyPressCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyUp: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyUpCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  // Image Events
  var onLoad: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadStart: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadStartCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedData: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedDataCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedMetadata: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLostPointerCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onLostPointerCaptureCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onMouseDown: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseDownCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseEnter: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseEnterCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseLeave: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseLeaveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseMove: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseMoveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOut: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOutCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOver: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOverCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseUp: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseUpCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onPaste: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onPasteCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onPause: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPauseCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlay: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlayCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlaying: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlayingCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPointerCancel: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerCancelCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerDown: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerDownCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerEnter: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerEnterCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerLeave: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerMove: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerMoveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOut: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOutCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  // Pointer Events
  var onPointerOver: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOverCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerUp: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerUpCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onProgress: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onProgressCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onRateChange: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onRateChangeCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onReset: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onResetCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // UI Events
  var onScroll: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.UIEventHandler[Target]] = js.undefined
  var onScrollCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.UIEventHandler[Target]] = js.undefined
  var onSearch: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSearchCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeeked: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeekedCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeeking: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeekingCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Selection Events
  var onSelect: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSelectCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onStalled: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onStalledCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSubmit: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSubmitCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSuspend: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSuspendCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onTimeUpdate: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Details Events
  var onToggle: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Touch Events
  var onTouchCancel: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchCancelCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchEnd: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchEndCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchMove: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchMoveCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchStart: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchStartCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  // Transition Events
  var onTransitionEnd: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TransitionEventHandler[Target]] = js.undefined
  var onTransitionEndCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.TransitionEventHandler[Target]] = js.undefined
  var onVolumeChange: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onWaiting: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onWaitingCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Wheel Events
  var onWheel: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.WheelEventHandler[Target]] = js.undefined
  var onWheelCapture: js.UndefOr[typingsJapgolly.preact.jsxMod.JSXInternal.WheelEventHandler[Target]] = js.undefined
}

object DOMAttributes {
  @scala.inline
  def apply[Target /* <: EventTarget */](
    children: ComponentChildren = null,
    dangerouslySetInnerHTML: AnonHtml = null,
    onAbort: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onAbortCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onAnimationEnd: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationEndCapture: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationIteration: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationIterationCapture: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationStart: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationStartCapture: typingsJapgolly.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onBlur: typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onBlurCapture: typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onCanPlay: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayThrough: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayThroughCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onChange: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onChangeCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onClick: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onClickCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onCompositionEnd: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionEndCapture: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionStart: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionStartCapture: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionUpdate: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionUpdateCapture: typingsJapgolly.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onContextMenu: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onContextMenuCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onCopy: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCopyCapture: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCut: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCutCapture: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onDblClick: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onDblClickCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onDrag: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnd: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEndCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnter: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnterCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragExit: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragExitCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragLeave: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragLeaveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragOver: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragOverCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragStart: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragStartCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDrop: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDropCapture: typingsJapgolly.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDurationChange: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onDurationChangeCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEmptied: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEmptiedCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEncrypted: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEncryptedCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEnded: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEndedCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onError: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onErrorCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onFocus: typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onFocusCapture: typingsJapgolly.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onFormData: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onFormDataCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onGotPointerCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onGotPointerCaptureCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onInput: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInputCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInvalid: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInvalidCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onKeyDown: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyDownCapture: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyPress: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyPressCapture: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyUp: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyUpCapture: typingsJapgolly.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onLoad: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadStart: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadStartCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedData: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedDataCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedMetadata: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedMetadataCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLostPointerCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onLostPointerCaptureCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onMouseDown: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseDownCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseEnter: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseEnterCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseLeave: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseLeaveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseMove: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseMoveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOut: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOutCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOver: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOverCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseUp: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseUpCapture: typingsJapgolly.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onPaste: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onPasteCapture: typingsJapgolly.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onPause: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPauseCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlay: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlayCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlaying: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlayingCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPointerCancel: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerCancelCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerDown: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerDownCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerEnter: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerEnterCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerLeave: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerLeaveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerMove: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerMoveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOut: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOutCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOver: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOverCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerUp: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerUpCapture: typingsJapgolly.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onProgress: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onProgressCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onRateChange: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onRateChangeCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onReset: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onResetCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onScroll: typingsJapgolly.preact.jsxMod.JSXInternal.UIEventHandler[Target] = null,
    onScrollCapture: typingsJapgolly.preact.jsxMod.JSXInternal.UIEventHandler[Target] = null,
    onSearch: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSearchCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeeked: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeekedCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeeking: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeekingCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSelect: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSelectCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onStalled: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onStalledCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSubmit: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSubmitCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSuspend: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSuspendCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTimeUpdate: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTimeUpdateCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onToggle: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTouchCancel: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchCancelCapture: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchEnd: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchEndCapture: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchMove: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchMoveCapture: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchStart: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchStartCapture: typingsJapgolly.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTransitionEnd: typingsJapgolly.preact.jsxMod.JSXInternal.TransitionEventHandler[Target] = null,
    onTransitionEndCapture: typingsJapgolly.preact.jsxMod.JSXInternal.TransitionEventHandler[Target] = null,
    onVolumeChange: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onVolumeChangeCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWaiting: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWaitingCapture: typingsJapgolly.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWheel: typingsJapgolly.preact.jsxMod.JSXInternal.WheelEventHandler[Target] = null,
    onWheelCapture: typingsJapgolly.preact.jsxMod.JSXInternal.WheelEventHandler[Target] = null
  ): DOMAttributes[Target] = {
    val __obj = js.Dynamic.literal()
    if (children != null) __obj.updateDynamic("children")(children.asInstanceOf[js.Any])
    if (dangerouslySetInnerHTML != null) __obj.updateDynamic("dangerouslySetInnerHTML")(dangerouslySetInnerHTML.asInstanceOf[js.Any])
    if (onAbort != null) __obj.updateDynamic("onAbort")(onAbort.asInstanceOf[js.Any])
    if (onAbortCapture != null) __obj.updateDynamic("onAbortCapture")(onAbortCapture.asInstanceOf[js.Any])
    if (onAnimationEnd != null) __obj.updateDynamic("onAnimationEnd")(onAnimationEnd.asInstanceOf[js.Any])
    if (onAnimationEndCapture != null) __obj.updateDynamic("onAnimationEndCapture")(onAnimationEndCapture.asInstanceOf[js.Any])
    if (onAnimationIteration != null) __obj.updateDynamic("onAnimationIteration")(onAnimationIteration.asInstanceOf[js.Any])
    if (onAnimationIterationCapture != null) __obj.updateDynamic("onAnimationIterationCapture")(onAnimationIterationCapture.asInstanceOf[js.Any])
    if (onAnimationStart != null) __obj.updateDynamic("onAnimationStart")(onAnimationStart.asInstanceOf[js.Any])
    if (onAnimationStartCapture != null) __obj.updateDynamic("onAnimationStartCapture")(onAnimationStartCapture.asInstanceOf[js.Any])
    if (onBlur != null) __obj.updateDynamic("onBlur")(onBlur.asInstanceOf[js.Any])
    if (onBlurCapture != null) __obj.updateDynamic("onBlurCapture")(onBlurCapture.asInstanceOf[js.Any])
    if (onCanPlay != null) __obj.updateDynamic("onCanPlay")(onCanPlay.asInstanceOf[js.Any])
    if (onCanPlayCapture != null) __obj.updateDynamic("onCanPlayCapture")(onCanPlayCapture.asInstanceOf[js.Any])
    if (onCanPlayThrough != null) __obj.updateDynamic("onCanPlayThrough")(onCanPlayThrough.asInstanceOf[js.Any])
    if (onCanPlayThroughCapture != null) __obj.updateDynamic("onCanPlayThroughCapture")(onCanPlayThroughCapture.asInstanceOf[js.Any])
    if (onChange != null) __obj.updateDynamic("onChange")(onChange.asInstanceOf[js.Any])
    if (onChangeCapture != null) __obj.updateDynamic("onChangeCapture")(onChangeCapture.asInstanceOf[js.Any])
    if (onClick != null) __obj.updateDynamic("onClick")(onClick.asInstanceOf[js.Any])
    if (onClickCapture != null) __obj.updateDynamic("onClickCapture")(onClickCapture.asInstanceOf[js.Any])
    if (onCompositionEnd != null) __obj.updateDynamic("onCompositionEnd")(onCompositionEnd.asInstanceOf[js.Any])
    if (onCompositionEndCapture != null) __obj.updateDynamic("onCompositionEndCapture")(onCompositionEndCapture.asInstanceOf[js.Any])
    if (onCompositionStart != null) __obj.updateDynamic("onCompositionStart")(onCompositionStart.asInstanceOf[js.Any])
    if (onCompositionStartCapture != null) __obj.updateDynamic("onCompositionStartCapture")(onCompositionStartCapture.asInstanceOf[js.Any])
    if (onCompositionUpdate != null) __obj.updateDynamic("onCompositionUpdate")(onCompositionUpdate.asInstanceOf[js.Any])
    if (onCompositionUpdateCapture != null) __obj.updateDynamic("onCompositionUpdateCapture")(onCompositionUpdateCapture.asInstanceOf[js.Any])
    if (onContextMenu != null) __obj.updateDynamic("onContextMenu")(onContextMenu.asInstanceOf[js.Any])
    if (onContextMenuCapture != null) __obj.updateDynamic("onContextMenuCapture")(onContextMenuCapture.asInstanceOf[js.Any])
    if (onCopy != null) __obj.updateDynamic("onCopy")(onCopy.asInstanceOf[js.Any])
    if (onCopyCapture != null) __obj.updateDynamic("onCopyCapture")(onCopyCapture.asInstanceOf[js.Any])
    if (onCut != null) __obj.updateDynamic("onCut")(onCut.asInstanceOf[js.Any])
    if (onCutCapture != null) __obj.updateDynamic("onCutCapture")(onCutCapture.asInstanceOf[js.Any])
    if (onDblClick != null) __obj.updateDynamic("onDblClick")(onDblClick.asInstanceOf[js.Any])
    if (onDblClickCapture != null) __obj.updateDynamic("onDblClickCapture")(onDblClickCapture.asInstanceOf[js.Any])
    if (onDrag != null) __obj.updateDynamic("onDrag")(onDrag.asInstanceOf[js.Any])
    if (onDragCapture != null) __obj.updateDynamic("onDragCapture")(onDragCapture.asInstanceOf[js.Any])
    if (onDragEnd != null) __obj.updateDynamic("onDragEnd")(onDragEnd.asInstanceOf[js.Any])
    if (onDragEndCapture != null) __obj.updateDynamic("onDragEndCapture")(onDragEndCapture.asInstanceOf[js.Any])
    if (onDragEnter != null) __obj.updateDynamic("onDragEnter")(onDragEnter.asInstanceOf[js.Any])
    if (onDragEnterCapture != null) __obj.updateDynamic("onDragEnterCapture")(onDragEnterCapture.asInstanceOf[js.Any])
    if (onDragExit != null) __obj.updateDynamic("onDragExit")(onDragExit.asInstanceOf[js.Any])
    if (onDragExitCapture != null) __obj.updateDynamic("onDragExitCapture")(onDragExitCapture.asInstanceOf[js.Any])
    if (onDragLeave != null) __obj.updateDynamic("onDragLeave")(onDragLeave.asInstanceOf[js.Any])
    if (onDragLeaveCapture != null) __obj.updateDynamic("onDragLeaveCapture")(onDragLeaveCapture.asInstanceOf[js.Any])
    if (onDragOver != null) __obj.updateDynamic("onDragOver")(onDragOver.asInstanceOf[js.Any])
    if (onDragOverCapture != null) __obj.updateDynamic("onDragOverCapture")(onDragOverCapture.asInstanceOf[js.Any])
    if (onDragStart != null) __obj.updateDynamic("onDragStart")(onDragStart.asInstanceOf[js.Any])
    if (onDragStartCapture != null) __obj.updateDynamic("onDragStartCapture")(onDragStartCapture.asInstanceOf[js.Any])
    if (onDrop != null) __obj.updateDynamic("onDrop")(onDrop.asInstanceOf[js.Any])
    if (onDropCapture != null) __obj.updateDynamic("onDropCapture")(onDropCapture.asInstanceOf[js.Any])
    if (onDurationChange != null) __obj.updateDynamic("onDurationChange")(onDurationChange.asInstanceOf[js.Any])
    if (onDurationChangeCapture != null) __obj.updateDynamic("onDurationChangeCapture")(onDurationChangeCapture.asInstanceOf[js.Any])
    if (onEmptied != null) __obj.updateDynamic("onEmptied")(onEmptied.asInstanceOf[js.Any])
    if (onEmptiedCapture != null) __obj.updateDynamic("onEmptiedCapture")(onEmptiedCapture.asInstanceOf[js.Any])
    if (onEncrypted != null) __obj.updateDynamic("onEncrypted")(onEncrypted.asInstanceOf[js.Any])
    if (onEncryptedCapture != null) __obj.updateDynamic("onEncryptedCapture")(onEncryptedCapture.asInstanceOf[js.Any])
    if (onEnded != null) __obj.updateDynamic("onEnded")(onEnded.asInstanceOf[js.Any])
    if (onEndedCapture != null) __obj.updateDynamic("onEndedCapture")(onEndedCapture.asInstanceOf[js.Any])
    if (onError != null) __obj.updateDynamic("onError")(onError.asInstanceOf[js.Any])
    if (onErrorCapture != null) __obj.updateDynamic("onErrorCapture")(onErrorCapture.asInstanceOf[js.Any])
    if (onFocus != null) __obj.updateDynamic("onFocus")(onFocus.asInstanceOf[js.Any])
    if (onFocusCapture != null) __obj.updateDynamic("onFocusCapture")(onFocusCapture.asInstanceOf[js.Any])
    if (onFormData != null) __obj.updateDynamic("onFormData")(onFormData.asInstanceOf[js.Any])
    if (onFormDataCapture != null) __obj.updateDynamic("onFormDataCapture")(onFormDataCapture.asInstanceOf[js.Any])
    if (onGotPointerCapture != null) __obj.updateDynamic("onGotPointerCapture")(onGotPointerCapture.asInstanceOf[js.Any])
    if (onGotPointerCaptureCapture != null) __obj.updateDynamic("onGotPointerCaptureCapture")(onGotPointerCaptureCapture.asInstanceOf[js.Any])
    if (onInput != null) __obj.updateDynamic("onInput")(onInput.asInstanceOf[js.Any])
    if (onInputCapture != null) __obj.updateDynamic("onInputCapture")(onInputCapture.asInstanceOf[js.Any])
    if (onInvalid != null) __obj.updateDynamic("onInvalid")(onInvalid.asInstanceOf[js.Any])
    if (onInvalidCapture != null) __obj.updateDynamic("onInvalidCapture")(onInvalidCapture.asInstanceOf[js.Any])
    if (onKeyDown != null) __obj.updateDynamic("onKeyDown")(onKeyDown.asInstanceOf[js.Any])
    if (onKeyDownCapture != null) __obj.updateDynamic("onKeyDownCapture")(onKeyDownCapture.asInstanceOf[js.Any])
    if (onKeyPress != null) __obj.updateDynamic("onKeyPress")(onKeyPress.asInstanceOf[js.Any])
    if (onKeyPressCapture != null) __obj.updateDynamic("onKeyPressCapture")(onKeyPressCapture.asInstanceOf[js.Any])
    if (onKeyUp != null) __obj.updateDynamic("onKeyUp")(onKeyUp.asInstanceOf[js.Any])
    if (onKeyUpCapture != null) __obj.updateDynamic("onKeyUpCapture")(onKeyUpCapture.asInstanceOf[js.Any])
    if (onLoad != null) __obj.updateDynamic("onLoad")(onLoad.asInstanceOf[js.Any])
    if (onLoadCapture != null) __obj.updateDynamic("onLoadCapture")(onLoadCapture.asInstanceOf[js.Any])
    if (onLoadStart != null) __obj.updateDynamic("onLoadStart")(onLoadStart.asInstanceOf[js.Any])
    if (onLoadStartCapture != null) __obj.updateDynamic("onLoadStartCapture")(onLoadStartCapture.asInstanceOf[js.Any])
    if (onLoadedData != null) __obj.updateDynamic("onLoadedData")(onLoadedData.asInstanceOf[js.Any])
    if (onLoadedDataCapture != null) __obj.updateDynamic("onLoadedDataCapture")(onLoadedDataCapture.asInstanceOf[js.Any])
    if (onLoadedMetadata != null) __obj.updateDynamic("onLoadedMetadata")(onLoadedMetadata.asInstanceOf[js.Any])
    if (onLoadedMetadataCapture != null) __obj.updateDynamic("onLoadedMetadataCapture")(onLoadedMetadataCapture.asInstanceOf[js.Any])
    if (onLostPointerCapture != null) __obj.updateDynamic("onLostPointerCapture")(onLostPointerCapture.asInstanceOf[js.Any])
    if (onLostPointerCaptureCapture != null) __obj.updateDynamic("onLostPointerCaptureCapture")(onLostPointerCaptureCapture.asInstanceOf[js.Any])
    if (onMouseDown != null) __obj.updateDynamic("onMouseDown")(onMouseDown.asInstanceOf[js.Any])
    if (onMouseDownCapture != null) __obj.updateDynamic("onMouseDownCapture")(onMouseDownCapture.asInstanceOf[js.Any])
    if (onMouseEnter != null) __obj.updateDynamic("onMouseEnter")(onMouseEnter.asInstanceOf[js.Any])
    if (onMouseEnterCapture != null) __obj.updateDynamic("onMouseEnterCapture")(onMouseEnterCapture.asInstanceOf[js.Any])
    if (onMouseLeave != null) __obj.updateDynamic("onMouseLeave")(onMouseLeave.asInstanceOf[js.Any])
    if (onMouseLeaveCapture != null) __obj.updateDynamic("onMouseLeaveCapture")(onMouseLeaveCapture.asInstanceOf[js.Any])
    if (onMouseMove != null) __obj.updateDynamic("onMouseMove")(onMouseMove.asInstanceOf[js.Any])
    if (onMouseMoveCapture != null) __obj.updateDynamic("onMouseMoveCapture")(onMouseMoveCapture.asInstanceOf[js.Any])
    if (onMouseOut != null) __obj.updateDynamic("onMouseOut")(onMouseOut.asInstanceOf[js.Any])
    if (onMouseOutCapture != null) __obj.updateDynamic("onMouseOutCapture")(onMouseOutCapture.asInstanceOf[js.Any])
    if (onMouseOver != null) __obj.updateDynamic("onMouseOver")(onMouseOver.asInstanceOf[js.Any])
    if (onMouseOverCapture != null) __obj.updateDynamic("onMouseOverCapture")(onMouseOverCapture.asInstanceOf[js.Any])
    if (onMouseUp != null) __obj.updateDynamic("onMouseUp")(onMouseUp.asInstanceOf[js.Any])
    if (onMouseUpCapture != null) __obj.updateDynamic("onMouseUpCapture")(onMouseUpCapture.asInstanceOf[js.Any])
    if (onPaste != null) __obj.updateDynamic("onPaste")(onPaste.asInstanceOf[js.Any])
    if (onPasteCapture != null) __obj.updateDynamic("onPasteCapture")(onPasteCapture.asInstanceOf[js.Any])
    if (onPause != null) __obj.updateDynamic("onPause")(onPause.asInstanceOf[js.Any])
    if (onPauseCapture != null) __obj.updateDynamic("onPauseCapture")(onPauseCapture.asInstanceOf[js.Any])
    if (onPlay != null) __obj.updateDynamic("onPlay")(onPlay.asInstanceOf[js.Any])
    if (onPlayCapture != null) __obj.updateDynamic("onPlayCapture")(onPlayCapture.asInstanceOf[js.Any])
    if (onPlaying != null) __obj.updateDynamic("onPlaying")(onPlaying.asInstanceOf[js.Any])
    if (onPlayingCapture != null) __obj.updateDynamic("onPlayingCapture")(onPlayingCapture.asInstanceOf[js.Any])
    if (onPointerCancel != null) __obj.updateDynamic("onPointerCancel")(onPointerCancel.asInstanceOf[js.Any])
    if (onPointerCancelCapture != null) __obj.updateDynamic("onPointerCancelCapture")(onPointerCancelCapture.asInstanceOf[js.Any])
    if (onPointerDown != null) __obj.updateDynamic("onPointerDown")(onPointerDown.asInstanceOf[js.Any])
    if (onPointerDownCapture != null) __obj.updateDynamic("onPointerDownCapture")(onPointerDownCapture.asInstanceOf[js.Any])
    if (onPointerEnter != null) __obj.updateDynamic("onPointerEnter")(onPointerEnter.asInstanceOf[js.Any])
    if (onPointerEnterCapture != null) __obj.updateDynamic("onPointerEnterCapture")(onPointerEnterCapture.asInstanceOf[js.Any])
    if (onPointerLeave != null) __obj.updateDynamic("onPointerLeave")(onPointerLeave.asInstanceOf[js.Any])
    if (onPointerLeaveCapture != null) __obj.updateDynamic("onPointerLeaveCapture")(onPointerLeaveCapture.asInstanceOf[js.Any])
    if (onPointerMove != null) __obj.updateDynamic("onPointerMove")(onPointerMove.asInstanceOf[js.Any])
    if (onPointerMoveCapture != null) __obj.updateDynamic("onPointerMoveCapture")(onPointerMoveCapture.asInstanceOf[js.Any])
    if (onPointerOut != null) __obj.updateDynamic("onPointerOut")(onPointerOut.asInstanceOf[js.Any])
    if (onPointerOutCapture != null) __obj.updateDynamic("onPointerOutCapture")(onPointerOutCapture.asInstanceOf[js.Any])
    if (onPointerOver != null) __obj.updateDynamic("onPointerOver")(onPointerOver.asInstanceOf[js.Any])
    if (onPointerOverCapture != null) __obj.updateDynamic("onPointerOverCapture")(onPointerOverCapture.asInstanceOf[js.Any])
    if (onPointerUp != null) __obj.updateDynamic("onPointerUp")(onPointerUp.asInstanceOf[js.Any])
    if (onPointerUpCapture != null) __obj.updateDynamic("onPointerUpCapture")(onPointerUpCapture.asInstanceOf[js.Any])
    if (onProgress != null) __obj.updateDynamic("onProgress")(onProgress.asInstanceOf[js.Any])
    if (onProgressCapture != null) __obj.updateDynamic("onProgressCapture")(onProgressCapture.asInstanceOf[js.Any])
    if (onRateChange != null) __obj.updateDynamic("onRateChange")(onRateChange.asInstanceOf[js.Any])
    if (onRateChangeCapture != null) __obj.updateDynamic("onRateChangeCapture")(onRateChangeCapture.asInstanceOf[js.Any])
    if (onReset != null) __obj.updateDynamic("onReset")(onReset.asInstanceOf[js.Any])
    if (onResetCapture != null) __obj.updateDynamic("onResetCapture")(onResetCapture.asInstanceOf[js.Any])
    if (onScroll != null) __obj.updateDynamic("onScroll")(onScroll.asInstanceOf[js.Any])
    if (onScrollCapture != null) __obj.updateDynamic("onScrollCapture")(onScrollCapture.asInstanceOf[js.Any])
    if (onSearch != null) __obj.updateDynamic("onSearch")(onSearch.asInstanceOf[js.Any])
    if (onSearchCapture != null) __obj.updateDynamic("onSearchCapture")(onSearchCapture.asInstanceOf[js.Any])
    if (onSeeked != null) __obj.updateDynamic("onSeeked")(onSeeked.asInstanceOf[js.Any])
    if (onSeekedCapture != null) __obj.updateDynamic("onSeekedCapture")(onSeekedCapture.asInstanceOf[js.Any])
    if (onSeeking != null) __obj.updateDynamic("onSeeking")(onSeeking.asInstanceOf[js.Any])
    if (onSeekingCapture != null) __obj.updateDynamic("onSeekingCapture")(onSeekingCapture.asInstanceOf[js.Any])
    if (onSelect != null) __obj.updateDynamic("onSelect")(onSelect.asInstanceOf[js.Any])
    if (onSelectCapture != null) __obj.updateDynamic("onSelectCapture")(onSelectCapture.asInstanceOf[js.Any])
    if (onStalled != null) __obj.updateDynamic("onStalled")(onStalled.asInstanceOf[js.Any])
    if (onStalledCapture != null) __obj.updateDynamic("onStalledCapture")(onStalledCapture.asInstanceOf[js.Any])
    if (onSubmit != null) __obj.updateDynamic("onSubmit")(onSubmit.asInstanceOf[js.Any])
    if (onSubmitCapture != null) __obj.updateDynamic("onSubmitCapture")(onSubmitCapture.asInstanceOf[js.Any])
    if (onSuspend != null) __obj.updateDynamic("onSuspend")(onSuspend.asInstanceOf[js.Any])
    if (onSuspendCapture != null) __obj.updateDynamic("onSuspendCapture")(onSuspendCapture.asInstanceOf[js.Any])
    if (onTimeUpdate != null) __obj.updateDynamic("onTimeUpdate")(onTimeUpdate.asInstanceOf[js.Any])
    if (onTimeUpdateCapture != null) __obj.updateDynamic("onTimeUpdateCapture")(onTimeUpdateCapture.asInstanceOf[js.Any])
    if (onToggle != null) __obj.updateDynamic("onToggle")(onToggle.asInstanceOf[js.Any])
    if (onTouchCancel != null) __obj.updateDynamic("onTouchCancel")(onTouchCancel.asInstanceOf[js.Any])
    if (onTouchCancelCapture != null) __obj.updateDynamic("onTouchCancelCapture")(onTouchCancelCapture.asInstanceOf[js.Any])
    if (onTouchEnd != null) __obj.updateDynamic("onTouchEnd")(onTouchEnd.asInstanceOf[js.Any])
    if (onTouchEndCapture != null) __obj.updateDynamic("onTouchEndCapture")(onTouchEndCapture.asInstanceOf[js.Any])
    if (onTouchMove != null) __obj.updateDynamic("onTouchMove")(onTouchMove.asInstanceOf[js.Any])
    if (onTouchMoveCapture != null) __obj.updateDynamic("onTouchMoveCapture")(onTouchMoveCapture.asInstanceOf[js.Any])
    if (onTouchStart != null) __obj.updateDynamic("onTouchStart")(onTouchStart.asInstanceOf[js.Any])
    if (onTouchStartCapture != null) __obj.updateDynamic("onTouchStartCapture")(onTouchStartCapture.asInstanceOf[js.Any])
    if (onTransitionEnd != null) __obj.updateDynamic("onTransitionEnd")(onTransitionEnd.asInstanceOf[js.Any])
    if (onTransitionEndCapture != null) __obj.updateDynamic("onTransitionEndCapture")(onTransitionEndCapture.asInstanceOf[js.Any])
    if (onVolumeChange != null) __obj.updateDynamic("onVolumeChange")(onVolumeChange.asInstanceOf[js.Any])
    if (onVolumeChangeCapture != null) __obj.updateDynamic("onVolumeChangeCapture")(onVolumeChangeCapture.asInstanceOf[js.Any])
    if (onWaiting != null) __obj.updateDynamic("onWaiting")(onWaiting.asInstanceOf[js.Any])
    if (onWaitingCapture != null) __obj.updateDynamic("onWaitingCapture")(onWaitingCapture.asInstanceOf[js.Any])
    if (onWheel != null) __obj.updateDynamic("onWheel")(onWheel.asInstanceOf[js.Any])
    if (onWheelCapture != null) __obj.updateDynamic("onWheelCapture")(onWheelCapture.asInstanceOf[js.Any])
    __obj.asInstanceOf[DOMAttributes[Target]]
  }
}

