package typingsJapgolly.activexLibreoffice.com_.sun.star.xml

import japgolly.scalajs.react.Callback
import typingsJapgolly.activexLibreoffice.LibreOffice.SeqEquiv
import typingsJapgolly.activexLibreoffice.`type`
import typingsJapgolly.activexLibreoffice.com_.sun.star.beans.PropertyValue
import typingsJapgolly.activexLibreoffice.com_.sun.star.uno.XInterface
import typingsJapgolly.activexLibreoffice.com_.sun.star.xml.sax.XDocumentHandler
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/**
  * interface to implement for an XML-based import filter.
  * @since OOo 1.1.2
  */
trait XImportFilter
  extends StObject
     with XInterface {
  
  /**
    * performs the import.
    *
    * The source data (location indicated by **aSourceData** ), and the XML representation of the document must be generated by calls to xocHandler (???)
    * methods.
    * @param aSourceData the {@link com.sun.star.document.MediaDescriptor} which defines the data source
    * @param msUserData Sequence of strings which contains the user data defined in the TypeDetection.xml
    * @param xDocHandler target for the XML document representation
    * @returns `TRUE` if import process is successful
    */
  def importer(aSourceData: SeqEquiv[PropertyValue], xDocHandler: XDocumentHandler, msUserData: SeqEquiv[String]): Boolean
}
object XImportFilter {
  
  inline def apply(
    acquire: Callback,
    importer: (SeqEquiv[PropertyValue], XDocumentHandler, SeqEquiv[String]) => Boolean,
    queryInterface: `type` => Any,
    release: Callback
  ): XImportFilter = {
    val __obj = js.Dynamic.literal(acquire = acquire.toJsFn, importer = js.Any.fromFunction3(importer), queryInterface = js.Any.fromFunction1(queryInterface), release = release.toJsFn)
    __obj.asInstanceOf[XImportFilter]
  }
  
  extension [Self <: XImportFilter](x: Self) {
    
    inline def setImporter(value: (SeqEquiv[PropertyValue], XDocumentHandler, SeqEquiv[String]) => Boolean): Self = StObject.set(x, "importer", js.Any.fromFunction3(value))
  }
}
