package typingsJapgolly.styledComponents

import japgolly.scalajs.react.facade.React.ComponentClassP
import typingsJapgolly.react.mod.FunctionComponent
import typingsJapgolly.std.ReturnType
import typingsJapgolly.styledComponents.nativeDistTypesMod.ExoticComponentWithDisplayName
import typingsJapgolly.styledComponents.nativeDistTypesMod.IStyledComponentFactory
import typingsJapgolly.styledComponents.nativeDistTypesMod.RuleSet
import typingsJapgolly.styledComponents.nativeDistTypesMod.StyledOptions
import typingsJapgolly.styledComponents.styledComponentsStrings.`object`
import typingsJapgolly.styledComponents.styledComponentsStrings.`var`
import typingsJapgolly.styledComponents.styledComponentsStrings.a
import typingsJapgolly.styledComponents.styledComponentsStrings.abbr
import typingsJapgolly.styledComponents.styledComponentsStrings.address
import typingsJapgolly.styledComponents.styledComponentsStrings.animate
import typingsJapgolly.styledComponents.styledComponentsStrings.animateMotion
import typingsJapgolly.styledComponents.styledComponentsStrings.animateTransform
import typingsJapgolly.styledComponents.styledComponentsStrings.area
import typingsJapgolly.styledComponents.styledComponentsStrings.article
import typingsJapgolly.styledComponents.styledComponentsStrings.aside
import typingsJapgolly.styledComponents.styledComponentsStrings.audio
import typingsJapgolly.styledComponents.styledComponentsStrings.b
import typingsJapgolly.styledComponents.styledComponentsStrings.base
import typingsJapgolly.styledComponents.styledComponentsStrings.bdi
import typingsJapgolly.styledComponents.styledComponentsStrings.bdo
import typingsJapgolly.styledComponents.styledComponentsStrings.big
import typingsJapgolly.styledComponents.styledComponentsStrings.blockquote
import typingsJapgolly.styledComponents.styledComponentsStrings.body
import typingsJapgolly.styledComponents.styledComponentsStrings.br
import typingsJapgolly.styledComponents.styledComponentsStrings.button
import typingsJapgolly.styledComponents.styledComponentsStrings.canvas
import typingsJapgolly.styledComponents.styledComponentsStrings.caption
import typingsJapgolly.styledComponents.styledComponentsStrings.circle
import typingsJapgolly.styledComponents.styledComponentsStrings.cite
import typingsJapgolly.styledComponents.styledComponentsStrings.clipPath
import typingsJapgolly.styledComponents.styledComponentsStrings.code
import typingsJapgolly.styledComponents.styledComponentsStrings.col
import typingsJapgolly.styledComponents.styledComponentsStrings.colgroup
import typingsJapgolly.styledComponents.styledComponentsStrings.data
import typingsJapgolly.styledComponents.styledComponentsStrings.datalist
import typingsJapgolly.styledComponents.styledComponentsStrings.dd
import typingsJapgolly.styledComponents.styledComponentsStrings.defs
import typingsJapgolly.styledComponents.styledComponentsStrings.del
import typingsJapgolly.styledComponents.styledComponentsStrings.desc
import typingsJapgolly.styledComponents.styledComponentsStrings.details
import typingsJapgolly.styledComponents.styledComponentsStrings.dfn
import typingsJapgolly.styledComponents.styledComponentsStrings.dialog
import typingsJapgolly.styledComponents.styledComponentsStrings.div
import typingsJapgolly.styledComponents.styledComponentsStrings.dl
import typingsJapgolly.styledComponents.styledComponentsStrings.dt
import typingsJapgolly.styledComponents.styledComponentsStrings.ellipse
import typingsJapgolly.styledComponents.styledComponentsStrings.em
import typingsJapgolly.styledComponents.styledComponentsStrings.embed
import typingsJapgolly.styledComponents.styledComponentsStrings.feBlend
import typingsJapgolly.styledComponents.styledComponentsStrings.feColorMatrix
import typingsJapgolly.styledComponents.styledComponentsStrings.feComponentTransfer
import typingsJapgolly.styledComponents.styledComponentsStrings.feComposite
import typingsJapgolly.styledComponents.styledComponentsStrings.feConvolveMatrix
import typingsJapgolly.styledComponents.styledComponentsStrings.feDiffuseLighting
import typingsJapgolly.styledComponents.styledComponentsStrings.feDisplacementMap
import typingsJapgolly.styledComponents.styledComponentsStrings.feDistantLight
import typingsJapgolly.styledComponents.styledComponentsStrings.feDropShadow
import typingsJapgolly.styledComponents.styledComponentsStrings.feFlood
import typingsJapgolly.styledComponents.styledComponentsStrings.feFuncA
import typingsJapgolly.styledComponents.styledComponentsStrings.feFuncB
import typingsJapgolly.styledComponents.styledComponentsStrings.feFuncG
import typingsJapgolly.styledComponents.styledComponentsStrings.feFuncR
import typingsJapgolly.styledComponents.styledComponentsStrings.feGaussianBlur
import typingsJapgolly.styledComponents.styledComponentsStrings.feImage
import typingsJapgolly.styledComponents.styledComponentsStrings.feMerge
import typingsJapgolly.styledComponents.styledComponentsStrings.feMergeNode
import typingsJapgolly.styledComponents.styledComponentsStrings.feMorphology
import typingsJapgolly.styledComponents.styledComponentsStrings.feOffset
import typingsJapgolly.styledComponents.styledComponentsStrings.fePointLight
import typingsJapgolly.styledComponents.styledComponentsStrings.feSpecularLighting
import typingsJapgolly.styledComponents.styledComponentsStrings.feSpotLight
import typingsJapgolly.styledComponents.styledComponentsStrings.feTile
import typingsJapgolly.styledComponents.styledComponentsStrings.feTurbulence
import typingsJapgolly.styledComponents.styledComponentsStrings.fieldset
import typingsJapgolly.styledComponents.styledComponentsStrings.figcaption
import typingsJapgolly.styledComponents.styledComponentsStrings.figure
import typingsJapgolly.styledComponents.styledComponentsStrings.filter
import typingsJapgolly.styledComponents.styledComponentsStrings.footer
import typingsJapgolly.styledComponents.styledComponentsStrings.foreignObject
import typingsJapgolly.styledComponents.styledComponentsStrings.form
import typingsJapgolly.styledComponents.styledComponentsStrings.g
import typingsJapgolly.styledComponents.styledComponentsStrings.h1
import typingsJapgolly.styledComponents.styledComponentsStrings.h2
import typingsJapgolly.styledComponents.styledComponentsStrings.h3
import typingsJapgolly.styledComponents.styledComponentsStrings.h4
import typingsJapgolly.styledComponents.styledComponentsStrings.h5
import typingsJapgolly.styledComponents.styledComponentsStrings.h6
import typingsJapgolly.styledComponents.styledComponentsStrings.head
import typingsJapgolly.styledComponents.styledComponentsStrings.header
import typingsJapgolly.styledComponents.styledComponentsStrings.hgroup
import typingsJapgolly.styledComponents.styledComponentsStrings.hr
import typingsJapgolly.styledComponents.styledComponentsStrings.html
import typingsJapgolly.styledComponents.styledComponentsStrings.i
import typingsJapgolly.styledComponents.styledComponentsStrings.iframe
import typingsJapgolly.styledComponents.styledComponentsStrings.image
import typingsJapgolly.styledComponents.styledComponentsStrings.img
import typingsJapgolly.styledComponents.styledComponentsStrings.input
import typingsJapgolly.styledComponents.styledComponentsStrings.ins
import typingsJapgolly.styledComponents.styledComponentsStrings.kbd
import typingsJapgolly.styledComponents.styledComponentsStrings.keygen
import typingsJapgolly.styledComponents.styledComponentsStrings.label
import typingsJapgolly.styledComponents.styledComponentsStrings.legend
import typingsJapgolly.styledComponents.styledComponentsStrings.li
import typingsJapgolly.styledComponents.styledComponentsStrings.line
import typingsJapgolly.styledComponents.styledComponentsStrings.linearGradient
import typingsJapgolly.styledComponents.styledComponentsStrings.link
import typingsJapgolly.styledComponents.styledComponentsStrings.main
import typingsJapgolly.styledComponents.styledComponentsStrings.map
import typingsJapgolly.styledComponents.styledComponentsStrings.mark
import typingsJapgolly.styledComponents.styledComponentsStrings.marker
import typingsJapgolly.styledComponents.styledComponentsStrings.mask
import typingsJapgolly.styledComponents.styledComponentsStrings.menu
import typingsJapgolly.styledComponents.styledComponentsStrings.menuitem
import typingsJapgolly.styledComponents.styledComponentsStrings.meta
import typingsJapgolly.styledComponents.styledComponentsStrings.metadata
import typingsJapgolly.styledComponents.styledComponentsStrings.meter
import typingsJapgolly.styledComponents.styledComponentsStrings.mpath
import typingsJapgolly.styledComponents.styledComponentsStrings.nav
import typingsJapgolly.styledComponents.styledComponentsStrings.noindex
import typingsJapgolly.styledComponents.styledComponentsStrings.noscript
import typingsJapgolly.styledComponents.styledComponentsStrings.ol
import typingsJapgolly.styledComponents.styledComponentsStrings.optgroup
import typingsJapgolly.styledComponents.styledComponentsStrings.option
import typingsJapgolly.styledComponents.styledComponentsStrings.output
import typingsJapgolly.styledComponents.styledComponentsStrings.p
import typingsJapgolly.styledComponents.styledComponentsStrings.param
import typingsJapgolly.styledComponents.styledComponentsStrings.path
import typingsJapgolly.styledComponents.styledComponentsStrings.pattern
import typingsJapgolly.styledComponents.styledComponentsStrings.picture
import typingsJapgolly.styledComponents.styledComponentsStrings.polygon
import typingsJapgolly.styledComponents.styledComponentsStrings.polyline
import typingsJapgolly.styledComponents.styledComponentsStrings.pre
import typingsJapgolly.styledComponents.styledComponentsStrings.progress
import typingsJapgolly.styledComponents.styledComponentsStrings.q
import typingsJapgolly.styledComponents.styledComponentsStrings.radialGradient
import typingsJapgolly.styledComponents.styledComponentsStrings.rect
import typingsJapgolly.styledComponents.styledComponentsStrings.rp
import typingsJapgolly.styledComponents.styledComponentsStrings.rt
import typingsJapgolly.styledComponents.styledComponentsStrings.ruby
import typingsJapgolly.styledComponents.styledComponentsStrings.s
import typingsJapgolly.styledComponents.styledComponentsStrings.samp
import typingsJapgolly.styledComponents.styledComponentsStrings.script
import typingsJapgolly.styledComponents.styledComponentsStrings.section
import typingsJapgolly.styledComponents.styledComponentsStrings.select
import typingsJapgolly.styledComponents.styledComponentsStrings.slot
import typingsJapgolly.styledComponents.styledComponentsStrings.small
import typingsJapgolly.styledComponents.styledComponentsStrings.source
import typingsJapgolly.styledComponents.styledComponentsStrings.span
import typingsJapgolly.styledComponents.styledComponentsStrings.stop
import typingsJapgolly.styledComponents.styledComponentsStrings.strong
import typingsJapgolly.styledComponents.styledComponentsStrings.style
import typingsJapgolly.styledComponents.styledComponentsStrings.sub
import typingsJapgolly.styledComponents.styledComponentsStrings.summary
import typingsJapgolly.styledComponents.styledComponentsStrings.sup
import typingsJapgolly.styledComponents.styledComponentsStrings.svg
import typingsJapgolly.styledComponents.styledComponentsStrings.switch
import typingsJapgolly.styledComponents.styledComponentsStrings.symbol
import typingsJapgolly.styledComponents.styledComponentsStrings.table
import typingsJapgolly.styledComponents.styledComponentsStrings.tbody
import typingsJapgolly.styledComponents.styledComponentsStrings.td
import typingsJapgolly.styledComponents.styledComponentsStrings.template
import typingsJapgolly.styledComponents.styledComponentsStrings.text
import typingsJapgolly.styledComponents.styledComponentsStrings.textPath
import typingsJapgolly.styledComponents.styledComponentsStrings.textarea
import typingsJapgolly.styledComponents.styledComponentsStrings.tfoot
import typingsJapgolly.styledComponents.styledComponentsStrings.th
import typingsJapgolly.styledComponents.styledComponentsStrings.thead
import typingsJapgolly.styledComponents.styledComponentsStrings.time
import typingsJapgolly.styledComponents.styledComponentsStrings.title
import typingsJapgolly.styledComponents.styledComponentsStrings.tr
import typingsJapgolly.styledComponents.styledComponentsStrings.track
import typingsJapgolly.styledComponents.styledComponentsStrings.tspan
import typingsJapgolly.styledComponents.styledComponentsStrings.u
import typingsJapgolly.styledComponents.styledComponentsStrings.ul
import typingsJapgolly.styledComponents.styledComponentsStrings.use
import typingsJapgolly.styledComponents.styledComponentsStrings.video
import typingsJapgolly.styledComponents.styledComponentsStrings.view
import typingsJapgolly.styledComponents.styledComponentsStrings.wbr
import typingsJapgolly.styledComponents.styledComponentsStrings.web
import typingsJapgolly.styledComponents.styledComponentsStrings.webview
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object nativeDistModelsStyledComponentMod {
  
  @JSImport("styled-components/native/dist/models/StyledComponent", JSImport.Namespace)
  @js.native
  val ^ : js.Any = js.native
  
  inline def default[OuterProps /* <: js.Object */, Statics](target: `object`, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, `object`, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, `object`, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: `var`, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, `var`, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, `var`, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: abbr, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, abbr, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, abbr, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: address, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, address, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, address, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: animateMotion, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, animateMotion, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, animateMotion, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: animateTransform, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, animateTransform, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, animateTransform, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: animate, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, animate, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, animate, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: a, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, a, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, a, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: area, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, area, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, area, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: article, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, article, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, article, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: aside, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, aside, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, aside, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: audio, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, audio, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, audio, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: base, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, base, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, base, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: bdi, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, bdi, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, bdi, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: bdo, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, bdo, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, bdo, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: big, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, big, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, big, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: blockquote, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, blockquote, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, blockquote, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: body, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, body, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, body, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: b, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, b, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, b, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: br, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, br, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, br, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: button, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, button, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, button, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: canvas, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, canvas, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, canvas, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: caption, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, caption, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, caption, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: circle, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, circle, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, circle, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: cite, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, cite, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, cite, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: clipPath, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, clipPath, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, clipPath, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: code, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, code, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, code, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: colgroup, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, colgroup, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, colgroup, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: col, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, col, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, col, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: datalist, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, datalist, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, datalist, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: data, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, data, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, data, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: dd, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, dd, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, dd, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: defs, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, defs, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, defs, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: del, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, del, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, del, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: desc, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, desc, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, desc, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: details, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, details, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, details, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: dfn, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, dfn, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, dfn, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: dialog, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, dialog, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, dialog, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: div, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, div, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, div, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: dl, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, dl, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, dl, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: dt, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, dt, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, dt, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: ellipse, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, ellipse, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, ellipse, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: embed, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, embed, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, embed, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: em, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, em, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, em, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feBlend, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feBlend, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feBlend, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feColorMatrix, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feColorMatrix, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feColorMatrix, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feComponentTransfer, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feComponentTransfer, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feComponentTransfer, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feComposite, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feComposite, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feComposite, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feConvolveMatrix, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feConvolveMatrix, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feConvolveMatrix, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feDiffuseLighting, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feDiffuseLighting, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feDiffuseLighting, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feDisplacementMap, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feDisplacementMap, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feDisplacementMap, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feDistantLight, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feDistantLight, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feDistantLight, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feDropShadow, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feDropShadow, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feDropShadow, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feFlood, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feFlood, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feFlood, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feFuncA, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feFuncA, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feFuncA, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feFuncB, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feFuncB, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feFuncB, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feFuncG, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feFuncG, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feFuncG, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feFuncR, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feFuncR, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feFuncR, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feGaussianBlur, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feGaussianBlur, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feGaussianBlur, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feImage, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feImage, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feImage, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feMergeNode, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feMergeNode, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feMergeNode, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feMerge, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feMerge, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feMerge, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feMorphology, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feMorphology, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feMorphology, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feOffset, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feOffset, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feOffset, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: fePointLight, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, fePointLight, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, fePointLight, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feSpecularLighting, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feSpecularLighting, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feSpecularLighting, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feSpotLight, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feSpotLight, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feSpotLight, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feTile, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feTile, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feTile, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: feTurbulence, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, feTurbulence, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, feTurbulence, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: fieldset, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, fieldset, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, fieldset, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: figcaption, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, figcaption, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, figcaption, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: figure, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, figure, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, figure, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: filter, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, filter, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, filter, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: footer, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, footer, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, footer, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: foreignObject, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, foreignObject, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, foreignObject, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: form, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, form, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, form, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: g, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, g, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, g, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h1, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h1, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h1, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h2, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h2, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h2, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h3, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h3, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h3, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h4, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h4, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h4, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h5, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h5, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h5, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: h6, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, h6, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, h6, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: header, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, header, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, header, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: head, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, head, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, head, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: hgroup, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, hgroup, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, hgroup, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: hr, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, hr, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, hr, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: html, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, html, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, html, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: iframe, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, iframe, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, iframe, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: image, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, image, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, image, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: img, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, img, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, img, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: input, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, input, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, input, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: ins, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, ins, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, ins, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: i, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, i, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, i, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: kbd, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, kbd, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, kbd, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: keygen, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, keygen, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, keygen, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: label, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, label, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, label, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: legend, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, legend, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, legend, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: linearGradient, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, linearGradient, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, linearGradient, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: line, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, line, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, line, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: link, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, link, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, link, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: li, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, li, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, li, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: main, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, main, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, main, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: map, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, map, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, map, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: marker, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, marker, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, marker, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: mark, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, mark, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, mark, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: mask, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, mask, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, mask, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: menuitem, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, menuitem, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, menuitem, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: menu, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, menu, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, menu, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: metadata, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, metadata, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, metadata, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: meta, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, meta, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, meta, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: meter, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, meter, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, meter, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: mpath, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, mpath, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, mpath, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: nav, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, nav, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, nav, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: noindex, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, noindex, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, noindex, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: noscript, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, noscript, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, noscript, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: ol, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, ol, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, ol, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: optgroup, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, optgroup, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, optgroup, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: option, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, option, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, option, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: output, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, output, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, output, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: param, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, param, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, param, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: path, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, path, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, path, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: pattern, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, pattern, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, pattern, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: picture, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, picture, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, picture, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: polygon, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, polygon, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, polygon, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: polyline, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, polyline, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, polyline, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: p, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, p, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, p, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: pre, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, pre, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, pre, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: progress, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, progress, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, progress, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: q, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, q, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, q, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: radialGradient, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, radialGradient, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, radialGradient, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: rect, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, rect, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, rect, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: rp, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, rp, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, rp, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: rt, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, rt, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, rt, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: ruby, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, ruby, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, ruby, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: samp, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, samp, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, samp, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: script, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, script, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, script, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: section, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, section, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, section, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: select, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, select, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, select, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: slot, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, slot, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, slot, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: small, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, small, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, small, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: s, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, s, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, s, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: source, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, source, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, source, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: span, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, span, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, span, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: stop, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, stop, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, stop, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: strong, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, strong, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, strong, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: style, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, style, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, style, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: sub, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, sub, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, sub, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: summary, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, summary, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, summary, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: sup, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, sup, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, sup, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: svg, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, svg, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, svg, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: switch, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, switch, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, switch, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: symbol, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, symbol, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, symbol, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: table, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, table, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, table, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: tbody, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, tbody, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, tbody, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: td, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, td, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, td, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: template, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, template, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, template, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: textPath, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, textPath, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, textPath, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: textarea, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, textarea, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, textarea, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: text, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, text, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, text, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: tfoot, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, tfoot, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, tfoot, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: thead, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, thead, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, thead, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: th, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, th, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, th, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: time, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, time, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, time, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: title, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, title, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, title, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: track, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, track, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, track, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: tr, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, tr, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, tr, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: tspan, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, tspan, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, tspan, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: ul, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, ul, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, ul, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: u, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, u, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, u, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: use, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, use, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, use, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: video, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, video, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, video, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: view, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, view, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, view, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: wbr, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, wbr, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, wbr, OuterProps, Statics]]]
  inline def default[OuterProps /* <: js.Object */, Statics](target: webview, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, webview, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, webview, OuterProps, Statics]]]
  
  inline def default_web[OuterProps /* <: js.Object */, Statics](target: String, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, String, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, String, OuterProps, Statics]]]
  inline def default_web[Target /* <: ExoticComponentWithDisplayName[Any] | (ComponentClassP[Any & js.Object]) | FunctionComponent[Any] */, OuterProps /* <: js.Object */, Statics](target: Target, options: StyledOptions[web, OuterProps], rules: RuleSet[OuterProps]): ReturnType[IStyledComponentFactory[web, Target, OuterProps, Statics]] = (^.asInstanceOf[js.Dynamic].applyDynamic("default")(target.asInstanceOf[js.Any], options.asInstanceOf[js.Any], rules.asInstanceOf[js.Any])).asInstanceOf[ReturnType[IStyledComponentFactory[web, Target, OuterProps, Statics]]]
}
