package typingsJapgolly.schematicsAngular.thirdPartyGithubDotcomMicrosoftTypeScriptLibTypescriptMod.server

import typingsJapgolly.schematicsAngular.schematicsAngularStrings.actionColonColoninvalidate
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.actionColonColonpackageInstalled
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.actionColonColonset
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.eventColonColonbeginInstallTypes
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.eventColonColonendInstallTypes
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.eventColonColoninitializationFailed
import typingsJapgolly.schematicsAngular.schematicsAngularStrings.eventColonColontypesRegistry
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}


type ActionInvalidate = actionColonColoninvalidate

type ActionPackageInstalled = actionColonColonpackageInstalled

type ActionSet = actionColonColonset

type EventBeginInstallTypes = eventColonColonbeginInstallTypes

type EventEndInstallTypes = eventColonColonendInstallTypes

type EventInitializationFailed = eventColonColoninitializationFailed

type EventTypesRegistry = eventColonColontypesRegistry
